### ISSUE TITLE
Can you expose the assigned IP address to the kernel boot screen?

### ISSUE THREAD

**Issue by PeterSuh-Q3** [fbelavenuto/arpl#1]
I can find the IP address assigned by the router with find.synology.com, but
It would be convenient to know the assigned IP address in advance.

Proxmox also informs the console of the assigned IP when logging in.
I know esxi does that too.
It seems that IP exposure on the Booing screen has nothing to do with security issues.

Is it possible?

**Comment by fbelavenuto** [comment]
Hello, the loader displays the IP both in the console and in the menu.
About proxmox I know that it is necessary to install a software called agent so that the proxmox interface can know the guest IPs, but I don't know if it is possible to install this software inside the DSM.

**Comment by dalso0418** [comment]
It's a fantastic update.

**Comment by PeterSuh-Q3** [comment]
thank you I think it will be very useful.
This is a feature that has not been found in any Redfill Loader yet.!!!
