### ISSUE TITLE
can use DiskIdxMap for sas controller?

### ISSUE THREAD

**Issue by nanalynKR** [fbelavenuto/arpl#100]
I build arpl with two sas controllers.
When configured in a test environment, the build and use itself is very normal.
Please contact us if you have any concerns.
It's not that important to use..
Disks attached to the sas controller do not seem to be reconciled successfully by sataportmap or diskidxmap.
Is there no way at all because it's dsm's own problem, or is there something I don't know about?
I am always very grateful.

**Comment by fbelavenuto** [comment]
Hi, sataportmap and diskidxmap works only with the SATA ports!

**Comment by nanalynKR** [comment]
![image](https://user-images.githubusercontent.com/109270188/185018598-d96429bf-f7ab-4387-836d-64369de200f4.png)
![image](https://user-images.githubusercontent.com/109270188/185018649-653e38ef-f1f5-4841-95e4-b62f438cf478.png)
Thank you! for answer.
The only way is to empty slots 1 and 2 and use them.
