### ISSUE TITLE
What format is used to add "sataport map" and "diskidxmap" to that file?

### ISSUE THREAD

**Issue by xiaohanxiansheng** [fbelavenuto/arpl#103]
What format is used to add "sataport map" and "diskidxmap" to that file?

**Comment by xiaohanxiansheng** [comment]
> 

thank you

**Comment by fbelavenuto** [comment]
If there are another trouble, please open a new issue

**Comment by lancaitou** [comment]
What's wrong with God's attaching NTFS hard disk with esata? This is machine translated English!
