### ISSUE TITLE
Compatibility HP G7 N54L

### ISSUE THREAD

**Issue by yoshito83** [fbelavenuto/arpl#110]
Hi guys!! very good job i am very exited with your proyect.

ok, but... I have a problem with my G7 N54L. In this machine i have 12GB to RAM. I make a usb but don´t work. The usb launch the kernel, but no continue. I think that system is crashed.

The same USB i boot in same machine but across proxmox and boot ok. The problem is when use this USB to boot in real machine.

Red-Pill 0.8 works ok and i don´t any problem this. The only problem is red-pill no boot 42951 but ARPL yes.

I want use ARPL 

Thank with your help

**Comment by fbelavenuto** [comment]
Hi, can you type "lspci -nnk" from the TC prompt and post here?

**Comment by yoshito83** [comment]
Hi

Yes, but in this moment, the machine execute proxmox i attach this response for this comandos, but i don' t have if  file is validar for you.

If you need other file, tell me.

Thanks 
[lspci.txt](https://github.com/fbelavenuto/arpl/files/9373098/lspci.txt)

**Comment by yoshito83** [comment]
[lspci.log](https://github.com/fbelavenuto/arpl/files/9373582/lspci.log)

Hi

This is te retorno of comandos. At the moment the servir execute proxmox,  i don't have that content of file is validar for resolved this problem.

If file is not valid, tell me and try get other file.

Thanks

**Comment by pocopico** [comment]
Please make sure that bios is set correctly 

In Advance page, [disable C1E Support](https://xpenology.com/forum/topic/7527-hp-n54l-dsm-61-onwards/?page=11&tab=comments#comment-76876)

**Comment by yoshito83** [comment]
![16610075776386447146968652871226](https://user-images.githubusercontent.com/111462248/185752946-91774fae-8c13-44ac-8593-15019cac35a3.jpg)
Good idea, but not.

C1E sopport is disable. Red-pill run ok, but arpl not.

Thanks

**Comment by fbelavenuto** [comment]
Please, test the v0.4-alpha8 release

**Comment by WickedDurkie** [comment]
I tested the v0.4-alpha9 release and it hangs when booting DSM

**Comment by ElmerALucier** [comment]
> I tested the v0.4-alpha9 release and it hangs when booting DSM

Same issue with booting stuck on v0.4-alpha11 (HP G7 N40L)

**Comment by yoshito83** [comment]
Goodmorning guys

the thursday, I tested versión arpl 0.9 and problem persist.

The g7 n40 and n54 is a same machine, only change the processor, amd turion x2 n54 o n40 but it s same machine.

At the moment, continue equal

Thanks guys

**Comment by fbelavenuto** [comment]
Guys, please update the Loader and Addons (or burn v0.4a12), add the addon "dbgutils", rebuild it and boots.
When the PC shutdown, please get the usb flash drive and check if exists a folder named "logs" in the first partition of flash drive (Windows S.O. recognize), get the files and post here.

**Comment by ElmerALucier** [comment]
It is very strange but after all the actions I do not get the Logs folder (I use the V0.4A12 version, add the DBGUTILS addon, rebuild it and press the Boot button, after 15 minutes I turn off the server manually because nothing else happens; I also tried booting another time and after another 15 minutes of waiting and forced shutdown - it is still nothing)...

**Comment by fbelavenuto** [comment]
Thanks for the test, so my technique is not 100%, back to the drawing board!

**Comment by pocopico** [comment]
With the introduction of TCRP Friend (buildroot) , there are reports on my side as well of KP. We tried several workarounds but system gets a kernel panic after kexec. 

We have tested by setting various linux command line options accoring but not limited to the following : 

https://forums.centos.org/viewtopic.php?t=56420

**Comment by fbelavenuto** [comment]
Thank you for the report. Then we will need to add an option in grub to boot directly.

**Comment by fbelavenuto** [comment]
Please burn to USB flash drive the image from here:
https://github.com/fbelavenuto/arpl/actions/runs/3244163012
Reconfigure loader, before boot select the "Switch direct boot" option to activate it and boot.

**Comment by WickedDurkie** [comment]
Thank you for following up. When I do this, the auto update feature probably does not work? Is there any change to get this working?

**Comment by fbelavenuto** [comment]
Auto update do not work for this.

**Comment by jackavenger** [comment]
Mine N40L boots well. I have 16Gb RAM and no extra cards in PCI-E slot

**Comment by jackavenger** [comment]
Sorry. N40L/8Gb RAM, no cards in PCI-E. Got KP during boot. Ready to do tests, but i'm a noob.

**Comment by jackavenger** [comment]
> Please burn to USB flash drive the image from here:
> https://github.com/fbelavenuto/arpl/actions/runs/3244163012
> Reconfigure loader, before boot select the "Switch direct boot" option to activate it and boot.
Thank you! This works for me.
