### ISSUE TITLE
installing external driver for Megaraid/LSI/Adaptec

### ISSUE THREAD

**Issue by gcat000** [fbelavenuto/arpl#131]
how can i install an external driver on an already assebled bootloader arpl?
i want to install raid controller LSI/Megaraid for SAS HDDs, but don't understand how i can add external driver

**Comment by fbelavenuto** [comment]
You don't need to add drivers, there is already a driver for this card, in this case "mpt3sas".
If you have an old version, you can enter the loader, update the loader and modules through the update menu, recreate the loader and boot.

**Comment by gcat000** [comment]
i tried the controller LSI 9271-8i
disk was initializes in a controller bois. virtual disk is OK
but DSM not recognize and can't see disk. pluggen шетщ controller
without disk initialization by the controller, the disk is also not visible in the DSM system

**Comment by gcat000** [comment]
Assembly 
Dsm7.1.-42661 and ds3622xs+

**Comment by darkguy2008** [comment]
Is there a known way we can add custom drivers to this? It seems ARPL is missing the "alx" driver for My Killer Network E2000 internet (Atheros AR8161). I can confirm booting with TCRP works, ARPL doesn't.

**Comment by fbelavenuto** [comment]
Hi, please test with the last alpha version:
https://github.com/fbelavenuto/arpl/releases/tag/v0.4-alpha7

**Comment by gcat000** [comment]
thank you~ i will try tomorrow when i'm at work.
I have a test server there.
