### ISSUE TITLE
Failed to waiting IP

### ISSUE THREAD

**Issue by wangwork-kelemige** [fbelavenuto/arpl#132]
Hello
 the tool waiting ip  =error， my lan _devices is RTL8111H，it seems same to RTL8169 or RTL8168，So does the tool support them?

my computer info
CPU : J5005
MB : J5005
lan: Realtek  RTL8111HN

**Comment by fbelavenuto** [comment]
Please type 'lspci -nnk' and post the result (Can be a cel photo)

**Comment by wangwork-kelemige** [comment]
![图片](https://user-images.githubusercontent.com/72541560/186458575-11b50db5-6665-4b22-bfb0-74f27e37c046.png)
Hi the ethernet controller is R8168.

**Comment by fbelavenuto** [comment]
Ok, very strange!! Does your network have a DHCP server?

**Comment by wangwork-kelemige** [comment]
sure，the DHCP server is enable，it‘s strange，i can't find DSM devices with DS918 bootloader support RTL8168 in the synology assistant, but change the DS3617 bootloader support RTL8169,the network can identify DSM devices。

**Comment by Cryental** [comment]
Can you try to run ifconfig?

**Comment by wangwork-kelemige** [comment]
ifconfig information：
![图片](https://user-images.githubusercontent.com/72541560/186689619-053d9da5-f8d7-45bd-a4e7-916ffa38f7b0.png)

**Comment by fbelavenuto** [comment]
Please test with this image:
https://github.com/fbelavenuto/arpl/actions/runs/2933332549

**Comment by wangwork-kelemige** [comment]
Very exciting，it successfully got the IP with new image，a new question：can  i build ds918 bootloader with new image?
![图片](https://user-images.githubusercontent.com/72541560/186923458-c5e9bd3e-2362-4dd5-a23c-48da868725a9.png)

**Comment by fbelavenuto** [comment]
I believe not! DS918 needs a more new CPU. You can test disabling flag restriction, the DS918 model is apper and you can test if it works

I do not think so! DS918 needs a newer CPU. You can test disable flag restriction, DS918 model is apper and you can test if it works.

**Comment by wangwork-kelemige** [comment]
You are right,I have successfully build the bootloader of DS918，thanks for your support。

**Comment by fbelavenuto** [comment]
Good!! Closing issue
