### ISSUE TITLE
Virtual Machine Manager Not letting linux install complete

### ISSUE THREAD

**Issue by Tauvil** [fbelavenuto/arpl#137]
Trying to install Ubuntu in Virtual machine and it gets stuck at this screen. Any idea's what to do ?
https://i.postimg.cc/kXq41JBd/Ubunto.png
Debian Also 
https://i.postimg.cc/02nNhTwK/Ubun-DEBian.png
Thank You

**Comment by fbelavenuto** [comment]
Hi, did you manage to install it? I saw your problem but I didn't respond because I don't know what it could be.

**Comment by Tauvil** [comment]
I did a reinstall with v0.4-alpha6 yesterday (smooth install) and retried VVM install ubuntu and it stopped install at the same point. 

Bare Metal install Dell T1700 i7-4790 16gig ram 

oWell not very important I can always use VMWare, Maybe just that machine does not like VVM ( laugh )

I will try on a different machine later this week and let you know
Gerald 
    On Wednesday, September 7, 2022 at 01:11:05 PM PDT, Fabio Belavenuto ***@***.***> wrote:  
 
 


Hi, did you manage to install it? I saw your problem but I didn't respond because I don't know what it could be.

**Comment by Tauvil** [comment]
VMM CPU compatibility mode needed to be turned on 

Thank You  
    On Wednesday, September 7, 2022 at 01:11:05 PM PDT, Fabio Belavenuto ***@***.***> wrote:  
 
 


Hi, did you manage to install it? I saw your problem but I didn't respond because I don't know what it could be.

**Comment by StatCombo** [comment]
so do you solve this problem? i have same problem with linux install!
