### ISSUE TITLE
30 questions about adding SATA controller to esxi and each display hard disk interface

### ISSUE THREAD

**Issue by cocoakeer** [fbelavenuto/arpl#138]
Hello! Excuse me.

I currently use v0.4-alpha4 to test and compile, and find that every time a SATA controller is added to the esxi virtual machine, 30 hard disk interfaces are displayed in the hard disk status. At the same time, the parameter settings of sataport map and diskidxmap are not effective. I wonder if I have a problem? Looking forward to your reply, thank you very much.
<img width="280" alt="image" src="https://user-images.githubusercontent.com/112269603/187057561-26fcd426-01be-4dcd-85ba-fa991a5361af.png">
<img width="766" alt="image" src="https://user-images.githubusercontent.com/112269603/187057569-cf5719ab-a393-4fde-a467-0f11d2744967.png">
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/112269603/187057638-5e909acf-6d99-4a88-a90d-72eb0dd31a6b.png">
<img width="860" alt="image" src="https://user-images.githubusercontent.com/112269603/187057576-b9613daa-480c-47be-aa2f-13496fb0c0df.png">

**Comment by fbelavenuto** [comment]
First try to remove the "internalportcfg" synoinfo entry. If it still doesn't work go to the synoinfo menu and manually set the amount of disks to 3
