### ISSUE TITLE
vmw_pvscsi

### ISSUE THREAD

**Issue by AuxXxilium** [fbelavenuto/arpl#139]
Thank you for sharing this. It works very well on baremetal installation. but on esxi i have a problem that all drives attached to vmw_pvscsi are not showing up. is there something that i have to load a module or something on my own?

**Comment by fbelavenuto** [comment]
Which DSM model are you testing? Models with DT (device-tree) only work with SATA, they will not recognize another type of disk (SAS, SCSI).

**Comment by AuxXxilium** [comment]
DS3622xs+ with DSM 7.1 and 7.1.1.

**Comment by fbelavenuto** [comment]
Okay, so it has to work. Can you add a serial port on ESXi, set it to save to txt file and then send it here?

**Comment by fbelavenuto** [comment]
Okay, now I understand! This was not supposed to happen!
In this case, type at the loader prompt:
lspci -nnk
And post the result here, please.

**Comment by AuxXxilium** [comment]
![Screenshot 2022-08-29 192646](https://user-images.githubusercontent.com/67025065/187261772-6ac192b6-9963-40c8-a7c0-edec78a6b479.png)
![Screenshot 2022-08-29 192633](https://user-images.githubusercontent.com/67025065/187261776-0776f17b-138d-4169-b636-acffc29b9e3e.png)
It states that the Kernel Module is loaded.

**Comment by AuxXxilium** [comment]
And can you please tell me, how to add a second "original-mac"?

**Comment by fbelavenuto** [comment]
This screen will show only the SATA ports:
![image](https://user-images.githubusercontent.com/11461290/187279041-dd86642b-68f8-412e-851c-2579975f60ad.png)

The kernel module is loaded.
You will be able to see the SCSI disks (and others) with the command:
ls -la /dev/sd*

Try adding in the "cmdline" menu an entry "SataPortMap" with value "1" and test into DSM

**Comment by fbelavenuto** [comment]
> And can you please tell me, how to add a second "original-mac"?
This entry in the configuration file is only used to reset the MAC of the first port by the menu.sh script. Do not edit it!

If you want to define the MACs of two ports, add some entries in the "cmdline" menu:
"mac1" with value of the first network interface (must already be configured)
"mac2" with value of second network interface
PS: Only digits, ex: "001122334455"
And "netif_num" with value 2

In the configuration file it should look like this:
...
cmdline:
   netif_num: 2
   mac1: 001122334455
   mac2: 66778899AABB
...

**Comment by AuxXxilium** [comment]
> This screen will show only the SATA ports: ![image](https://user-images.githubusercontent.com/11461290/187279041-dd86642b-68f8-412e-851c-2579975f60ad.png)
> 
> The kernel module is loaded. You will be able to see the SCSI disks (and others) with the command: ls -la /dev/sd*
> 
> Try adding in the "cmdline" menu an entry "SataPortMap" with value "1" and test into DSM

SataPortMap 1 is working. PVSCI is showing up. Thank you
