### ISSUE TITLE
alpha4-proxmox-vm error

### ISSUE THREAD

**Issue by dalso0418** [fbelavenuto/arpl#140]
Hello.
I am reporting the following error when building the boot loader from arpl in Proxmox.

The same error occurred when the build version was set to 41951 and failed and set to 42218.

Thank you always.

*Please understand if there is a misinterpretation of the text written through the translator.

![image](https://user-images.githubusercontent.com/107911055/188271225-d958ff00-d853-445e-8209-25dab0d2f22e.png)
![image](https://user-images.githubusercontent.com/107911055/188271229-052d6667-a78a-40fa-823a-c95063ca3022.png)

**Comment by dalso0418** [comment]
This error occurred only when building with 42591 and did not occur when building with 42218.

**Comment by fbelavenuto** [comment]
Hi, please add more RAM for your VM. 4GB minimum required

**Comment by dalso0418** [comment]
Yes, thank you for checking
