### ISSUE TITLE
DSM 7.1.1.-42962 update fail

### ISSUE THREAD

**Issue by dalso0418** [fbelavenuto/arpl#141]
Hello.

I am reporting that the update failed because there was no information about the version in 7.1.1-42962, which was updated today.
![image](https://user-images.githubusercontent.com/107911055/188440535-8336234a-c0e9-404e-810b-acd7b8f3d997.png)

Thank you.

**Comment by fbelavenuto** [comment]
Update the loader for the v0.4-alpha5 version, I've added the new buildnumber.

**Comment by dalso0418** [comment]
Yes, thank you for checking
