### ISSUE TITLE
Freezes when it boots through VMware Workstation

### ISSUE THREAD

**Issue by cvc90** [fbelavenuto/arpl#145]
Hi, with the latest updates (v0.4-alpha5 and v0.4-alpha6) it freezes when it boots through VMware® Workstation 16 Pro as seen in the image, should something be changed in the configuration? 

If accessed through the web/ssh interface, it is only through the VMware® Workstation 16 Pro interface

![image](https://user-images.githubusercontent.com/76731844/188596341-9c2e27fb-faf3-4db6-8bfc-97cee3bc126f.png)

Buenas, con las ultimas actualizaciones (v0.4-alpha5 y v0.4-alpha6) se queda congelado cuando arranca a través de VMware® Workstation 16 Pro como se ve en la imagen, se debe cambiar algo en la configuración?

Si se tiene acceso a través de la interfaz web/ssh, solo es a través de la interfaz de VMware® Workstation 16 Pro

![image](https://user-images.githubusercontent.com/76731844/188596341-9c2e27fb-faf3-4db6-8bfc-97cee3bc126f.png)

**Comment by fbelavenuto** [comment]
I've added framebuffer drivers! Is possible to change the type of graphis card emulated by VMWare?

**Comment by cvc90** [comment]
The available options are scarce, it does not have a GPU passthrough option, it only has options to activate 3D graphics acceleration, screen resolution and GPU memory. Do I try any option?

I attach an image

![image](https://user-images.githubusercontent.com/76731844/188674290-14fc0ab0-3594-470e-8c43-187ba4f0bb15.png)

**Comment by fbelavenuto** [comment]
Hi, please test with the last alpha version:
https://github.com/fbelavenuto/arpl/releases/tag/v0.4-alpha7

**Comment by cvc90** [comment]
Hello, with the latest alpha version (v0.4-alpha7) it works correctly again.
