### ISSUE TITLE
Add vmxnet for DS3622xs+

### ISSUE THREAD

**Issue by cvc90** [fbelavenuto/arpl#148]
Could you add the vmxnet driver (NIC Vmware) for DS3622xs+ in addons?

**Comment by fbelavenuto** [comment]
not needed, this driver already exists in the project and will load automatically.

**Comment by cvc90** [comment]
Well, I checked the vmxnet3 nic and it doesn't load, with the e1000e nic without any problem.

Simply change the .vmdk file to vmxnet3?

**Comment by AuxXxilium** [comment]
vmxnet3 included and working oob with esxi7. confirmed it on my privat host.

**Comment by fbelavenuto** [comment]
Hi, please test with the last alpha version:
https://github.com/fbelavenuto/arpl/releases/tag/v0.4-alpha7

**Comment by cvc90** [comment]
Hello, with the latest alpha version (v0.4-alpha7) it works correctly again.
