### ISSUE TITLE
Virtualbox/VM Wrokstation Issue

### ISSUE THREAD

**Issue by dalso0418** [fbelavenuto/arpl#15]
Hello. Thank you so much for the good project.

When installing Proxmox with arpl, it is installed well without any problems, but when installing on other platforms (Virtualbox and VM Workstation), the following error occurred.

Virtualbox - Slow boot, intermittent, infinite load, pauses

VM Workstation - good to build, but formatting error output when installing DSM.

*We ask for your understanding even if there is a misunderstanding using a translator.

In addition, it would be great if the drivers for Hyper-V are supported.

**Comment by dalso0418** [comment]
![image](https://user-images.githubusercontent.com/107911055/178180577-86768af1-caec-4b0a-a23b-62a408612d1a.png)
I checked the installation in virtualbox.
Thank you.

**Comment by fbelavenuto** [comment]
Cool, closing issue
