### ISSUE TITLE
v0.4-alpha5 and v0.4-alpha6 doesn't boot

### ISSUE THREAD

**Issue by tim427** [fbelavenuto/arpl#150]
Booting directly "alpha5", the ARPL-image doesn't boot.
<img width="261" alt="image" src="https://user-images.githubusercontent.com/4570297/188848362-cf0a37f0-4a7f-4562-97cd-f61e878a1764.png">

After updating from "alpha4" to "alpha6", the ARPL-image doesn't boot anymore.
<img width="410" alt="image" src="https://user-images.githubusercontent.com/4570297/188847397-01a4392f-a71e-4aef-9b9b-38d18dfa8137.png">

Currently running on ESXi 7, upgraded the Video Controller with 128MB RAM and 3D support.

**Comment by fbelavenuto** [comment]
Sorry, due to an update failure, your image has become corrupted! Please re-record the image with the latest release:
https://github.com/fbelavenuto/arpl/releases/tag/v0.4-alpha6

**Comment by tim427** [comment]
"alpha6" indeed works again :)
