### ISSUE TITLE
v0.4-alpha6 with "update arpl" menu can not work

### ISSUE THREAD

**Issue by dominicx** [fbelavenuto/arpl#154]
in menu.sh
STATUS=`curl --insecure -s -w "%{http_code}" -L "https://github.com/fbelavenuto/arpl/releases/download/${TAG}/bzImage" -o /tmp/bzImage`

but in v0.4-alpha6 release files, The file bzImage  does not exist and the file rootfs.cpio.xz does not exist either.

**Comment by fbelavenuto** [comment]
Fixed!

**Comment by fbelavenuto** [comment]
Closing, if has another trouble please reopen
