### ISSUE TITLE
v0.4-alpha6 not booting after update arpl

### ISSUE THREAD

**Issue by l3oytoys** [fbelavenuto/arpl#155]
v0.4-alpha6 not working ,Not booting
v0.4-alpha5 working
v0.4-alpha4 working

**Comment by fbelavenuto** [comment]
Please give more information. Is it baremetal? Virtual? Which micro/virtualizer? Amount of RAM, etc.

**Comment by l3oytoys** [comment]
oh its fixed thanks for your work

**Comment by fbelavenuto** [comment]
Hi, please test with the last alpha version:
https://github.com/fbelavenuto/arpl/releases/tag/v0.4-alpha7
