### ISSUE TITLE
Lsi controller doesn't work in alpha6 and alpha7.

### ISSUE THREAD

**Issue by JerryCol** [fbelavenuto/arpl#158]
Controller LSI 9207 doesn't work in alpha6 and alpha7, but it work well in alpha5. It just doesn't make sense.
test in model:ds3617xs, 42962.

**Comment by gexadew** [comment]
me too     
LSI9271  
TEST IN MODEL  DS918 42962

**Comment by JerryCol** [comment]
> me too LSI9271 TEST IN MODEL DS918 42962

ir mode or it mode？ My LSI 9207 is it mode and the hard drives are SATA port.

**Comment by gexadew** [comment]
> 

IT MODE

**Comment by fbelavenuto** [comment]
Hi, please test with the last alpha version:
https://github.com/fbelavenuto/arpl/releases/tag/v0.4-alpha7

**Comment by JerryCol** [comment]
> Hi, please test with the last alpha version: https://github.com/fbelavenuto/arpl/releases/tag/v0.4-alpha7

It's working! Goodjob!
