### ISSUE TITLE
AQC 108 5G  network card doesn't work 

### ISSUE THREAD

**Issue by gexadew** [fbelavenuto/arpl#159]
already chang  
set netif_num=2
and  add mac2 
but it doesn't work

**Comment by jimlee2002** [comment]
+1, I meet the same problem. Same configuration as you.

**Comment by darkguy2008** [comment]
+1, I need to add the "alx" driver and don't know how to, every URL I try says it's invalid, HELP!

**Comment by fbelavenuto** [comment]
Hi, please test with the last alpha version:
https://github.com/fbelavenuto/arpl/releases/tag/v0.4-alpha7

**Comment by jimlee2002** [comment]
> Hi, please test with the last alpha version: https://github.com/fbelavenuto/arpl/releases/tag/v0.4-alpha7

For me, after the force update to this version, my aqc108 nic can be recognized again! Thanks for your amzing work!😄
