### ISSUE TITLE
2008 IT Mode HBA not recognizing Disks

### ISSUE THREAD

**Issue by kaneske** [fbelavenuto/arpl#161]
Hi,

Alpha 7 doesn’t show my Disks up on my 2 HBA in IT Mode.

Is there an Issue in this or isn’t that Model supported?

**Comment by JerryCol** [comment]
Try Alpha 5.

**Comment by fbelavenuto** [comment]
Hi, please test with the last alpha version:
https://github.com/fbelavenuto/arpl/releases/tag/v0.4-alpha7

**Comment by JerryCol** [comment]
> Hi, please test with the last alpha version: https://github.com/fbelavenuto/arpl/releases/tag/v0.4-alpha7

it's working good with lsi 9207 IT-mode.
