### ISSUE TITLE
Is this speed right?

### ISSUE THREAD

**Issue by JerryCol** [fbelavenuto/arpl#165]
Now my dsm 7.1.1-42962 working fine, but the disk read/write speed looking not good.
![未标题-1](https://user-images.githubusercontent.com/113221848/189932688-a35dc138-2a50-47d5-a54a-bf5077542a2c.jpg)
This is disk on "hyper backup" action speed, is this speed right?
There disks on motherboard-sata-ports, disks are fine.
dsm 7.1.1-42962, 0.4 alpha 7.

**Comment by fbelavenuto** [comment]
Please let us know what model your network card is.

**Comment by JerryCol** [comment]
> Please let us know what model your network card is.

This is disk to disk copy mission, not upload mission. And my motherboard is Gigabyte z390 gaming x.
Now the 0.4 alpha 11 is coming out, next week I'll find time to test it. : )

**Comment by JerryCol** [comment]
I’m install the v0.4alpha12, and the disk speed seems good, issue close.
