### ISSUE TITLE
After each DSM restart I get "CMOS Checksum bad" in bios screen

### ISSUE THREAD

**Issue by coolinx** [fbelavenuto/arpl#174]
I installed a FUJITSU LIFEBOOK S710 as NVA1622 using the arpl bootloader. (for some reason with the TCRP loader the dsm7.1 for NVA1622 could not complete the install)

Each time I restart the DSM, the bios screen presents me with a "CMOS Checksum bad" error and loads the default bios settings. I then have to press F2 to enter the bios and set the USB as first boot option again.

I know the CMOS battery is fine, and this only happens after I have started dsm via the arpl bootloader and in the DSM gui do shutdown or reboot.

Not sure how to troubleshoot this. Please let me know what logs or other info I could collect to investigate this further.

**Comment by fbelavenuto** [comment]
This problem is very strange!! I have no idea what could be happening. If I find something I'll let you know.

**Comment by fbelavenuto** [comment]
After researchs:
https://xpenology.com/forum/topic/58-bios-checksum-bad/
(posted for reference and log)

**Comment by fbelavenuto** [comment]
This problem is more complicated than it looks:

https://xpenology.com/forum/topic/1909-annoying-bios-reset-issue-is-really-bugging-me/page/6/#comment-46097

**Comment by jimmyGALLAND** [comment]
Maybe
In rp-lkm module Source 
https://github.com/fbelavenuto/redpill-lkm/blob/master/shim/bios/rtc_proxy.c

by making the function  write_rtc_num inoperate in order to build a test lkm module?

**Comment by fbelavenuto** [comment]
@jimmyGALLAND I'm studying this, but I believe the correct function to "block" is ' "rtc_write (Macro CMOS_WRITE)" which is in the kernel.
If I can understand how these TTG "shims" work I can try to apply them in this function.

**Comment by fbelavenuto** [comment]
I've tested others DSM models and the models DS918+, DS920+, DS1520+ and DVA1622 have this trouble. Another models works without corrupt the CMOS.
A temporary solution for you is to use another model, until you find a permanent solution.

**Comment by coolinx** [comment]
Thanks for looking into this. For now my workaround is to not restart the machine, and if I do I just have to set the USB again as first boot device each time...

**Comment by fbelavenuto** [comment]
I found the part of the code that causes the problem:
arch/x86/kernel/smpboot.c:1233

#ifdef MY_ABC_HERE
        spin_lock_irqsave(&rtc_lock, flags);
        SynoMemoryTrainFailReason = CMOS_READ(CONFIG_SYNO_MRC_POSTCODE_CMOS_ADDR);
        **CMOS_WRITE(0xff, CONFIG_SYNO_MRC_POSTCODE_CMOS_ADDR);**
        spin_unlock_irqrestore(&rtc_lock, flags);
        if (0xff != SynoMemoryTrainFailReason) {
                pr_err("%s: this boot have memory training fail, last reason is 0x%02x\n", _func_, SynoMemoryTrainFailReason);
        }
#endif /* MY_ABC_HERE */

I've modified my kpatch utility to patch this call to CMOS_WRITE, fixed in #186

**Comment by fbelavenuto** [comment]
Please update all (loader, addons, modules), reboot into loader mode, rebuild the loader and boot

**Comment by fbelavenuto** [comment]
Problem solved, closing
