### ISSUE TITLE
h200 it mode not working

### ISSUE THREAD

**Issue by green1052** [fbelavenuto/arpl#175]
![image](https://user-images.githubusercontent.com/34261355/190631818-edb728e8-a178-4a05-885b-145def44ec26.png)

https://kb.synology.com/ko-kr/DSM/tutorial/I_received_the_error_message_Failed_to_format_disk_DSM_installation

arpl version 0.4-alpha8

my disk is wd sas 14tb

only one

**Comment by Cryental** [comment]
Please create a Windows installation drive, boot into it, press Shift+F10, run diskpart and "clean" all disks. After that, boot to DSM and try to reinstall. It can help sometimes.

**Comment by green1052** [comment]
i tried it, but loop synology install page

**Comment by fbelavenuto** [comment]
@green1052 Thanks for the test.
@Cryental Another way to wipe partitions from a disk is to run "fdisk /dev/sdX", type "o" and press enter, type "w" and press enter, from a linux (it can be do in the loader, just be careful not to delete the loader itself).

**Comment by Cryental** [comment]
@green1052 Please check if your hdd is detected by linux (You're saying it's SAS, can be the reason), you can try it in the loader. Also let us know what DSM model/version you tried to install.

**Comment by green1052** [comment]
ds3622xs+  42962

lsblk result
sdb 8:16 12.7t 0 disk
sdb1
sdb2

@Cryental

**Comment by green1052** [comment]
umm i tried update all and working
