### ISSUE TITLE
Is there any way to adjust the  NIC order ?

### ISSUE THREAD

**Issue by picopock** [fbelavenuto/arpl#181]
Very useful tool, thanks for your all effort.

I conveniently and successfully  compiled the loader for my machine, and all function‘s work well.

My machine has two NIC，one is onboard NIC i219v and the other one is PCIE NIC intel X520.

The onboard NIC is recognized as eth1, and the other is Recognized as eth0 and eth2. 

Is there any way to adjust the order, the onboard NIC is eth0 and the other is eth1 and eth2 ?

**Comment by fbelavenuto** [comment]
I do not think so! I searched to see if it is possible but I didn't find a solution.

**Comment by picopock** [comment]
Got it, TYVM. (*￣︶￣)

**Comment by Cryental** [comment]
I don't think so :) It's randomly ordered

**Comment by fbelavenuto** [comment]
Issue explained, closing it.
