### ISSUE TITLE
能添加6.2x的版本支持吗

### ISSUE THREAD

**Issue by xu-kevin** [fbelavenuto/arpl#182]
Can you add 6.2x support？

**Comment by Cryental** [comment]
You can use Jun's mod for 6.2x, it's very stable. arpl loader doesn't provide support for 6.2x.

**Comment by JerryCol** [comment]
> Can you add 6.2x support？

why need 6.2x?

**Comment by fbelavenuto** [comment]
No plans to support 6.2, closing
