### ISSUE TITLE
tar: Option -a is not permitted in mode -x

### ISSUE THREAD

**Issue by macminoz** [fbelavenuto/arpl#189]
while using Mac OS 12.6 (Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 i386) I got this error:

Archive:  /tmp/addons.zip
  inflating: /tmp/addons/9p.addon
  inflating: /tmp/addons/acpid.addon
  inflating: /tmp/addons/dbgutils.addon
  inflating: /tmp/addons/dtbpatch.addon
  inflating: /tmp/addons/eudev.addon
  inflating: /tmp/addons/i915.addon
  inflating: /tmp/addons/lsiutil.addon
  inflating: /tmp/addons/maxdisks.addon
  inflating: /tmp/addons/misc.addon
Installing addons to files/board/arpl/p3/addons
Extracting /tmp/addons/9p.addon to files/board/arpl/p3/addons/9p
**tar: Option -a is not permitted in mode -x**

**Comment by fbelavenuto** [comment]
Are you trying to generate the image on a Mac? I've never used a Mac, but apparently the "tar" command has different options!

**Comment by fbelavenuto** [comment]
Closing. If the problem persists please reopen
