### ISSUE TITLE
Strange problem after updating to Alfa11

### ISSUE THREAD

**Issue by agisofttm** [fbelavenuto/arpl#190]
Hi @fbelavenuto 

When I installed first time DVA1622 with certified Synology 10GB network card I used arpl ver. alfa8 and everything working except BIOS problem checksum. Today I updated to Alfa11, BIOS problem was solved, but my network card doesn't work at all. Can you check it please. Here is lspci output for this card

root@arpl:/opt/arpl# Ispci -nu I grep Ethernet
01:00.0 Ethernet controller [0200]: Aquantia Corp. AQC107 NBase-1/IEEE 802.3bz Ethernet Controller LAQtion] [1d6a:07b1] (reu 02)

What I've done is going to boot loader edit menu, updated arpl to alfa 11, rebooted and going back to configure mode. Updated modules, addons and everything, after that I rebuild the loader.

Thank you in advance

**Comment by fbelavenuto** [comment]
Hi, I made mistake with this driver! Please go to loader menu, update the modules, rebuild the loader and boot.

**Comment by agisofttm** [comment]
> Hi, I made mistake with this driver! Please go to loader menu, update the modules, rebuild the loader and boot.

Thank you very much, I do it tomorrow (because computer is in my office) and I'll reply for results 👍

**Comment by agisofttm** [comment]
@fbelavenuto Thanks again - everything is working as expected 👍
