### ISSUE TITLE
Menu addon not show Cryental's Intel iGPU Drivers (8-9th Gen)

### ISSUE THREAD

**Issue by sumonchai** [fbelavenuto/arpl#197]
After custom install addon  i915-3e98.addon succeess 
how to use i915-3e98 replace i915 gen 10 in Menu Not show Cryental's Intel iGPU Drivers (8-9th Gen)

Thank you

**Comment by fbelavenuto** [comment]
This addon is only for Apollolake (DS918+), then is not show for others models

**Comment by sacredx72** [comment]
Good afternoon, maybe you have plans to implement an additional module similar to i915, only for modern N5105 Jasper Lake processors to implement the AI ​​function on DVA1622. APRL installs fine on N5105 but AI cameras and face recognition function does not work in Foto =)
