### ISSUE TITLE
custom SataPortMap and DiskIdxMap

### ISSUE THREAD

**Issue by chchia** [fbelavenuto/arpl#198]
can you add a line to let user key in their own SataPortMap and DiskIdxMap instead of user need to custom edit the config?

![image](https://user-images.githubusercontent.com/1291771/192440530-c4a2cc8c-949b-4691-8c8e-bda9632a56c8.png)

**Comment by fbelavenuto** [comment]
Uses the "cmdline menu" option from main menu:
![image](https://user-images.githubusercontent.com/11461290/192513169-1a48b910-5974-47d9-9621-215c09b01d30.png)
Choose "Add/Edit an cmdline":
![image](https://user-images.githubusercontent.com/11461290/192513354-680fb0a0-706b-442d-a427-6f7274adc1c7.png)
Type a name, ex SataPortMap:
![image](https://user-images.githubusercontent.com/11461290/192513435-2be0ecff-412f-49c6-abc9-25c44154bee2.png)
And type the value, ex 66:
![image](https://user-images.githubusercontent.com/11461290/192513489-7521cb76-0fb4-4955-b097-9ccff0d0a437.png)

**Comment by chchia** [comment]
Good! i didnt know that i can do it this way, thank you so much!
