### ISSUE TITLE
The guide interface is garbled

### ISSUE THREAD

**Issue by yunjuanyue** [fbelavenuto/arpl#205]
![微信图片_20220930115325](https://user-images.githubusercontent.com/105136714/193187018-bfddd913-9414-4254-a4d4-24d46cf14c86.jpg)

**Comment by fbelavenuto** [comment]
Please give more information about your configuration (Motherboard, CPU, external graphics card or onboard, RAM, etc)

**Comment by yunjuanyue** [comment]
Motherboard: 17x17 itx hm65 v1.5
CPU: i3-2350m CPU 2.3g dual core four thread, supporting virtualization
Video card: integrated hd3000 core video card
Memory: 2g ddr3







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fbelavenuto/arpl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月4日(星期二) 凌晨2:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fbelavenuto/arpl] The guide interface is garbled (Issue #205)





 
Please give more information about your configuration (Motherboard, CPU, external graphics card or onboard, RAM, etc)

**Comment by fbelavenuto** [comment]
the dsm model chosen was the DVA1622?

**Comment by yunjuanyue** [comment]
I have not used versions before arpl4. From arpl4 to arpl12, after installing the ds3617xs or ds920+, the boot is garbled.


The following interface is full of garbled code










&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fbelavenuto/arpl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月4日(星期二) 上午9:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fbelavenuto/arpl] The guide interface is garbled (Issue #205)





 
the dsm model chosen was the DVA1622?

**Comment by fbelavenuto** [comment]
I don't know what the problem is! Do you have more RAM to put in and test?

**Comment by redwoodkiwi** [comment]
Wondering if this got resolved?  I am having the exact same problem.  Boot screen appears just as the OP has posted.  Unable to proceed as cant make out any of the options.

Using a Foxconn NanoPC.  Celeron J1800. Embedded Intel Integrated HD graphics. 4 GB ram. 

Many thanks in advance.

**Comment by yunjuanyue** [comment]
Not resolved yet

**Comment by redwoodkiwi** [comment]
Got around the issue for now (by using the HTTP terminal).

**Comment by kygsmsc** [comment]
I am having the exact same problem,which may be related to the early CPU integrated graphics card.
Motherboard: 17x17 itx qm67
CPU: i3-3110m CPU 2.39g dual core four thread, supporting virtualization
Video card: integrated hd4000 core video card
Memory: 4g ddr3

**Comment by fbelavenuto** [comment]
Please test with this images:
https://github.com/fbelavenuto/arpl/actions/runs/3219726258
(reburn the USB flash drive)

**Comment by kygsmsc** [comment]
Thanks to fbelavenuto for using“ https://github.com/fbelavenuto/arpl/actions/runs/3219726258 ”Image, my problem has been solved.
