### ISSUE TITLE
power button does not work on proxmox vm

### ISSUE THREAD

**Issue by TingYsf** [fbelavenuto/arpl#206]
Hi, 

I like your program, it works for me on the first try. I used your alph 11 version to create a xpenology on proxmox, I chose DS3617xs-dsm7.1-42661 update 4, everything working except power button, when I use proxmox gui shutdown, it does not turn off this xpenology. 

Wondering whether this is a comment issue with this loader?

**Comment by TingYsf** [comment]
Yes and thank you. I got it working, I just have to manually restart the vm, then it works after. Thank for your reply.

**Comment by mbskykill** [comment]
> 
you are welcom

**Comment by fbelavenuto** [comment]
Annotated detail, closing

**Comment by db-one** [comment]
> Yes and thank you. I got it working, I just have to manually restart the vm, then it works after. Thank for your reply.

I have encountered the same problem. Could you please tell me if I need to reboot the whole PVE server or just the DSM virtual machine? I have rebooted DSM but it seems not to work. Thank you.
DSM system：DSM 7.1.1-42962
