### ISSUE TITLE
Some advice on ARPL

### ISSUE THREAD

**Issue by kygsmsc** [fbelavenuto/arpl#207]
I come from China, my English is very poor, the following words, I was written in Chinese, with the translation tool translated into English, I hope you can understand.

I have been using your program, very easy to use, thank you in advance!

There are a few problems in the use of hope to get your help.

1. Because of the problem of Internet, it will stop after "Build the Loader", and the problem of last error will be skipped automatically when compiling again, so that the final compiled boot is unavailable.

2. "BOOTING...." appears on the USB boot, possibly because of a problem with the graphics card driver. After that, the screen began to display as a white square, can not identify what characters are displayed, but the problem of the display, the main program is normal, I wonder whether it can be fixed?

3. I am using an old computer, "QM67+ I3-3110M integrated Intel Graphics HD4000", in Synology system SSH input ls /dev/dri, LS: cannot access '/dev/dri': No such file or directory, No graphics card, can I Add my graphics card driver in Addons under Add an Addon like adding "I95 Intel iGPU Drivers"?

**Comment by fbelavenuto** [comment]
Hello
1 - Check how much RAM you have, 4GB or more is required.

2 - It's probably a problem with your 3rd generation CPU.

3 - To be able to use the integrated intel video card it is necessary to use a 4th generation PC or higher. From the 4th generation to the 7th the existing driver works, for the 8th and 9th generation there is an Addon that replaces the correct driver.

**Comment by fbelavenuto** [comment]
Questions clarified?
