### ISSUE TITLE
How do I remove some modules.

### ISSUE THREAD

**Issue by yuzb1beiz** [fbelavenuto/arpl#208]
When I reboot, my RTL8156b USB card loads the cdc_ncm or e1000e driver, causing it to not work properly.

**Comment by yuzb1beiz** [comment]
I solved this problem by deleting the driver in <code>/mnt/p3/modules</code>. And I hope that in the future, arpl can provide the option of customizing the uninstall/install driver in the menu.

**Comment by fbelavenuto** [comment]
> I solved this problem by deleting the driver in `/mnt/p3/modules`. And I hope that in the future, arpl can provide the option of customizing the uninstall/install driver in the menu.

Good to know! I'll add a menu option to customize the drivers/modules

**Comment by fbelavenuto** [comment]
Added in this pre-release:
https://github.com/fbelavenuto/arpl/actions/runs/3184033056

Please test it!
