### ISSUE TITLE
real machine , Loader disk not found !

### ISSUE THREAD

**Issue by undefine-man** [fbelavenuto/arpl#211]
All perfect above ESXi 7 virtual machine.
I try to install on my spare real machine ( tried to set SATA to ACHI and IDE ) , uefi mode will come up grub interface. So i use legacy boot mode ,i can enter to the installiation linux ,but show "Loader disk not found". 

![1001_1](https://user-images.githubusercontent.com/24623544/193412781-d1b74fd4-6c8c-4b9e-a5da-847d015a7229.jpg)

**Comment by DarkDreamDark** [comment]
my real machine have a same problem when i install V7.1 OS and reboot

**Comment by fbelavenuto** [comment]
What is the ARPL version?

**Comment by DarkDreamDark** [comment]
> What is the ARPL version?

what is ARPL means?
i use v0.4-alpha11...v0.4-alpha12, and my cpu is n3150 and network card is rtl8111

**Comment by fbelavenuto** [comment]
ARPL is the loader itself

Type the commands in this screen:
![image](https://user-images.githubusercontent.com/11461290/193838931-b0c80f86-8954-451e-b256-9b2ad3d8cf0e.png)

**Comment by fbelavenuto** [comment]
And I forgot the commands! Sorry.

Type "fdisk -l", "blkid" and "lsblk", one command by line, and post the result here

**Comment by DarkDreamDark** [comment]
> And I forgot the commands! Sorry.
> 
> Type "fdisk -l", "blkid" and "lsblk", one command by line, and post the result here
![IMG_20221005_100410_副本](https://user-images.githubusercontent.com/114749773/193965612-bc1fd519-1c86-4270-b326-9eae59e8241f.jpg)
![IMG_20221005_101424_副本](https://user-images.githubusercontent.com/114749773/193965722-050efe2a-6d99-47e1-865c-e8e2ac1c72a1.jpg)
![IMG_20221005_101506_副本](https://user-images.githubusercontent.com/114749773/193965789-84beb13f-d7af-455e-8278-5e8420c86d60.jpg)

it have another state,when i frst run this app and reboot, computer, it have appear loader disk not found tip
__

**Comment by DarkDreamDark** [comment]
> And I forgot the commands! Sorry.
> 
> Type "fdisk -l", "blkid" and "lsblk", one command by line, and post the result here

i have a new question, how to use SSH to connect this app? user、 password and port i not know

**Comment by fbelavenuto** [comment]
Something happens with 3th partition, it should have the label on the partition.
![image](https://user-images.githubusercontent.com/11461290/194061519-6cd7e5a8-20e6-4374-aa03-4e7aa797543b.png)
Please test with another software to burn the image or another flash disk.

| i have a new question, how to use SSH to connect this app? user、 password and port i not know
ssh root@_[ip]_
Password: Redp1lL-1s-4weSomE
Port 22

**Comment by DarkDreamDark** [comment]
> Something happens with 3th partition, it should have the label on the partition. ![image](https://user-images.githubusercontent.com/11461290/194061519-6cd7e5a8-20e6-4374-aa03-4e7aa797543b.png) Please test with another software to burn the image or another flash disk.
> 
> | i have a new question, how to use SSH to connect this app? user、 password and port i not know ssh root@_[ip]_ Password: Redp1lL-1s-4weSomE Port 22

think for your help, i use my nvme disk reboot and loader system succeed. thank you!!!
