### ISSUE TITLE
Fail boot with second USB drive attached

### ISSUE THREAD

**Issue by mahmoudhamadeh** [fbelavenuto/arpl#214]
If I'm connecting another USB drive to use for hybrid backup, on the next reboot the boot will fail. It will boot to the GRUB prompt with the following text "Minimal BASH-like line editing is supported. For the first word, TAB lists possible command completions. Anywhere else TAB lists possible device or file completions.". I guess the USB is messing the drive numbering 0,1,2, etc.. therefore it failed. When USB removed, it boots correctly.

**Comment by fbelavenuto** [comment]
Thanks for the report

**Comment by nomadism19** [comment]
This happens every time with mine too. I have to manually boot without external drive, then plug it in after boot. Cannot run reboot command remotely as it will just end up in GRUB terminal without the usual GRUB boot menu

**Comment by fbelavenuto** [comment]
Please guys, type "fdisk -l", "blkid" and "lsblk", one command by line, and post the result here

**Comment by mahmoudhamadeh** [comment]
Where should I use those command? In GRUB prompt it is not recognized. Shall I do SSH while the external USB attached? I think this will require a live disk boot, correct?

**Comment by fbelavenuto** [comment]
Ops, my bad, boot with one flash disk to ARPL, plug another flash disk and type commands.

**Comment by mahmoudhamadeh** [comment]
here you go, thank you!

![WIN_20221004_09_53_35_Pro](https://user-images.githubusercontent.com/26927138/193841505-43059ac5-07e1-4495-9744-b9e0de508658.jpg)

**Comment by mahmoudhamadeh** [comment]
No, the BIOS is set correctly to boot from ARPL USB. Actually, this is just a blank USB with no boot in it. I think the issue here is any external USB will hijack position “hd0” and push other USBs to the next slot. See here with/without USB how the drives are identified. The boot menu will always point to root = hd0 which will be empty in this case and therefore brough the GRUB prompt.

![WIN_20221004_21_35_20_Pro](https://user-images.githubusercontent.com/26927138/193969045-52ba1854-80b2-43dc-a6ae-930369727d60.jpg)
![Screenshot 2022-10-04 223224](https://user-images.githubusercontent.com/26927138/193969063-a234a573-c6e0-48c7-be0f-6f4545455cf4.png)

**Comment by fbelavenuto** [comment]
My bad, now I found the trouble.

**Comment by fbelavenuto** [comment]
Please test with this new release:
https://github.com/fbelavenuto/arpl/releases/tag/v0.5-alpha1

**Comment by mahmoudhamadeh** [comment]
Thanks! is there any easy way to upgrade to the latest version without need to reset all from the beginning?

**Comment by mahmoudhamadeh** [comment]
sure, I will try that later. But for now I edited the "grub.cfg" file manually and added (search --set=root --label "ARPL1") now it can boot correctly while the other USB is attached.
