### ISSUE TITLE
DVA1622 Disk Full form files .Pma [On VMWARE ]

### ISSUE THREAD

**Issue by sumonchai** [fbelavenuto/arpl#215]
Local_Display Created  files .pma alway.
Check and remove
1. sudo -i
2. cd /volume1
3. du -h -d1

Remove all .pma files
cd /volume1/@appstore/SurveillanceStation/local_display/.config/chromium-local-display/BrowserMetrics
find . -name "*.pma" -delete

Try Disable  Local Display but create alway. How to fix

Create Schedule as root
code:
find /volume1/@appstore/SurveillanceStation/local_display/.config/chromium-local-display/BrowserMetrics/ -name "*.pma" -delete

**Comment by J0hnMatrix** [comment]
Same behavior here, have to create a scheduled task to remove the .pma files

**Comment by incmve** [comment]
![13bae731-1010-42d5-bfec-f0bc39a484ac](https://user-images.githubusercontent.com/3177116/199597807-6ff431a8-ace0-4970-a0b9-5220bfcd5a8e.jpg)
FYI in surveillance station disable the local display in app center seems to stop the pma files for me.
The dir grew 600MB per 15 minutes before stopping it, now the size stays the same.
