### ISSUE TITLE
Making a bootloader with SSL commands

### ISSUE THREAD

**Issue by Ostap6** [fbelavenuto/arpl#217]
Fabio Belavenuto - Your bootloader design is great.
One question - is it possible to make a bootloader using your projects not from menu, but using SSH commands?
And if so, how?
I could not access the image originally written to the flash from which the boot was made:

Ostap60-:~ ostap60$ ssh root@192.168.0.xxx
Ostap60-:~ ostap60$ ssh ostap60@192.168.0.xxx
Ostap60-:~ ostap60$ ssh aprl@192.168.0.xxx

Password:
Redp1IL-1s-4weSomE
not suitable

Thanks in advance for your reply!

**Comment by fbelavenuto** [comment]
Hi, thanks.

The correct is type "ssh root@x.x.x.x" and type the password "Redp1lL-1s-4weSomE". Tested now:
![image](https://user-images.githubusercontent.com/11461290/193882856-d30a84c7-2adc-46b2-bde0-4b296d793d35.png)

**Comment by fbelavenuto** [comment]
Question clarified?
