### ISSUE TITLE
WOL does not work on DS918+ with valid pair

### ISSUE THREAD

**Issue by Ostap6** [fbelavenuto/arpl#222]
Good time !!
I tested:
arpl-0.4-alpha12 
& 
arpl-0.5-alpha1 

The situation is the same:
WOL does not work on DS918+ with valid pair. However, with a random serial number and a default mac address, the WOL works great.  

But on the DS3622xs, the WOL functions perfectly including with a valid pair.

The v0.5-alpha1 bootloader header says: 
"Welcome to Automated Redpill Loader v0.4-alpha6"
![photo_2022-10-05_19-32-48](https://user-images.githubusercontent.com/62217636/194114398-0013977f-49c1-40f4-a713-d7f109966a6c.jpg)

**Comment by fbelavenuto** [comment]
Closing
