### ISSUE TITLE
DVA1622 NIC ixgbe not work

### ISSUE THREAD

**Issue by coolfree** [fbelavenuto/arpl#223]
v0.4-alpha12 and v0.5-alpha1
MB: J4125NHU
build DVA1622 loader

NIC ixgbe not work

information:

0000:02:00.0 Class [0200]: Device [10ec:8168] (rev 15)
	DeviceName: Onboard - RTK Ethernet
	Subsystem: Device [1565:2312]
	Kernel driver in use: r8168
0000:03:00.0 Class [0200]: Device [8086:10fb] (rev 01)
	Subsystem: Device [8086:0006]
	Kernel driver in use: ixgbe
0001:01:00.0 Class [0106]: Device [1b4b:9235] (rev 11)

root@Home_NVR:~# dmesg -Tw | grep -e ixgbe
[Thu Oct  6 12:36:52 2022] ixgbe 0000:03:00.0: Multiqueue Enabled: Rx Queue count = 4, Tx Queue count = 4
[Thu Oct  6 12:36:52 2022] ixgbe 0000:03:00.0: 4.000 Gb/s available PCIe bandwidth, limited by 5 GT/s x1 link at 0000:00:14.0 (capable of 63.008 Gb/s with 8 GT/s x8 link)
[Thu Oct  6 12:36:52 2022] ixgbe 0000:03:00.0 eth0: MAC: 2, PHY: 17, SFP+: 5, PBA No: G30771-004
[Thu Oct  6 12:36:52 2022] ixgbe 0000:03:00.0: 90:e2:ba:88:ba:72
[Thu Oct  6 12:36:52 2022] ixgbe 0000:03:00.0 eth0: Enabled Features: RxQ: 4 TxQ: 4 FdirHash
[Thu Oct  6 12:36:52 2022] ixgbe 0000:03:00.0 eth0: Intel(R) 10 Gigabit Network Connection
[Thu Oct  6 12:37:57 2022] ixgbe 0000:03:00.0 eth5: renamed from eth0
[Thu Oct  6 12:37:57 2022] ixgbe 0000:03:00.0 eth1: renamed from eth5

coolfree@Home_NVR:/$ ethtool  eth1
Settings for eth1:
	Supported ports: [ FIBRE ]
	Supported link modes:   10000baseT/Full 
	Supported pause frame use: Symmetric
	Supports auto-negotiation: No
	Supported FEC modes: Not reported
	Advertised link modes:  10000baseT/Full 
	Advertised pause frame use: Symmetric
	Advertised auto-negotiation: No
	Advertised FEC modes: Not reported
	Speed: Unknown!
	Duplex: Unknown! (255)
	Port: FIBRE
	PHYAD: 0
	Transceiver: internal
	Auto-negotiation: off
Cannot get wake-on-lan settings: Operation not permitted
	Current message level: 0x00000007 (7)
			       drv probe link
	Link detected: no
 pls help

**Comment by fbelavenuto** [comment]
Please test with this image:
https://github.com/fbelavenuto/arpl/actions/runs/3219726258
(reburn the USB flash drive)

**Comment by coolfree** [comment]
thanks bro

**Comment by fbelavenuto** [comment]
Working?

**Comment by coolfree** [comment]
i can't download that image.
but i find why not work

modinfo ixgbe_not_ok.ko
filename:       ixgbe_not_ok.ko
version:        5.13.4
depends:        dca,vxlan
vermagic:       4.4.180+ SMP mod_unload 

modinfo ixgbe_ok.ko
filename:       ixgbe_ok.ko
version:        5.16.5
srcversion:     F5781D1F10DD159E858ADA7
depends:        vxlan
vermagic:       4.4.180+ SMP mod_unload 

anybody change that drivers
i think dca.ko not export
