### ISSUE TITLE
v0.5alpha1 upnp service always busy.

### ISSUE THREAD

**Issue by JerryCol** [fbelavenuto/arpl#225]
I'm using ARPL v0.5alpha1 and the Model is ds3617 with DSM 42962.
When I wanna open the Upnp service setting, this page always "busy".
I think it's a bug.
Now I wanna return to ARPL v0.4alpha12 or alpha11.

**Comment by storm-99** [comment]
https://github.com/fbelavenuto/arpl/releases/download/v0.4-alpha12/arpl-0.4-alpha12.vmdk.zip
or
https://github.com/fbelavenuto/arpl/releases/download/v0.4-alpha12/arpl-0.4-alpha12.img.zip

**Comment by fbelavenuto** [comment]
Works?
