### ISSUE TITLE
Restore USB devices support

### ISSUE THREAD

**Issue by J0hnMatrix** [fbelavenuto/arpl#228]
Hello,
Do you think is it possible to restore the USB device support that Synology drops from DSM7?
Indeed, I plan to use a RFXCom and an USB DVB tuner with Docker.

I have copied the files ch341.ko and cp210x.ko (designed for the DS3622xs) and load them with modprobe command and from the dmesg, the RFXCom seems detected but it is not linked to a ttyUSB* or a ttyACME* device.

Modules:
[modules.zip](https://github.com/fbelavenuto/arpl/files/9733994/modules.zip)

Commands:
```
modprobe usbserial
modprobe ftdi_sio
modprobe cdc-acm
```

![image](https://user-images.githubusercontent.com/17948440/194556722-85897163-51dd-4006-85cd-df3545309534.png)

![image](https://user-images.githubusercontent.com/17948440/194556613-c165ec27-8f5b-4e86-9b51-92055171eca4.png)

Many thanks in advance!

**Comment by fbelavenuto** [comment]
I've replaced the modules needed for this, but apparently more is needed.
I won't promise as it may be technically impossible.

**Comment by J0hnMatrix** [comment]
No problems, if you need testing or something else, I can help.
I don't know if USB devices can interfere with the Redpill loader as there are some usb shiming but on original Synology with DSM7, these modules seems to work.

**Comment by cvc90** [comment]
Could you indicate where you got the ch341.ko and cp210x.ko files from? I have others apart from those two files which are pl2303.ko and ti_usb_3410_5052.ko all taken from [http://www.jadahl.com/](http://www.jadahl.com/iperf-arp-scan /DSM_7.0/broadwellnk/), and currently I'm getting disconnect errors every two or three days since I turn on the machine and forcing me to reboot it to detect them again correctly.

My devices are a RFLink and a Sonoff Zigbee

**Comment by J0hnMatrix** [comment]
I got the modules from the same location as you but by using Wayback Machine as Jadahl website is not working anymore.
https://web.archive.org/web/20220616040640/http://www.jadahl.com/iperf-arp-scan/DSM_7.0/

Sad to know that the modules are not working properly, maybe will be better to not continue the investigation?

**Comment by cvc90** [comment]
I have been investigating possible solutions for several days and it is possible that I have two solutions to recover the drivers of the USB devices.

The first option would be to install the ["SynoKernel USB Serial drivers"](https://synocommunity.com/package/synokernel-usbserial) package from the [Synocommunity](https://synocommunity.com/) repo, installing it would be enough for the devices to detect and work correctly. It is available for almost all architectures and versions DSM 6.x and DSM 7.x.

The second option would be from the github [dsm7-usb-serial-drivers](https://github.com/robertklep/dsm7-usb-serial-drivers), these modules seem to be more up-to-date, but they are installed manually by following the steps indicated. These modules are available for most architectures and only for DSM 7.x versions.

Could you try any of these solutions to see if they work for you?

**Comment by J0hnMatrix** [comment]
Very nice finding!
The Synokernel USB Serial drivers seems to works accordingly, the RFXCom dongle is now correctly attached to the port ttyUSB0:

<img width="748" alt="image" src="https://user-images.githubusercontent.com/17948440/195973433-75c13846-e7e2-4635-9f8a-b21dc544879f.png">

**Comment by cvc90** [comment]
I am glad to know that the solution found worked for you.
