### ISSUE TITLE
biostar J4125NHU DS920+ cannot be searched after a while

### ISSUE THREAD

**Issue by wu0lei** [fbelavenuto/arpl#231]
When the biostar J4125NHU makes the DS920+ boot, everything goes well, and the installation of the DSM42962 is all normal, but after the restart after the installation is completed, it can only be pinged for a period of time when the network port light is on, and Synology Assistant can also receive it, and the status is "Ready" , after a while, you can only ping, and Synology Assistant cannot search for the machine.

**Comment by wu0lei** [comment]
Addition: After canceling the add-in "10th gen i915 driver", the installation was successful, and there was no situation that it could not be found.

**Comment by fbelavenuto** [comment]
Thanks for the report.
