### ISSUE TITLE
a pattern striped screen

### ISSUE THREAD

**Issue by ljr78** [fbelavenuto/arpl#233]
When the J900 starts, a pattern striped screen appears, and you cannot see the text on the screen. Can I start in character mode?

**Comment by AuxXxilium** [comment]
You can use web console with IP:7681 so you don't need local output. I saw the same issue on one of mine but i started web console and everything is working fine.

By the way: The issue only apears if you start BIOS/CSM with UEFI everything is working fine.

**Comment by fbelavenuto** [comment]
Please test with this image:
https://github.com/fbelavenuto/arpl/actions/runs/3219726258
(reburn the USB flash drive)

**Comment by kygsmsc** [comment]
Thanks to fbelavenuto for using“ https://github.com/fbelavenuto/arpl/actions/runs/3219726258 ”Image, my problem has been solved.
