### ISSUE TITLE
The latest boot cannot wake on the network (WOL)

### ISSUE THREAD

**Issue by yunjuanyue** [fbelavenuto/arpl#241]
Boot DSM_ DS3617xs with arpl-0.4-alpha4.img, the network wake-up function is normal, but the network wake-up function does not work when you boot with the version after arpl-0.4-alpha4.img.

**Comment by fbelavenuto** [comment]
Did you mean v0.5-alpha1?
Go to the "modules" menu and select "Select all modules", rebuild the loader and test.

**Comment by yunjuanyue** [comment]
> Did you mean v0.5-alpha1? Go to the "modules" menu and select "Select all modules", rebuild the loader and test.

I have tested several versions of the ds3617 and ds920+, and only arpl-0.4-alpha4.img is effective for Wake on LAN.

**Comment by MartinKuhl** [comment]
WOL is working for me with ARPL on ds3622xs+. I have problems with the normal TCRP. Same NAS same Synology model but there WOL is not working for me.

**Comment by fbelavenuto** [comment]
WoL only works if network card has the MAC replaced. Test again, boot the DSM, turn off the machine and without removing the power do the test with WoL.
The network card has its MAC burned in the BIOS, when turning on a PC that is completely turned off, the BIOS will set the MAC to the factory default.
A definitive solution is to find some tool that can change this MAC from the factory, which may or may not be possible depending on the manufacturer.

**Comment by Brian099** [comment]
> WoL only works if network card has the MAC replaced. Test again, boot the DSM, turn off the machine and without removing the power do the test with WoL. The network card has its MAC burned in the BIOS, when turning on a PC that is completely turned off, the BIOS will set the MAC to the factory default. A definitive solution is to find some tool that can change this MAC from the factory, which may or may not be possible depending on the manufacturer.

so it's why the IP on the screen does not match the IP of DSM, IP on the screen is ordered to the loader, after DSM started, system will replace the MAC, then get another IP？

**Comment by chestor37** [comment]
> WoL only works if network card has the MAC replaced. Test again, boot the DSM, turn off the machine and without removing the power do the test with WoL. The network card has its MAC burned in the BIOS, when turning on a PC that is completely turned off, the BIOS will set the MAC to the factory default. A definitive solution is to find some tool that can change this MAC from the factory, which may or may not be possible depending on the manufacturer.

I created a reservation on my router for a real mac motherboard and only use it for WoL. And for web access, I use what dsm received via dhcp, because I have a real mac and sn from a real nas.

**Comment by yunjuanyue** [comment]
For the same DSM version (e.g. DSM_DS3617xs_426611), it is available to use arpl-0.4-alpha4.img as the boot LAN wake-up, but it is not available to use other versions of arpl as the boot LAN wake-up.
Can your LAN wake up normally？

**Comment by chestor37** [comment]
> For the same DSM version (e.g. DSM_DS3617xs_426611), it is available to use arpl-0.4-alpha4.img as the boot LAN wake-up, but it is not available to use other versions of arpl as the boot LAN wake-up. Can your LAN wake up normally？

I am using DS920+ latest version and arpl-v1.0-beta 2. The device wakes up normally if you use the mac address of the motherboard.

**Comment by fbelavenuto** [comment]
Closing. If the problem persists please reopen
