### ISSUE TITLE
disks misssing after migrate to arpl from tcrp

### ISSUE THREAD

**Issue by PikuZheng** [fbelavenuto/arpl#245]
hi, arpl greatly simplifies the deployment process, which is nice.

I use 3 virtual disks in tcrp and they work fine in esxi. After switching to arpl 2 were lost, even though it was recognized in the config interface.

Setting "set maxdisks manualy" to 3 or 4 is useless. It's DS3617xs so diskmap does not exist.

So, what else can I do?

![image](https://user-images.githubusercontent.com/12579522/195471006-3c925d10-6a26-479b-b47d-79097370e964.png)
![image](https://user-images.githubusercontent.com/12579522/195471380-29385c29-5265-404c-875b-834722afec37.png)

**Comment by storm-99** [comment]
You have 2 SATA controller? loader in SATA controller 1 and 3 data disks in SATA controller 2? If so, try add the following the cmdline option
SataPortMap: "18"
DiskIdxMap:  "1000"

**Comment by PikuZheng** [comment]
This works! thank you very much.

By the way, I think the necessary guidelines should exist if changes are required to migrate from tcrp to arpl
