### ISSUE TITLE
KVM suffers improper shut down in PVE

### ISSUE THREAD

**Issue by stevenwdhu** [fbelavenuto/arpl#251]
host platform: NUC8i5BEH
host manager: PVE 7.2-3
loader: v0.5-alpha1.
DSM build: 7.1.1-42962
model: 918+

Following the guide, I can successfully build the loader and boot the DSM. It runs normally until I upload big files. I tried to upload files via NFS and web interface, but it constantly shut down after nearly 10 minutes uploading tasks.

**Comment by fbelavenuto** [comment]
I believe it is something with the driver. Researching I found that this motherboard has an I219-V built in and the correct driver is the e1000e.
Please is it possible to SSH into your DSM and type: "lspci -nnv" and post the result here?
