### ISSUE TITLE
As for the boot boot problem, does the program not support UEFI boot?

### ISSUE THREAD

**Issue by cocoakeer** [fbelavenuto/arpl#252]
Hello, developer.
Does this program not support UEFI startup?
请问此程序是不是不支持UEFI方式启动？

**Comment by coolfree** [comment]
支持的

**Comment by cocoakeer** [comment]
> 支持的

很奇怪，我在用uefi启动时，屏幕黑屏无任何字符输出，必须使用传统启动方式才能有反应输出。
It's strange that when I use uefi to start, the screen is black and there is no character output. You must use the traditional startup mode to have response output.

**Comment by coolfree** [comment]
注意看一下,uefi启动的时候,是不是选择了硬盘启动

**Comment by cocoakeer** [comment]
> 注意看一下,uefi启动的时候,是不是选择了硬盘启动

我可以确定没从硬盘启动，我曾尝试将所有硬盘拆掉，直插入USB启动。

**Comment by cocoakeer** [comment]
> bios 开启csm支持,试试

是的，我已经开启了CSM，不然主板无法设置传统方式启动，打开之后是可以选择UEFI或者传统模式启动，现在目前我是把UEFI给关掉啦，不然无法启动屏幕无任何输出提示。

**Comment by fbelavenuto** [comment]
Yes, UEFI is supported

**Comment by cocoakeer** [comment]
> Yes, UEFI is supported

It's strange. After I started with uefi, there was no response and the screen was black. No output.
太奇怪啦，我用uefi启动后无反应，黑屏。无任何输出。

**Comment by cocoakeer** [comment]
> Please give more details, Motherboard Model, CPU, etc.

I currently use the Yingtai J4125 integrated motherboard, which supports UEFI and traditional mode startup.
我当前用的是映泰J4125集成主板，主板支持UEFI和传统模式启动。

**Comment by coolfree** [comment]
我也是这块主板

**Comment by cocoakeer** [comment]
> 我也是这块主板

请教下您是怎么设置的？直接UEFI模式启动吗？我是用rufus3.20制作的启动U盘。

**Comment by coolfree** [comment]
bios 版本是多少?先恢复默认设置,然后开始逐步设置

**Comment by coolfree** [comment]
bios 版本号:J41CW929.BSS

**Comment by cocoakeer** [comment]
> bios 版本号:J41CW929.BSS

我刚重启了下，你说的这个版本应该是官网最新的bios版本，我也是最新的UEFI2.7、PI1.6。
<img width="840" alt="image" src="https://user-images.githubusercontent.com/112269603/196202283-0f91715c-dd77-4439-bd67-3e0a56fdfd4e.png">

**Comment by cocoakeer** [comment]
> 我也是这块主板

我也曾经尝试再esxi虚拟机上测试用UEFI引导，也是无法启动。所以提出此疑问是否支持UEFI。
<img width="291" alt="image" src="https://user-images.githubusercontent.com/112269603/196205773-c7cc0823-2731-4b76-b58e-ff3c3a6109da.png">

**Comment by cocoakeer** [comment]
> 我也是这块主板

这位朋友您好，我还想问下，在此集成主板下您是否解决了硬解问题？我目前还没有搞定此问题，核显无法调用。

**Comment by coolfree** [comment]
我是安装dva1622,当作 nvr 用
你安装什么?

**Comment by coolfree** [comment]
可以试试安装 dva1622

**Comment by fbelavenuto** [comment]
Guys, try burn the image with another tool. I recommend the Raspberry Pi Imager which works great for other image types.
Here at home I have successfully tested UEFI with PVE, WMWare Workstation Player and VMWare ESXi 6.7

**Comment by fbelavenuto** [comment]
Closing, if the problem persists please reopen.
