### ISSUE TITLE
An error is reported when the ten minute countdown prompts "There is a problem".

### ISSUE THREAD

**Issue by cocoakeer** [fbelavenuto/arpl#254]
Hello, developer.
I am currently using ESXI virtual machine for installation. After ten minutes of countdown, I am prompted with the error message "There is a problem". Please click the button below to try to reconnect to your Synology NAS. "After repeated attempts, this has always been the case.
我当前用ESXI虚拟机安装，在出现倒计时十分钟结束后提示“出现问题“的报错，请单击下方按钮以尝试重新连接到您的 Synology NAS.”，经过反复尝试，一直如此。
<img width="803" alt="image" src="https://user-images.githubusercontent.com/112269603/196246315-aa0b4b13-0d34-48b3-92d2-2813aeb24644.png">
<img width="502" alt="image" src="https://user-images.githubusercontent.com/112269603/196246358-d3f444a2-eeaa-441f-ab32-bea62063f78a.png">

**Comment by coolfree** [comment]
用 synology assistant 查看,应该提示dsm没有安装

**Comment by cocoakeer** [comment]
> 用 synology assistant 查看,应该提示dsm没有安装

我用synology assistant 提示是转移的状态，这说明已经安装了吧？不知道为什么会这样，第一次碰到此问题，之前也尝试过虚拟机没遇到过。

**Comment by cocoakeer** [comment]
Please help us to analyze the possible problems@ developer
thank!

**Comment by cocoakeer** [comment]
<img width="934" alt="image" src="https://user-images.githubusercontent.com/112269603/196472235-2dd2617e-6d7b-4028-b794-1d3be41b5c99.png">

**Comment by fbelavenuto** [comment]
Closing, if the problem persists please reopen.
