### ISSUE TITLE
About the problem that "connection failed" appears on the [UPS] page in the [Control Panel]

### ISSUE THREAD

**Issue by itv3** [fbelavenuto/arpl#258]
Recently, in the process of setting up UPS, I accidentally found that in the [Control Panel]->[Hardware and Power]->[UPS] page, when the settings are saved and saved, the error "Connection failed. Please check your network settings" will appear. Prompt, confirm that the network connection is completely normal, although this prompt appears, but there is no problem with the function. Then I used tinycore-redpill to compile a new installation test, and confirmed that the problem only occurs in the compilation of ARPL. There is no problem with inycore-redpill compilation, please take a look

It is very simple to reproduce the problem. In the [Control Panel] -> [Hardware and Power] -> [UPS] page, enable ups, select "SNMP UPS", then enter any parameters, click Save to see the error message, click Cancellation can also see the error message
![1](https://user-images.githubusercontent.com/102932260/196712006-ef7dfb2a-675c-456c-b169-9a4dc93106fb.png)
![2](https://user-images.githubusercontent.com/102932260/196712018-5f44abbf-2e82-4645-8739-26936a29a72e.png)

**Comment by fbelavenuto** [comment]
Thanks for the report

**Comment by itv3** [comment]
你是用的ARPL还是tinycore-redpill?我安装的7.1.1-42962
