### ISSUE TITLE
can't connect

### ISSUE THREAD

**Issue by sonsungwon** [fbelavenuto/arpl#26]
hello

arpl version arpl-0.1-alpha8.img

boot the loader successfully

![image](https://user-images.githubusercontent.com/6913952/178301530-dfa54b3c-fa9e-4b2a-abc8-cc1575512e3e.png)

![image](https://user-images.githubusercontent.com/6913952/178301776-256bbfdb-b050-42eb-8b1f-6139cc1143e8.png)

http://1~~.~~~.~~~.~80:5000
http://1~~.~~~.~~~.~80:5001

but 
I can't access the installation page

**Comment by sonsungwon** [comment]
network : Realtek Dragon RTL8125BG
network you added


![image](https://user-images.githubusercontent.com/6913952/178738222-636e4b2b-5360-4762-b176-c1d7479c07e2.png)

**Comment by fbelavenuto** [comment]
Please test with 0.3-alpha1 release

**Comment by fbelavenuto** [comment]
Some success?

**Comment by fbelavenuto** [comment]
Duplicate, waiting answer in another issue
