### ISSUE TITLE
NIC not recognize on a hyper-v virutal machine

### ISSUE THREAD

**Issue by jhezjkp** [fbelavenuto/arpl#262]
![image](https://user-images.githubusercontent.com/769374/197388881-15113bf9-80eb-412b-b408-16312c3d2208.png)

host os: windows server 2022
host nic: Realtk Gaming 2.5GbE Family Controller
arpl version: v0.5-alpha1

**Comment by fbelavenuto** [comment]
DSM do not have support to Hyper-V. The kernel is compiled without this support. I've removed the Hyper-V support from loader too.
Without the source of DSM kernel parts, is impossible to add support to Hyper-V.
