### ISSUE TITLE
Need help with bootscript

### ISSUE THREAD

**Issue by AuxXxilium** [fbelavenuto/arpl#264]
Hello Fabio, i need your help. I try to make some addons, like static IP and some others. But they don't start at boot. I tried nearly everything. If i start a script over ssh it is working. Can you give me a short answer, what i have to do to make it automatic executing at boot. 

thanks for your work. it's the best loader script atm.

**Comment by fbelavenuto** [comment]
Please use existing addons as a base:
https://github.com/fbelavenuto/arpl-addons

**Comment by AuxXxilium** [comment]
Thank you for help. I found a way to get it working.
