### ISSUE TITLE
How to let the PassThrough SATA controler HDDs to hibernate?

### ISSUE THREAD

**Issue by EricksonLu** [fbelavenuto/arpl#265]
The SATA ASMedia Technology is the passthrough controller from PVE. And it connected two HDDs.
I already install a Synology without SataPortMap and DiskIdxMap parameters. And I created a storage pool with the two HDDs at the passthrough SATA controller. 
![1666595741855](https://user-images.githubusercontent.com/11749499/197468764-35f82e81-b09b-4a7f-a8a7-8032cf5c0b34.png)

I set HDD hibernation to 10mins. But the HDDs never hibernate one time. So I checked the Synology page to check the hibernation problems about turning off some services and options at Synology. The Synology system is just created, and I didn't change options. So I try to find the disk problem. When I pass through the HDDs I can't find them at PVE. So I think that's meaning the passthrough has worked. I only can find them at ARPL core and Synology.

So I check the HDDs status at Synology, and I found I can't find them at **Storage Overview**->**Device information**
![1666596261639](https://user-images.githubusercontent.com/11749499/197470227-f9f55dbd-a625-4efc-94f6-3e00ac7cefae.png)

I thought that was the problem HDDs can't hibernate. So I tried to set SataPortMap=0622 and DiskIdxMap=0A0300.
When I build the Synology at ARPL and reboot it. The Synology can't boot up just stuck at The terminal at the booting stage.

**This is the port map:**
![ffafbc35e2f066e48576528542c288b](https://user-images.githubusercontent.com/11749499/197465877-061b4651-cb42-4a71-a4a5-7ad119411363.png)

![1666595436238](https://user-images.githubusercontent.com/11749499/197467940-3c22278e-388b-4089-a549-cf1cbdc021f4.png)
![1666609936468](https://user-images.githubusercontent.com/11749499/197513298-2c3ed4b1-2de8-43e4-a5a8-ecb978d999c6.png)

 If I deleted the SataPortMap=0622 and DiskIdxMap=0A0300  I set. The Synology can boot up.
![1666595588854](https://user-images.githubusercontent.com/11749499/197468357-f1481ba7-e7e9-40a1-ae2e-b5c180921bcc.png)

I don't know where am I wrong. Are the SataPortMap and DiskIdxMap I mess up or what?
Please help me for a while , thanks a lot !!!@fbelavenuto

**Comment by fbelavenuto** [comment]
Try only this:
DiskIdxMap = 10020800

**Comment by fabio-ffclrp** [comment]
> <img alt="ARPL" width="327" src="https://user-images.githubusercontent.com/61157268/198091549-a39aaef8-c737-40a8-bbb3-a2ae9d09fae3.png">

For this configuration, uses:

SataPortMap: 66

**Comment by sgelineau17** [comment]
> > <img alt="ARPL" width="327" src="https://user-images.githubusercontent.com/61157268/198091549-a39aaef8-c737-40a8-bbb3-a2ae9d09fae3.png">
> 
> For this configuration, uses:
> 
> SataPortMap: 66

Thanks you, that working !
