### ISSUE TITLE
always missed two discs

### ISSUE THREAD

**Issue by Jamcao** [fbelavenuto/arpl#267]
Dera Fabio,

Thanks for you shared super arpl.
I have tried different model, like: 918+, DSM 1621+, DSM 3622+, but alwasy lost two discs as attached.

my system: esxi 7.0.3
![cd5960d9d3ab89043861ae4ff10b796](https://user-images.githubusercontent.com/110510944/197924656-3764042a-7a57-4298-ad45-a4fb02dd666b.png)

my prot：
![1da0998a6fe36e9e6524b4480cd3909](https://user-images.githubusercontent.com/110510944/197924629-138da31e-d3ea-4dc0-80bc-6b452eb83e51.png)

But always can't load DSM as:
![92fa0f9d4534c1475437b7f9f5276a7](https://user-images.githubusercontent.com/110510944/197924720-3bffd009-3c4d-441d-9c80-010a779b5a23.png)

checked the discs as:
![afe64be94d893fd6c8a93e049ffa542](https://user-images.githubusercontent.com/110510944/197924765-3b74c134-9c06-4021-adfc-3e6f299e40a9.jpg)

where is mistake, how can I do? thanks!

**Comment by Jamcao** [comment]
![7244d24570b386caf263e3b59ccc709](https://user-images.githubusercontent.com/110510944/197968345-4b16eb78-3aa1-4256-b4fb-53fd6d573d70.png)
![cb6e892393e522d660cfd4ecf32f1c1](https://user-images.githubusercontent.com/110510944/197968372-123ca0bb-0bee-406c-a01f-aaded3ab1617.png)

**Comment by fabio-ffclrp** [comment]
Go to loader and add cmdline entries:
SataPortMap: 010606
DiskIdxMap: 010700

**Comment by Jamcao** [comment]
> Go to loader and add cmdline entries: SataPortMap: 166 DiskIdxMap: 010700

Dear Fabio, Thanks very much, it wrok but still missed two disks as bellow:

![2e3bf9211ba8bb885608a6791e5f1b1](https://user-images.githubusercontent.com/110510944/198174630-573e637a-9868-4adb-a2ee-658b38345047.png)
![c2503e193f68cedd29492a6cbd9f0bf](https://user-images.githubusercontent.com/110510944/198174639-0cec0cd9-745a-4731-92c9-232a49275e4b.png)
![0766264de6d464c03a37580513b6d81](https://user-images.githubusercontent.com/110510944/198174652-a52e8dea-305b-4c89-96b6-96d27bac2742.png)

it means, my PCIE to Sata Card broken?

**Comment by fbelavenuto** [comment]
Please go to the option "Cmdline menu" from the menu and choose the "Add/edit ..." option:
![image](https://user-images.githubusercontent.com/11461290/198275391-7d61dff2-7b3e-41aa-983c-36cd3cbeaaf4.png)
Type "SataPortMap":
![image](https://user-images.githubusercontent.com/11461290/198275761-3b91d6ca-eca4-4ba9-b4fa-f70748ebc6f7.png)
In the next screen, type the correct value:
![image](https://user-images.githubusercontent.com/11461290/198275871-bf36f7fc-bbf4-44fb-8b8a-30b83b9b8d81.png)
Go to "Show user cmdline" and check if is correct:
![image](https://user-images.githubusercontent.com/11461290/198275980-fdecd8ad-8a67-4079-805d-60274c06f60c.png)

Repeat the process for "DiskIdxMap". Please check the typo, in your image you type "DiskId**e**xMap"

**Comment by Jamcao** [comment]
Very Thanks, all of them are working now!
