### ISSUE TITLE
Error: zImage not Patched

### ISSUE THREAD

**Issue by tlsnine** [fbelavenuto/arpl#27]
ARPL ver 0.2-alpha3 USB image

When building I receive two errors:
The first is "open /mnt/p1/user-config.yml: not a directory" (I also get this error if I try to manually edit the user config file)
The second is "zImage not patched" (which I assume is due to the first error) when I try building the loader.

I've tried 4 different USB drives of different brands and all larger than 4GB.
I've also used Etcher and RUFUS to make the USB with no difference.

The crazy thing is that the first time I tried the tool, it worked and I was able to setup my NAS, but after 2 or 3 reboots the DSM loader failed and kept dropping me back to the initial build scenario. The successful build was model DS3622xs+.
I've tried all of the models and both build numbers (where applicable) with no subsequent luck.

I'm not a very good coder but I'll try and help any way I can to figure this out.
FWIW I'm running an authentic Denverton Supermicro board.

Thank you for all the hard work!!

**Comment by tlsnine** [comment]
UPDATE: I used the built-in USB image writing tool in POP_OS (popsicle) and it looks like it worked again.
I'm not sure what's going on tbh, but I'm happy it's working.
I'll have to reboot it a bunch of times to make sure it's stable before moving files to it.

I'm going to keep this open for now and allow a maintainer to view and close.

Thanks

**Comment by fbelavenuto** [comment]
Thanks for report
