### ISSUE TITLE
after post install how to change things?

### ISSUE THREAD

**Issue by NietzscheX** [fbelavenuto/arpl#278]
1. download the latest image and burn it into USB.
2. boot from usb and continue setting use random MAC and SN.
3. setup DSM successfully.
4. everything goes well.
5. But this time how to change  change MAC and SN without reinstall DSM?
6. if the USB is broken, what should i do to burn a NEW USB to make things work without reinstall DSM? 
7. thanks you .

**Comment by fabio-ffclrp** [comment]
5) Just go to loader and change the S/N and MAC, is not necessary to rebuild the loader.
6) Save the files user-config.yml from first partition and "rd.gz" and "zImage" from second partition, or just write down the S/N and another necessary config to rebuild the loader. DSM will complain and ask to recover, just have it done.
