### ISSUE TITLE
Hyper-v support?

### ISSUE THREAD

**Issue by dadami-sub** [fbelavenuto/arpl#28]
As a user using Windows Server 2022 for hypervising os, it would be good if arpl supports hyper-v's network driver.
None of the existing dsm7 loaders support hyper-v (extension has been uploaded to pocopico's rp-ext repository, but it is incomplete).
If hyper-v is supported by arpl for the first time, it may be another superior advantage of arpl.
Best Regards, dadami

**Comment by fbelavenuto** [comment]
Thanks. In the vanilla linux source code and GPL'ed Synology source code, the hyper-v module do not compile!
It will take an advanced search to try to compile these modules.

**Comment by dadami-io** [comment]
you should definitely check these
https://github.com/torvalds/linux/tree/master/drivers/net/hyperv

I Reallllly hope to run xpenlogy in hyperv
Good luck!

**Comment by fbelavenuto** [comment]
Hi, 

Hyperv modules need the kernel to have a CONFIG_HYPERVISOR_GUEST setting enabled, and the DSM kernel does not!
Unfortunately there is no way to support hyper-v for now!

**Comment by fbelavenuto** [comment]
Closing
