### ISSUE TITLE
Need powersaving suggestion

### ISSUE THREAD

**Issue by huangda1982** [fbelavenuto/arpl#281]
I bought a small second-hand server, E3-1268l v3, 8G, 1 HDD@7200rpm, 1 SSD.
It consumed 25W on idle when running windows10.
Now it runs DMS loaded by arpl at 35W idle.
I have CPU C-state (C3/C6/C7) and package C-state (auto) enable in BIOS.

Any suggestion?

powertop gave suggestions like:
Enable the CONFIG_NO_HZ kernel configuration option.
disable the NMI watchdog by executing the following command:
   echo 0 > /proc/sys/kernel/nmi_watchdog
Enable USB autosuspend for non-input devices by pressing the U key
Enable the CONFIG_USB_SUSPEND kernel configuration option.
Enable the CONFIG_INOTIFY kernel configuration option.
Enable the CONFIG_USB_SUSPEND kernel configuration option.

I know what do those mean.

**Comment by fbelavenuto** [comment]
Hi, this configuration is done when compiling the kernel, and the DSM kernel doesn't have all the sources released! I don't know if Synology configured it this way, but changing it doesn't work without all available sources.

**Comment by fbelavenuto** [comment]
Closing, if the problem persists please reopen.
