### ISSUE TITLE
Can use vmware pvscsi?

### ISSUE THREAD

**Issue by nanalynKR** [fbelavenuto/arpl#29]
hello
i use esxi7, arpl 0.2a3
sata controller is fine working is good
but i testing vmware pvscsi
dsm can not find disk after install driver 
any have idea?

**Comment by fbelavenuto** [comment]
Which model did you test?

**Comment by nanalynKR** [comment]
3622XS

**Comment by fbelavenuto** [comment]
Please test with 0.3a1 fresh released

**Comment by sashakozlov86** [comment]
I had the same problem when trying to use the dva3221 assembly on vmware workstation 16 - the web interface was loaded at the ip address, but the created 50 gigabyte vdmk disk was not detected (in the vmware settings, I set sata 0: 0 to the boot disk (your image  ) and sata 1:0 to the newly created 50 GB disk).  On your advice, I tried the latest build from the eudev branch - v0.3 alpha1, built a new bootloader for DVA3221 on it, chose the latest build 42661, generated a serial number, chose to install two additional addons.  However, after the system booted, the web interface disappeared altogether (although it was available on your previous assemblies - the disk was simply not detected).  Thank you!

**Comment by fbelavenuto** [comment]
Please add manually cmdline DiskIdxMap with value 1b00

**Comment by sashakozlov86** [comment]
No, unfortunately this cmdline does not help.  On build 0.3a1, the web interface is also not available, and on build 0.2a5 hdd on dva3221 is not detected

**Comment by sashakozlov86** [comment]
Everything worked!!!  But it worked on assembly 0.2a5, on 0.3a1 the web interface is not available.  It turns out that it was necessary to write DiskIdxMap with the value 1b00 in cmdline.  Here, in DiskIdxMap, the letter I is that capital letter "i", not l - the small (lowercase) "L".  Thank you very much friend!  But pay attention, the web interface is not available on assembly 0.3a1.  I tried both in vmware workstation 16 pro and on bare metal when booting from a USB flash drive (after writing the img image through Rufus).

**Comment by nanalynKR** [comment]
i try 0.3a2 but..
Could not find vmxnet3 addon.
No ping after dsm boot.

**Comment by nanalynKR** [comment]
How do I load a module?
There doesn't seem to be a way to import a module after it has been changed to modular.

**Comment by fbelavenuto** [comment]
Do you have access to serial port?

I chenged to load modules automatically, and have vmxnet3 module builtin

**Comment by nanalynKR** [comment]
thank you for you update
but i can not connect dsm use vmxnet3
E1000E is working fine but i can not find pvscsi disk
diskidxmap=11b00

**Comment by nanalynKR** [comment]
hello
Thank you! it work use vmxnet3!
but can not find disk use pvscsi
ill try some test

**Comment by fbelavenuto** [comment]
Some success with pvscsi?

**Comment by nanalynKR** [comment]
i can use pvscsi
thank you
but i have more.
no space left on device when build loader

**Comment by nanalynKR** [comment]
version is 0.4a1

**Comment by nanalynKR** [comment]
/mnt/p3 is full

**Comment by fbelavenuto** [comment]
Thanks, closing issue
About '/mnt/p3 is full', this bug is know:
https://github.com/fbelavenuto/arpl/issues/89
For now you can increase the image disk, in vmware itself.
