### ISSUE TITLE
system will shut down abnormally

### ISSUE THREAD

**Issue by shanzigang** [fbelavenuto/arpl#291]
I compiled 918+ 7.1 42962 for a physical machine, and installed it into the system normally, but the system will shut down abnormally. Note: There are two SAS cards (9211) in the system

**Comment by shanzigang** [comment]
Sorry, it was my mistake! I checked the log carefully today, and it was caused by an automatic shutdown due to a high temperature of a hard disk. Since the previous 6.2.3 system has been running well, I didn't consider it to be a hardware problem. Now that a cooling fan is installed, the system is stable. Thanks fbelavenuto!

Remarks: The system can perfectly support SAS pass-through cards, SAS interface hard disks, and can support more than 18 hard disks (in the case of my hardware)

**Comment by fbelavenuto** [comment]
Ok, thanks, closing.
