### ISSUE TITLE
Is it possible to boot from a normal SSD?

### ISSUE THREAD

**Issue by sardaukar** [fbelavenuto/arpl#293]
I'd like to transfer the data from the USB stick I'm using now to an SSD, so I no longer have the stick poking out of my server. Is this possible?

Thanks!

**Comment by fabio-ffclrp** [comment]
Yes, You can use any tool, search for linux "dd" command or Windows software "MiniTool Partition Wizard".

**Comment by sardaukar** [comment]
Thanks!
