### ISSUE TITLE
Setting maxdisks manually doesn't work

### ISSUE THREAD

**Issue by sergejostir** [fbelavenuto/arpl#294]
Hello.

I'm using the following:
v1.0-beta2
Motherboard with 4 SATA ports
918+ model

Using arpl menu, I set maxdisks to 2. The maxdisks value is properly written to the user_config.json. However, when DSM is booted, maxdisks value is 4 in /etc/synoinfo.conf and /etc.defaults/synoinfo.conf. Additionally, internalportcfg is 0xf instead of 0x03.

What am I doing wrong? I want to reduce number of maxdisks because I'm using the last two SATA ports as eSATA.

**Comment by fabio-ffclrp** [comment]
Hi, go to loader main menu, choose "Synoinfo menu", choose the option "Set maxdisks manually" and put 2. Rebuild the loader and test it.

**Comment by aniel300** [comment]
@fabio-ffclrp do u know what is the max disk dsm can support?

**Comment by sergejostir** [comment]
Maybe my original message was not clear. I used "Set maxdisks manually".
![image](https://user-images.githubusercontent.com/21297285/200116699-c6cf5de4-7e3c-45bf-b260-257f9a008d25.png)

The setting is written to user_conf.json, but when the DSM boots up synoinfo.conf includes

> maxdisks="4"
> internalportcfg="0xf"

**Comment by fbelavenuto** [comment]
Hum, ok, my bad, I'll check for this bug, thanks.

**Comment by fbelavenuto** [comment]
Please update the addons, rebuild the loader and test it again.

**Comment by sergejostir** [comment]
It's working as expected now. Thanks a lot!

**Comment by aniel300** [comment]
It doesn't work for me
