### ISSUE TITLE
Why after loading the DSM kernel, ping fails

### ISSUE THREAD

**Issue by noway1013** [fbelavenuto/arpl#295]
How long will it take to search for nas after the U disk is started? After I compile it according to your method, the U disk starts. Ping the IP address all the time on Windows machines. After viewing the startup interface and obtaining the IP address, ping is enabled. After loading the DSM kernel, ping fails. The nas can't find it, so ask for directions.

**Comment by fbelavenuto** [comment]
Hello, DSM kernel is different from loader kernel. What is the vendor/model of your network card?

**Comment by noway1013** [comment]
Wait a little longer and  will be able to boot normally. 
Thank you for your support. 
This question can be closed, thank you.
