### ISSUE TITLE
Build loader for 7.1 42951 failed

### ISSUE THREAD

**Issue by jinlife** [fbelavenuto/arpl#298]
I'm using the arpl 1.0 beta2 version.
I can build loader successfully for 42962, 42661 and 42218. 
But I cannot build the loader for 42951. It looks like the download address of pat file changed.

**Comment by fbelavenuto** [comment]
Hi, 42951 is a beta from DSM. Synology maybe removed from your servers! I'll remove this buildnumber from ARPL

**Comment by jinlife** [comment]
Yes, you are right.
