### ISSUE TITLE
Error Update

### ISSUE THREAD

**Issue by IVvanes** [fbelavenuto/arpl#301]
Update aprl failure. Error downloading checksums. Update from ARPL 0.5-alpha1.

**Comment by Brian099** [comment]
v1.0-beta
First beta release! Alpha releases do not get this update, is necessary to burn image to flash drive/mass storage device

**Comment by fbelavenuto** [comment]
Hi, like @Brian099 say, is necessary to reburn the image, update do not works from alpha to beta!
