### ISSUE TITLE
Can't install DSM with pat file for DVA1622 build using virtualbox, Drive will not be formatted

### ISSUE THREAD

**Issue by zutewas** [fbelavenuto/arpl#305]
Hello, I can't install the DSM for DVA1622. The build of loader was sucessfully.

I add two SATA drives in VirtualBox (6.1.40).

1. arpl-dyn.vmdk
2. empty dynamic vmdk with 8gb

![pic003](https://user-images.githubusercontent.com/16150873/200174382-bd3e173d-b8a2-469f-ba89-79207dd9bf96.jpg)

After run the Boot DSM Kernel the access to http://192.168.1.169:5000/web_index.html is possible to start the installation of pat file. I select the pat file and get the message that all data will be delete from 1 founded drive.

![pic001](https://user-images.githubusercontent.com/16150873/200174237-5d9ed162-99ad-4dc9-b772-016d8f5bdb40.jpg)

Then starting installation but abort with the message the the drive can not be formated.

![pic002](https://user-images.githubusercontent.com/16150873/200174329-f78607c5-7af4-4abd-84d5-0a8ba4e61314.jpg)

Can anybody help me with this issue? Anybody is using VirtualBox with a working DSM?

Thanks :)

**Comment by sashakozlov86** [comment]
Hello!  Perhaps the problem is that you set the size of the virtual hard disk to 8 gigabytes.  Synology DSM cannot be installed on hard drives smaller than 50 GB.  Try setting the size of the SATA virtual hard disk to 50 gigabytes or more.  Hope that helped!  All the best!

**Comment by zutewas** [comment]
You save my day. Thanks for your post. It's solved.

**Comment by fbelavenuto** [comment]
Thanks @sashakozlov86

**Comment by Viking8** [comment]
> Hello! Perhaps the problem is that you set the size of the virtual hard disk to 8 gigabytes. Synology DSM cannot be installed on hard drives smaller than 50 GB. Try setting the size of the SATA virtual hard disk to 50 gigabytes or more. Hope that helped! All the best!

Thanks for letting those that didn't know this, know this! I was banging my head against a wall trying to figure out why the format wouldn't work. Just wanted to do a quick VM setup to test updating DSM and I left the disks that I created at 8GB like you said.
