### ISSUE TITLE
Can't access via SSH

### ISSUE THREAD

**Issue by vincejansen** [fbelavenuto/arpl#306]
Hello, 

First of all, a big thank you for creating this project. 

I'm currently having the following problem: 

I'm blind and I'm using a screenreader called NVDA. 

The web terminal isn't accessible, so I have to login via SSH. 

What are the credentials to do that? The default credentials from the original red pill project don't work in this loader. 

Thanks in advance and keep up the amazing work!

Vince

**Comment by fbelavenuto** [comment]
Hi, user is 'root', password is 'Redp1lL-1s-4weSomE'

**Comment by vincejansen** [comment]
Thanks, it works great!  Maybe it’s a good idea to update the documentation with this.   Keep up the amazing work! Vince   Verzonden vanuit Mail voor Windows Van:Verzonden: maandag 7 november 2022 15:46Aan: fbelavenuto/arplCC: vincejansen; AuthorOnderwerp: Re: [fbelavenuto/arpl] Can't access via SSH (Issue #306) Hi, user is 'root', password is 'Redp1lL-1s-4weSomE'—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by fbelavenuto** [comment]
Documentation updated
