### ISSUE TITLE
DVA3221 prompt under pve: Detected non-synology recommended memory module configurations

### ISSUE THREAD

**Issue by itv3** [fbelavenuto/arpl#307]
Recently migrated the DVA3221 from the esxi platform to the PVE platform, everything is perfect, except for the prompt: "Detected non-synology recommended memory module configurations" after entering the dsm desktop.
ProxmoxVE:Ver7.2-1, my hardware configuration is as shown in the figure, I have tried reinstalling with various parameters, when the installation is completed with the dsm system and the storage space is created, and then restarted to enter the DVA3221 desktop again, I will definitely get this prompt : "Detected non-synology recommended memory module configurations"

I've tried other models, such as the DS3622xs+, and the problem doesn't occur with the same hardware setup. dva3221 is also perfect under the esxi platform, there will be no error prompts
<img width="269" alt="1" src="https://user-images.githubusercontent.com/102932260/200340152-3b016b75-85fe-4a14-84e4-8c953235da55.png">
![2](https://user-images.githubusercontent.com/102932260/200340189-e0d983f4-50f8-48f2-89bb-ab0e9ecfd356.png)

**Comment by OrpheeGT** [comment]
I have the same every time I reboot mine.
I'm running it baremetal.
![image](https://user-images.githubusercontent.com/8038551/200431633-3e2abdd5-c4e5-40f3-885c-bfe04559bff4.png)

**Comment by itv3** [comment]
Confirm support_memory_compatibility: "no"
But there is still this problem, and the problem only exists in the dva3221 model in pve, other models in pve and dva3221 under the esxi platform are no problem
<img width="423" alt="3" src="https://user-images.githubusercontent.com/102932260/200528491-2f76e423-8d3f-4ae8-8f0b-bb25da171915.png">

**Comment by itv3** [comment]
I modified "support_memory_compatibility=yes", the prompt disappeared, but I don't know if this will cause other problems?

**Comment by OrpheeGT** [comment]
Funny, I just did the same on my baremetal, and no more warning message too.

**Comment by fbelavenuto** [comment]
Hum!! Thanks for the tests, I'll study if is better leave yes.

**Comment by OrpheeGT** [comment]
> Hum!! Thanks for the tests, I'll study if is better leave yes.

you may consider : support_led_brightness_adjustment="no"
too.

https://xpenology.com/forum/topic/65408-automated-redpill-loader-arpl/page/49/#comment-365280

I don't know how it is handled on virtual, but it seems necessary on baremetal.
