### ISSUE TITLE
How can I enable write caching?

### ISSUE THREAD

**Issue by cvc90** [fbelavenuto/arpl#310]
How can I enable write caching?

Model: DS-3622xs+
DSM: DSM 7.1.1-42962 Update 2
ARPL: v1.0-beta2, with all modules activated
System: UBUNTU SERVER, with VMware

![image](https://user-images.githubusercontent.com/76731844/200455686-2487d37b-92b3-4692-bd40-6bc81a72aa7e.png)

**Comment by fbelavenuto** [comment]
Hello, really do not know how! Perhaps DSM refuses due to HS incompatibility.
Please show what are your used synoinfo entries (post the user-config.yml file without the sensitive data)

**Comment by cvc90** [comment]
It is already solved in ARPL: v1.0
