### ISSUE TITLE
Install DVA3221 under ProxmoxVE platform, the following error occurs during startup

### ISSUE THREAD

**Issue by itv3** [fbelavenuto/arpl#311]
ProxmoxVE Ver 7.2-1
Use virtual usb to load the boot disk, modify <vm id>.conf, and add the following content:
args: -device 'qemu-xhci,addr=0x18' -drive 'id=synoboot,file=/var/lib/vz/images/101/arpl.img,if=none,format=raw' -device 'usb- storage,id=synoboot,drive=synoboot,bootindex=5'

After a normal boot, the serial port shows errors like these:
Are these errors normal?
![1](https://user-images.githubusercontent.com/102932260/200566647-8e676e8d-60c6-4d30-970b-c18f0f341d7c.png)
![2](https://user-images.githubusercontent.com/102932260/200566678-340ebcce-222f-495d-9736-ecb86e624f65.png)
![3](https://user-images.githubusercontent.com/102932260/200566692-0df832b9-dbdc-4321-9c14-984684fc0cef.png)
[log.txt](https://github.com/fbelavenuto/arpl/files/9961205/log.txt)

**Comment by OrpheeGT** [comment]
Hi,

I have the same on my baremetal start logs : 

```
[[1;33mDEPEND[0m] Dependency failed for rebuild local user and group db.
[[32m  OK  [0m] Reached target Synology root filesystem (rw) ready.
         Starting DSM Installation ID...
         Starting Synology Default TLS Profile...
         Starting Set Eunit Sequence...
         Starting Load AppArmor profiles...
         Starting syno-cgi-keygen.service...
```

`[[1;31mFAILED[0m] Failed to start DSM Boot Health Check.`


```
[[1;31mFAILED[0m] Failed to start synoindex check if ... any synoindex-related packages.
See "systemctl status synoindex-checkpackage.service" for details.
[[1;33mDEPEND[0m] Dependency failed for synomkthumbd.
[[1;33mDEPEND[0m] Dependency failed for synoindex plugind.
[[1;33mDEPEND[0m] Dependency failed for synoindex workerd.
[[1;33mDEPEND[0m] Dependency failed for synoindex scand.
[[1;33mDEPEND[0m] Dependency failed for synoindexd.
[[1;33mDEPEND[0m] Dependency failed for synomkflvd.
[[1;33mDEPEND[0m] Dependency failed for synoindex notifyd.
[[1;33mDEPEND[0m] Dependency failed for synoindex mediad.
```

**Comment by fbelavenuto** [comment]
I really don't know if it's normal!! Test for a few days to see if any abnormal issues occur.

I'll start looking at the log.

**Comment by OrpheeGT** [comment]
I never looked at it before, I guess it was always here, and it always worked like this... but I may be wrong.

I did not see any issues with it. I don't think it is related to ARPL direcly.

**Comment by fbelavenuto** [comment]
This errors are normal, safe to ignore. Closing
