### ISSUE TITLE
Build the loader

### ISSUE THREAD

**Issue by jklist** [fbelavenuto/arpl#314]
Prompt after recent compilation

![image](https://user-images.githubusercontent.com/115347699/200875985-21ef2876-ce77-454f-80dd-c5825b22879c.png)

![image](https://user-images.githubusercontent.com/115347699/200876055-1279048e-6573-4432-ae6a-440477908f4c.png)

![image](https://user-images.githubusercontent.com/115347699/200876095-8f451b7f-452e-4a58-b07a-e2bdf3e7cf13.png)

**Comment by jklist** [comment]
![image](https://user-images.githubusercontent.com/115347699/200876285-60b357cf-1cbe-4656-945c-60c848d5de88.png)
How do I view network problems or hard disk problems?

**Comment by fbelavenuto** [comment]
It could be the amount of RAM. Can you put 4GB or more?

**Comment by Murdock79** [comment]
I have 8GB Ram and exactly the same problem. How can i fix it?

**Comment by jklist** [comment]
> 它可能是 RAM 的数量。你能放4GB或更多吗？

The effect of 4G-8G memory is the same

**Comment by fbelavenuto** [comment]
Very strange! Type into shell: "free -h" and post the results.

**Comment by jklist** [comment]
![image](https://user-images.githubusercontent.com/115347699/204585600-a3365924-d92d-44c2-ac1b-d2f7912f5c60.png)

ESXI 7.0U3 has allocated 4G memory
![image](https://user-images.githubusercontent.com/115347699/204585907-3bfb6938-8046-46c2-9c7d-cac28445a7bc.png)

**Comment by jklist** [comment]
> 很奇怪！在 shell 中输入：“free -h”并发布结果。

It has been sent to you. I don't know if it is a network problem. In China, I can stay at my home for a while, but it will be OK again in a few days

**Comment by fbelavenuto** [comment]
Closing, if the problem persists please reopen.
