### ISSUE TITLE
Problem with long installation and boot

### ISSUE THREAD

**Issue by sashakozlov86** [fbelavenuto/arpl#32]
Good afternoon, dear friend! I have hardware: Asrock j4205-itx, 4gb ram, wd purple 1 tb, usb 2.0 flash drive 2gb (for bootloader). I downloaded the latest arrpl bootloader from the link https://github.com/fbelavenuto/arpl/releases, it compiled the bootloader for dva1622, generated a serial random one, clicked boot loader. It took a long time (10 minutes) to load (there was an inscription booting), then a picture from synology appeared on the monitor, it also took a long time to load and an inscription appeared to press enter for local installation. I clicked, then an inscription appeared that a local installation was in progress, it would take about 6 minutes, do not turn off the system. So it's been hanging with me for 30 minutes without changes. So everything should take a long time to load? The web interface is available by local ip, it offers to install the system, but I don’t even know, because it seems to be installed locally (judging by the recording from the monitor) or not?

 Maybe, of course, it's a slow flash drive, but it doesn't seem to be involved in the process at all (it blinked when loading, but now it doesn't)

 UPD: I tried to assemble the bootloader using the method from the first post (tcrp dev at the link https://github.com/pocopico/tinycore-redpill/tree/develop), while changing the flash drive to 64GB usb 3.0 sandisk. The situation has not changed anyway, everything takes a long time to load (synology screen), while the Web interface is not available via local ip). I do not know what to do...

 Thank you, friend!

**Comment by fbelavenuto** [comment]
Hi, thanks for report.

It wasn't supposed to take that long.  did you test on other usb ports on your motherboard?

**Comment by sashakozlov86** [comment]
Yes, I have tried all the usb 3.0 and 2.0 ports on the motherboard.  In bios, I turned off all processor power savings (C1 and C6, I thought maybe because of them everything slows down, but it didn’t help).  Nevertheless, the system installed during the night, worked a little, I added cameras to Surveillance station, turned on AI deep analitycs, everything worked for several hours, then I could not access the web interface, connected the monitor via hdmi and saw black  the screen with the mouse pointer, but it did not move and the system did not respond to the keyboard.  After that, I rebooted the computer using the reset button on the case and after 10 minutes an inscription appeared on the monitor for me to press enter so that the system was installed on the computer again - as if everything had been reset.  Why did it happen?

**Comment by fbelavenuto** [comment]
Unfortunately I don't know what it could be! 
I haven't had this kind of problem in my tests but I also don't have access to many test machines.
Let's leave this issue open and wait for a solution if I can reproduce and find the solution.
Thanks

**Comment by fbelavenuto** [comment]
I remembered a detail now, test with the misc addon and without it

**Comment by sashakozlov86** [comment]
Dear friend!  Thanks for trying to help me.  For the sake of experiment, I tried to boot from a flash drive from my HP x360 ultrabook.  Everything on it is remarkably fast and perfectly boot.  But, unfortunately, it does not have its own LAN connector and built-in network card.  I have an adapter (USB 3.0 - Gigabit Lan) model D-Link DUB-1312, but as I expected, this adapter is not supported by the bootloader.  If I could use Go as a network card, then I could use my ultrabook as a DVA1622 - that would be great!

**Comment by sashakozlov86** [comment]
However, it's very annoying that Xpenology dva3221 on vmware workstation doesn't see my Nvidia GTX2070 graphics card.  I wanted to use it for AI functions.

**Comment by sashakozlov86** [comment]
if you mean "misc" addon on build 0.3.a1, then web interface is not available on this build.  And on assembly 0.2a5 I did not see this addon.

**Comment by sashakozlov86** [comment]
I bought an ASRock J4125-ITX motherboard with a Geminikake J4125 processor, integrated Intel UHD 600 graphics. I installed 8 Gb DDR4 RAM. This processor and integrated video card are the native hardware platform for the DVA16222 and the system should essentially work correctly.  However, boot also takes a long time (about 10 minutes) and sometimes in the local terminal interface (control via usb-connected keyboard and mouse, display via a monitor connected via hdmi), the system freezes and loads various windows for a long time (real-time monitoring, face recognition, etc.)  .P.)

**Comment by sashakozlov86** [comment]
I tried to install a Kingston 128Gb SSD as a second disk and made it a volume for installing Synology applications.  It worked and the system now works without brakes and seems to be stable!  I would recommend that the author of the project in the description of the bootloader recommend that users install an SSD for stable system operation without brakes.
