### ISSUE TITLE
How to add extra network card driver

### ISSUE THREAD

**Issue by Pascalleung** [fbelavenuto/arpl#320]
I use v1.0  beta2 to setup 7.1.1-42962 and working fine. but how can i add extra network card driver. 
like Broadcom 5709 " pocopico.bnx2 " which the URL: https://raw.githubusercontent.com/pocopico/rp-ext/master/bnx2/rpext-index.json 

many thanks.

**Comment by fbelavenuto** [comment]
This driver already exists, you don't need to do anything
