### ISSUE TITLE
Static IP

### ISSUE THREAD

**Issue by ptitbasou** [fbelavenuto/arpl#33]
Hello, thank you very much for this project, I never succes to install DSM with other loader.
I would like to know if it is possible to fix static adress ip for dsm?

i fix it in DSM option (192.168.1.187), but I had to restart VM under proxmox and now I have 2 address:
192.168.1.187 and new one given by dhcp 192.168.1.185 and both with the same Mac address

![Capture d’écran 2022-07-16 à 23 06 49](https://user-images.githubusercontent.com/75440779/179371962-f37fe9fa-ba94-4045-b2b1-e19b26abad93.png)

**Comment by ptitbasou** [comment]
I will test but I think yes.

**Comment by fbelavenuto** [comment]
Closing. If the problem persists please reopen
