### ISSUE TITLE
Waiting IP...............:ERROR

### ISSUE THREAD

**Issue by minimoonleaf** [fbelavenuto/arpl#331]
Show Waiting IP...............:ERROR
But CMD>ifconfig
has show IP why?
https://photos.app.goo.gl/5r5mGZw6HppjewrS8

**Comment by fbelavenuto** [comment]
Small timeout!

**Comment by minimoonleaf** [comment]
Timeout?That will auto renew?
Because I try every times all show Waiting IP...............:ERROR

**Comment by fbelavenuto** [comment]
For some reason the driver for this network card is taking more than 15 seconds to get the IP, timing out the script.

I'm going to increase this time, in the next releases it should give the necessary time to work in your case.
