### ISSUE TITLE
v1.0-beta3 Does not work on vmware workstation

### ISSUE THREAD

**Issue by FZ500** [fbelavenuto/arpl#338]
v1.0-beta3 Does not work on vmware workstation

In the same way, 1.0-beta2 can be installed successfully, but in 1.0-beta3, it will be formatted together with Boot Loader HD when formatting, causing the installation to fail.

**Comment by fbelavenuto** [comment]
Please give more details

**Comment by FZ500** [comment]
There is only one BootLoader and one SATA 300G mounted on the virtual machine. When formatting 1.0beta2, only 1 disk will be displayed, but in 1.0beta3, there will be 1 and 2 two disks. After formatting, the BootLoader disk will not work. boot

![2022-11-23_chrome_0029](https://user-images.githubusercontent.com/117428082/203455108-8191a0d7-4277-474d-9c28-0cd023d35a89.png)
![2022-11-23_chrome_0031](https://user-images.githubusercontent.com/117428082/203455111-91f5e293-5372-4a17-98bd-8eb24eabe079.png)
![2022-11-23_ShareX_0027](https://user-images.githubusercontent.com/117428082/203455112-75c30cea-ab63-4e60-ab64-7904b3303cf1.png)

**Comment by x1763235201** [comment]
This is also the case with me. I hope to solve it. My system environment is esxi 6.7. Thank you very much!

**Comment by fbelavenuto** [comment]
Ok, please test changing data disk to SATA

**Comment by OrpheeGT** [comment]
I did not test with beta3, but I can confirm everything worked like a charm with beta2 on ESXi 7.0u3 with flat image.

Of course loader set to SATA 0:0 and disks tro SATA 1:X

SataPortMap=18
DiskIdxMap=1000

**Comment by FZ500** [comment]
> Ok, please test changing data disk to SATA

boot&Data Disks are in SATA mode

**Comment by OrpheeGT** [comment]
Could this be related to :

https://github.com/fbelavenuto/arpl/issues/351

?

**Comment by fbelavenuto** [comment]
Guys, please update all (ARPL, addons and modules), rebuild and test it.

**Comment by FZ500** [comment]
> Guys, please update all (ARPL, addons and modules), rebuild and test it.

The status of the upgrade 1.0beta6 is normal, thanks
