### ISSUE TITLE
DS918+ and FMA3

### ISSUE THREAD

**Issue by Pooh063** [fbelavenuto/arpl#339]
Model DS918+ has an Intel Celeron J3455 processor (https://kb.synology.com/ru-ru/DSM/tutorial/What_kind_of_CPU_does_my_NAS_have)
Does the J3455 processor support the FMA3 instruction?

**Comment by fbelavenuto** [comment]
Yes, Celeron J3455 belongs to Apollolake family, it suports FMA3

**Comment by Pooh063** [comment]
j5040 belongs to the Gemini Lake family. It turns out it also supports FMA3.
Why then can't I choose DS918+?
