### ISSUE TITLE
please add the version DSM 6.24

### ISSUE THREAD

**Issue by softwarefind** [fbelavenuto/arpl#343]
Because new version 7.1.1 is **unstable** with some function and not easy to use.

https://archive.synology.cn/download/Os/DSM/6.2.4-25556-6

**Comment by OrpheeGT** [comment]
https://github.com/fbelavenuto/arpl/issues/250

**Comment by softwarefind** [comment]
OK，I will try it .I find the JUN mod only support up to  DSM6.23.  It not  support  DSM 6.24

**Comment by fbelavenuto** [comment]
Hi, unfortunately I don't intend to support version 6.2! Is possible to use original Redpill loader or the TCRP from pocopico (https://github.com/pocopico/tinycore-redpill)
