### ISSUE TITLE
How to add extra intel i225/i226 network card driver

### ISSUE THREAD

**Issue by kvvb67** [fbelavenuto/arpl#347]
how can i add extra network card driver.
like intel i225/i226 " pocopico/rp-ext/igc/ " which the URL: https://github.com/pocopico/rp-ext/tree/main/igc
many thanks.

**Comment by fbelavenuto** [comment]
Already added! (https://github.com/fbelavenuto/arpl-modules/pull/78)
Update the ARPL and modules to get last version.
Just build the loader, the module will load automatically.

**Comment by kvvb67** [comment]
thank you every mush
