### ISSUE TITLE
System will freeze

### ISSUE THREAD

**Issue by amdmaxe** [fbelavenuto/arpl#36]
After installation the system hangs on booting and is not responsive.
I have tried a virtual and physical installation on my system.

**Comment by fbelavenuto** [comment]
Please can you give me more information? Which machine, hardware, loader version, etc.
If it is possible to get the log through the serial port it would be better.

**Comment by sashakozlov86** [comment]
I had a problem with a long installation and system boot.  And the responsiveness of the system, including the web interface, lagged a lot.  I tried to install a Kingston 128Gb SSD as a second disk and made it a volume for installing Synology applications.  It worked and the system now works without brakes and seems to be stable!  I would recommend that the author of the project in the description of the bootloader recommend that users install an SSD for stable system operation without brakes.

**Comment by fbelavenuto** [comment]
Thanks

**Comment by fbelavenuto** [comment]
Added to readme
