### ISSUE TITLE
VMXNET3 not working on beta4

### ISSUE THREAD

**Issue by Lovely-Pen-Pen** [fbelavenuto/arpl#362]
Hi,

I just tested the lastest release (1.0 beta 4) on my dev system and found that the VMXNET3 driver doesn't work on this release, there is no eth0 found. E1000e works fine.

Going back to beta 3 and the driver works fine without any problem.

I have a serial input on my VM, do you need any log or input that could help you ?

**Comment by fbelavenuto** [comment]
Hi, is not necessary a serial port. Go to loader/addons and add 'dbgutils', rebuild and boot. In the first partition have a folder named 'logs', get it and post here

I've recompiled all modules with official synology toolkit and this maybe a cause of troubles

**Comment by Lovely-Pen-Pen** [comment]
Well, it's quite useful to understand why the VM don't show up ;)

I will load dbgutils and upload the logs.

**Comment by Lovely-Pen-Pen** [comment]
Well, what happened was unexpected.

I rebooted on the loader, added dbgutils, rebuilt the loader and booted, and eth0 was there, and working.

I double checked I didn't forgot to change back to VMXNET3 and no, It was there and in my serial output, the driver loaded just fine.

So, I reuploaded the original beta 4 vmdk, and restarted.

I booted, built the loader with dbgutils, and it worked just fine, again.

Again, I reuploaded the original vmdk, and built the loader without dbgutils, and no eth0

Reboot, rebuilt with dgbutils, eth0 was there with an IP, rebooted, rebuild again without dbgutils, no eth0.

Could there be dependencies used by the VMXNET3 driver in the dgbutils add-on ?

**Comment by fbelavenuto** [comment]
@Lovely-Pen-Pen You found a strange behavior! Please get the logs via serial without dbgutils, please.

You can set LKM to prod to reduce logs

**Comment by Lovely-Pen-Pen** [comment]
[serial-prd..out.txt](https://github.com/fbelavenuto/arpl/files/10115921/serial-prd.out.txt)
[serial-dev.out.txt](https://github.com/fbelavenuto/arpl/files/10115922/serial-dev.out.txt)
The two outputs are without dbgutils, one with lkm on dev, the other on prd.

Do you need some with dbgutils loaded ?

**Comment by fbelavenuto** [comment]
Please test with the last release, beta5, without dbgutils

**Comment by Lovely-Pen-Pen** [comment]
Sorry for the delay, I had a pretty busy day yesterday.

It's working fine without dbgutils, thanks a lot.

I'm closing the ticket :)
