### ISSUE TITLE
DVA3221, why can't I find it? Is it not supported?

### ISSUE THREAD

**Issue by vojaly** [fbelavenuto/arpl#365]
DVA3221, why can't I find it? Is it not supported?

**Comment by fbelavenuto** [comment]
Yes, it is supported:
https://github.com/fbelavenuto/arpl/blob/main/files/board/arpl/overlayfs/opt/arpl/model-configs/DVA3221.yml

This model uses a newer CPU that needs to have the FMA instruction, if it doesn't appear to you, possibly your CPU doesn't support it.

You can force appear if you choose the "Disable flags restriction" option inside the "choose model" menu, but it's at your own risk, not guaranteed to work.

**Comment by fbelavenuto** [comment]
Closing, if necessary reopen it
