### ISSUE TITLE
No drives detected in DVA1622

### ISSUE THREAD

**Issue by PoorPaul** [fbelavenuto/arpl#367]
No drives detected in DVA1622. 
I used beta5 and "dbgutils" addon.
BTW, if I change the model to DS3622xs+, It works well.

**Comment by fbelavenuto** [comment]
Hi, DVA1622 is a devicetree model, only works with native SATA ports. Your machine (or VM) has native SATA ports?

**Comment by PoorPaul** [comment]
no i do not have native SATA ports. 
thx.
