### ISSUE TITLE
How to update the arpl version

### ISSUE THREAD

**Issue by wgetnz** [fbelavenuto/arpl#375]
I burned arpl on a USB flash drive, and now I want to upgrade to the latest version of arpl, how can I keep the configuration file unchanged and upgrade?

**Comment by fbelavenuto** [comment]
Just go to upgrade menu and choose "Upgrade ARPL", the loader will ask for reboot, accept it. Your configuration will be preserved.

**Comment by wgetnz** [comment]
> Just go to upgrade menu and choose "Upgrade ARPL", the loader will ask for reboot, accept it. Your configuration will be preserved.

thx

**Comment by ArmasF31** [comment]
How do I get to the upgrade menu?

**Comment by ArmasF31** [comment]
Can I also go back to the previous version in case it stops working?

**Comment by fbelavenuto** [comment]
> Can I also go back to the previous version in case it stops working?

To go back in versions, only reburning image to USB. You can preserve user-config.yml before reburning

**Comment by sansan333333** [comment]
> Just go to upgrade menu and choose "Upgrade ARPL", the loader will ask for reboot, accept it. Your configuration will be preserved.

where can i find the upgrade menu?

thx

**Comment by fbelavenuto** [comment]
Hi, sorry for typo, is "update":
https://github.com/fbelavenuto/arpl/wiki/Update-ARPL
