### ISSUE TITLE
ESXI Passthrough sata controller not detected

### ISSUE THREAD

**Issue by ChimpGamer** [fbelavenuto/arpl#378]
I have added the "Patsburg 4-Port SATA Storage Control Unit Intel Corporation" to the vm that is running arpl. This sata controller has one ssd connected to it (for testing). But it seems that it cannot be detected in arpl.
![image](https://user-images.githubusercontent.com/19960733/205297216-99acf4df-2c50-4895-97ac-31efa44d448c.png)

I can confirm that the passthrough is done correctly because when I use lspci -tv it shows the controller just fine.
![image](https://user-images.githubusercontent.com/19960733/205297785-b85c81be-adc9-43ec-ac05-ddd01cbc1ba8.png)

I can also confirm that the disk is connected correctly because when I use the lsblk command it shows the 120GB ssd (sbc)
![image](https://user-images.githubusercontent.com/19960733/205297849-d7b0b88e-b15c-4cb2-ab86-ffed52913c44.png)

Not sure if I'm doing something wrong. I hope I've provided enough information.

**Comment by fbelavenuto** [comment]
Please type some commands:
lspci -nnk
lspci -d ::106
ls -l /sys/class/scsi_host

**Comment by ChimpGamer** [comment]
Thanks for your response. I've executed all three commands and posted the results below.

lspci -nnk
![image](https://user-images.githubusercontent.com/19960733/205310558-1aab3f90-18db-41d3-8426-54557808c79d.png)

lspci -d ::106
![image](https://user-images.githubusercontent.com/19960733/205310727-873d85e3-2ed8-4ec7-a3bc-54193dc292fc.png)

ls -l /sys/class/scsi_host
![image](https://user-images.githubusercontent.com/19960733/205310893-bb43415f-17a6-487c-81e9-ea2979195d1c.png)

**Comment by fbelavenuto** [comment]
Ok, for some reason this controller is not a SATA native controller, is a SCSI controller. The ARPL only show SATA native ports.

All DSM models are not device-tree will work with this adapter (Better DS36xx series).

The "lspci -d ::106" command show only class SATA, now your adapter is another class:
![image](https://user-images.githubusercontent.com/11461290/205314007-9af17bad-0174-4bfb-a818-52ea3935ee4d.png)

I can't say if this is normal or something related to the passthrough, as unfortunately I have no knowledge in this area.

**Comment by ChimpGamer** [comment]
Alright. Thanks for help. Keep up the good work!
