### ISSUE TITLE
Hello, this virtual network card that doesn't support Hyper-V?

### ISSUE THREAD

**Issue by DreamMiu** [fbelavenuto/arpl#379]
I used Hyper-V boot and found that he couldn't recognize network card eth0
![image](https://user-images.githubusercontent.com/30835281/205372930-3ff5030a-f77c-4ec3-b799-dec42995dd87.png)

**Comment by fbelavenuto** [comment]
#262 #28

**Comment by DreamMiu** [comment]
> #262 #28

Well, I very much regret
