### ISSUE TITLE
Syslog error

### ISSUE THREAD

**Issue by cvc90** [fbelavenuto/arpl#383]
Hello, since I updated to the v1 versions of ARPL, I have errors with the SYSLOG records, as the attached photos show, it cannot start, what could be the reason?

![image](https://user-images.githubusercontent.com/76731844/205582429-1d1ef918-a3dc-4d98-ad52-c326cbba5d39.png)
![image](https://user-images.githubusercontent.com/76731844/205582235-75d17c90-59f7-4050-90fb-dc7bb73be353.png)

Other logs like the following don't work either
  
- /var/log/scemd.log
- /var/log/synosystemd.log
- /var/log/kern.log
- /var/log/nginx/access.log
- /var/log/nginx/error.log
- /var/log/dmesg

I do not have the "Reduce Syslogs / Records" module activated

In the log located in /var/log/syslog.log I found the following errors in case it can help

Error resolving reference; content='destination', name='d_syno_local_arch_db', location='/etc/syslog-ng/syno.d/synosyslog.conf.gen/auth:241:5'

Error checking the uniqueness of the persist names, please override it with persist-name option. Shutting down.; persist_name='affile_dd_writers(/dev/null)', location='/etc/syslog-ng/patterndb.d/scemd.conf:4:23'

Characteristics of the server where it runs

Model: DS-3622xs+
DSM: DSM 7.1.1-42962
ARPL: v1.0-beta6, with all modules activated
System: BAREMETAL

**Comment by MartinKuhl** [comment]
This is currently a known bug. Activate the module "Reduce Syslogs / Records" as a workaround until this error is fixed.

**Comment by cvc90** [comment]
Ok, when I activate the "Reduce Logs" module, I see that I have recovered certain logs, but I still can't run Synology's "Log Center", is this normal or do I have to modify something else?

**Comment by MartinKuhl** [comment]
Do you rebuild the loader? For me the log center is working when "Reduce Logs" addon is activaed.

**Comment by fbelavenuto** [comment]
@cvc90 , please get the contents of files:
/syslog-ng/patterndb.d/scemd.conf
/syslog-ng/patterndb.d/synosystemd.conf
and post here.

**Comment by cvc90** [comment]
I attach two screenshots with the content of the files.

File /etc/syslog-ng/patterndb.d/scemd.conf
![image](https://user-images.githubusercontent.com/76731844/205682934-9c990c9f-d4ca-4b08-a924-08e1862f6775.png)

File /etc/syslog-ng/patterndb.d/synosystemd.conf
![image](https://user-images.githubusercontent.com/76731844/205683030-98a67645-dbcc-4def-a6ad-0303e76b417b.png)

**Comment by fbelavenuto** [comment]
Please try type this:
sed 's|flags(final);||' -i /etc.defaults/syslog-ng/patterndb.d/scemd.conf
sed 's|flags(final);||' -i /etc/syslog-ng/patterndb.d/scemd.conf
sed 's|flags(final);||' -i /etc.defaults/syslog-ng/patterndb.d/synosystemd.conf
sed 's|flags(final);||' -i /etc/syslog-ng/patterndb.d/synosystemd.conf

**Comment by cvc90** [comment]
> Please try type this: sed 's|flags(final);||' -i /etc.defaults/syslog-ng/patterndb.d/scemd.conf sed 's|flags(final);||' -i /etc/syslog-ng/patterndb.d/scemd.conf sed 's|flags(final);||' -i /etc.defaults/syslog-ng/patterndb.d/synosystemd.conf sed 's|flags(final);||' -i /etc/syslog-ng/patterndb.d/synosystemd.conf

It still doesn't work, I still don't register

/var/log/scemd.log
/var/log/nginx/access.log
/var/log/nginx/error.log
/var/log/dmesg

**Comment by fbelavenuto** [comment]
Try to rewrite files:

root@DiskStation:~# **cat /etc.defaults/syslog-ng/patterndb.d/scemd.conf** 

```
filter f_scemd { program(scemd);  };
filter f_scemd_sev { level(info..emerg) };
filter f_no_auth { not facility(auth); };
destination d_scemd { file("/var/log/scemd.log"); };
log { source(src); filter(f_scemd); filter(f_scemd_sev); filter(f_no_auth); destination(d_scemd); };
```


root@DiskStation:~# **cat /etc.defaults/syslog-ng/patterndb.d/synosystemd.conf** 
```
filter f_synosystemd { match("synosystemd:" value("MESSAGE"));  };
destination d_synosystemd { file("/var/log/synosystemd.log"); };
log { source(src); filter(f_synosystemd); destination(d_synosystemd); };

filter f_systemd { program("systemd"); };
destination d_systemd { file("/var/log/systemd.log"); };
log { source(src); filter(f_systemd); destination(d_systemd); };
```

(repeat for /etc/...)

**Comment by cvc90** [comment]
File /etc.defaults/syslog-ng/patterndb.d/scemd.conf
![image](https://user-images.githubusercontent.com/76731844/206007894-b8b223d6-bc1c-4e91-8b82-84c10f6e16ef.png)

File /defaults/syslog-ng/patterndb.d/scemd.conf
![image](https://user-images.githubusercontent.com/76731844/206007937-2c50139b-787c-45fb-bf66-d39d7e77ad4d.png)

File /etc.defaults/syslog-ng/patterndb.d/synosystemd.conf
![image](https://user-images.githubusercontent.com/76731844/206007987-444db4f4-cf08-4812-92fe-e070c595a019.png)

File /etc/syslog-ng/patterndb.d/synosystemd.conf
![image](https://user-images.githubusercontent.com/76731844/206008016-521271dd-bf33-4101-8dd3-f71e68f0afc5.png)

It still doesn't work, I still don't register

/var/log/scemd.log
/var/log/nginx/access.log
/var/log/nginx/error.log
/var/log/dmesg

**Comment by fbelavenuto** [comment]
Now I'm out of ideas what the problem could be!! :(

**Comment by cvc90** [comment]
In syslog.log finds a bug in the file '/etc/syslog-ng/syno.d/synosyslog.conf.gen/auth:241:5'

![image](https://user-images.githubusercontent.com/76731844/206011789-96cefe8c-e133-473e-ab91-afaf276aed15.png)

File /etc/syslog-ng/syno.d/synosyslog.conf.gen/auth
![image](https://user-images.githubusercontent.com/76731844/206012881-a1ac4b7e-d6ee-4900-9139-02c06b64683a.png)

Could you check if your file is exactly the same?

**Comment by fbelavenuto** [comment]
No equal! The last lines is:

```
log {
    source(s_syno_synosyslog);
    filter(f_syno_auth);
    parser(p_syno_sdata_auth_synologand_0);
    rewrite(r_syno_username);
    rewrite(r_syno_args_auth);
    rewrite(r_synologand);
    destination(d_synologand);
};

```

The last line of mine is 222

**Comment by cvc90** [comment]
Could you send me a copy of the file, to test?

**Comment by cvc90** [comment]
Ok, it seems to start, but when restarting the configuration of this file is modified, but the one in charge of this is synologconfgen and when I run it it gives me a permissions error blocked by apparmor but I see that it runs python 3.9 and this was done before with python 3.8. .. I have several versions and I remember seeing modified options, could you show me how you have /bin/python*?

![image](https://user-images.githubusercontent.com/76731844/206018911-36c8f474-cb13-4fe2-941d-bb8cb1781ec3.png)
![image](https://user-images.githubusercontent.com/76731844/206018929-6b46fa74-e119-4638-b1e4-f4c1615aff75.png)

**Comment by cvc90** [comment]
Fixed!!!

Deleted file /bin/python3 and created again with symlink to version 3.8
![image](https://user-images.githubusercontent.com/76731844/206020645-2a609607-a24b-4394-af07-2a37526df5b5.png)

Run synologconfgen to recreate the configurations
![image](https://user-images.githubusercontent.com/76731844/206020932-a7844e00-f841-436d-8a64-450a4bca2214.png)

Start LogCenter
![image](https://user-images.githubusercontent.com/76731844/206021094-aae485de-ffac-4489-8fe8-655d90456ce5.png)

WebUI DSM
![image](https://user-images.githubusercontent.com/76731844/206021661-1b24b22c-beab-49bf-9e8a-dcd36f94ecb0.png)

**Comment by fbelavenuto** [comment]
There are more troubles?

**Comment by cvc90** [comment]
Everything seems to work correctly, the only thing I would like to leave the symbolic links to python in the correct way, could you show me how they are by default?

**Comment by cvc90** [comment]
Ok I have configured my python versions correctly and everything works correctly.

**Comment by fbelavenuto** [comment]
Closing, problem solved
