### ISSUE TITLE
AMD

### ISSUE THREAD

**Issue by hunter126** [fbelavenuto/arpl#387]
hello! I have a PC, the CPU is AMD 2600X, and the graphics card is Nvidia 1070, which doesn't seem to install the group hui system.

**Comment by hunter126** [comment]
hello! Is intel 12 generation cpu support？



---- Replied Message ----
| From | Fabio ***@***.***> |
| Date | 12/07/2022 01:34 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [fbelavenuto/arpl] AMD (Issue #387) |

Sorry, I don't understood your question

**Comment by fbelavenuto** [comment]
Hi, I don't have a 12th Gen Intel, but on the xpenology forum, some people are having success.
For video encoding and A.I. from Survellation, not all GPUs work. There is a group of people investigating and testing ports to work with the integrated GPU of modern CPUs.

**Comment by AuxXxilium** [comment]
12th Gen is support OOB. Usage of Intel Graphics not, your GTX1070 can be supported by DVA3221 but i think Syno loked it to a special version of GTX1650.

AMD 5600x/5950x is working OOB, too. So your 2600x should work.

**Comment by fbelavenuto** [comment]
Closing, original question explained
