### ISSUE TITLE
How to set it to support 36 hard disks. Currently, only 26 hard disks are supported

### ISSUE THREAD

**Issue by laotuoyuan1** [fbelavenuto/arpl#391]
How to set it to support 36 hard disks. Currently, only 26 hard disks are supported
如何设置才能支持36个硬盘，目前只支持26个硬盘

**Comment by laotuoyuan1** [comment]
ds3622xs

**Comment by fbelavenuto** [comment]
DSM has a limitation with naming drives, it does not support using more than one letter in the name, which limits it to 26, which is the number of letters in the alphabet.

Device-tree models support more than 26, but only work with native SATA ports (does not work with HBA)

**Comment by laotuoyuan1** [comment]
Synology has recently introduced a new model, HD6500, which supports 2 CPUs and up to 60 hard disks. I hope dalao can do a boot! thank you!

**Comment by fbelavenuto** [comment]
Closing, original question answered
