### ISSUE TITLE
The NTFS hard disk has been attached in the ESATA mode. The problem of setting the ESATA

### ISSUE THREAD

**Issue by lancaitou** [fbelavenuto/arpl#392]
![微信图片_20221207163153](https://user-images.githubusercontent.com/81699322/206128192-74e763f3-47ac-4b38-bc0e-e13ca053004d.png)
![微信图片_20221207164542](https://user-images.githubusercontent.com/81699322/206131061-5c2dfa9c-69f5-41f2-9c22-4cd5360d526d.png)

30 hard disk bits are displayed. I added parameters in cmdline
internalportcfg="0xFFF8000"
esataportcfg="0x7FFF"
Why not?
Machine translated English, please understand.

**Comment by fbelavenuto** [comment]
Hi, Device-tree models work differently, these variables do not work with these models.
Try to use one model non-DT, like DS3622XS+

**Comment by lancaitou** [comment]
Thank you. I'll try another model!

**Comment by fbelavenuto** [comment]
Closing, if problem persist, please re-open
