### ISSUE TITLE
disks not found in beta7

### ISSUE THREAD

**Issue by MartinKuhl** [fbelavenuto/arpl#394]
I updated my testsystem to beta7 and updated the addons, moduls and LKM as well.
After building and booting the loader I get the message that DSM is not installed and no harddisk is found.

I haven't changed any settings which could relate to this behavior.

**Comment by fbelavenuto** [comment]
Please give more information, what is your SATA controller (or HBA), etc.

**Comment by MartinKuhl** [comment]
I forgot that I changed the maxdisks entry. I try to revert this change.
I am working with a Paralles VM on a Mac.

**Comment by MartinKuhl** [comment]
Sorry for this issue. It was totaly my fault. I really forget that I changed this value for testing reasons.
Now after setting it back, everything is normal again.
