### ISSUE TITLE
"This file cannot be installed, the file may be damaged" Problem

### ISSUE THREAD

**Issue by ChristianSwift** [fbelavenuto/arpl#400]
![111](https://user-images.githubusercontent.com/20925565/206373080-2e488d59-3578-4a54-8795-b7fd5b6bd053.png)  
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/20925565/206373131-63d195a0-4a56-4b92-9ea1-b42134aa2599.png">  
<img width="1902" alt="image" src="https://user-images.githubusercontent.com/20925565/206373161-da12074b-5f88-43fd-b9ff-4194807c1d5f.png">

My environment is ESXi 6.7 u2, SATA Controller, DVA3221(other model not work either)

**Comment by ChristianSwift** [comment]
v1.0-beta to v1.0-beta7 are all the same

**Comment by qiuyan81** [comment]
v1.0-beta9 same error

**Comment by ChristianSwift** [comment]
> Try increasing the data HD size, put at least 100GB

Not work, already set to 150GB, still not work, and i tried upgrade my esxi to esxi 7.0.3, noting changed
<img width="627" alt="image" src="https://user-images.githubusercontent.com/20925565/207762762-33d93bd3-399a-4089-b3f2-25cda7ac0823.png">
<img width="783" alt="image" src="https://user-images.githubusercontent.com/20925565/207762793-922520aa-17fb-4267-b526-cdff8efa3cc6.png">

**Comment by fbelavenuto** [comment]
Okay, so try something else, when asked for the .pat file select to automatically download from Synology's servers, it's safe to select this option.

**Comment by ChristianSwift** [comment]
> 好的，所以尝试其他方法，当要求选择从 Synology 的服务器自动下载 .pat 文件时，选择此选项是安全的。

Already done this, but not work, upload pat file and download from synology server are all the same

**Comment by fbelavenuto** [comment]
Please add the addon "dbgutils", rebuild the loader, try to install, shutdown the machine after error and get logs from folder "logs" into first partition

**Comment by ChristianSwift** [comment]
> Please add the addon "dbgutils", rebuild the loader, try to install, shutdown the machine after error and get logs from folder "logs" into first partition

But where is the "logs" folder?  
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/20925565/208436334-e8ee79e2-061d-4963-8fde-5a69bd7a7f2b.png">

**Comment by fbelavenuto** [comment]
It was supposed to be on the partition labeled "ARPL1"!!

**Comment by ChristianSwift** [comment]
> 

ARPL1 does not have logs folder, by the way, dbgutils already installed.  
<img width="1913" alt="image" src="https://user-images.githubusercontent.com/20925565/208439313-cfcbbbcd-2183-4beb-b165-3d272caa250c.png">

**Comment by ChristianSwift** [comment]
> It was supposed to be on the partition labeled "ARPL1"!!

<img width="1897" alt="image" src="https://user-images.githubusercontent.com/20925565/208439619-2303edca-469e-4583-ad60-69d58afefe50.png">

**Comment by fbelavenuto** [comment]
Did you rebuild the loader, boot it and try to install again?

**Comment by ChristianSwift** [comment]
> Did you rebuild the loader, boot it and try to install again?

Of cause i rebuild the loader and boot and install

**Comment by ChristianSwift** [comment]
> Did you rebuild the loader, boot it and try to install again?

tried several times, all the same, no logs folder

**Comment by wlmh110** [comment]
I have met the same problem.
And I also tried adding the dbgutils, but no logs can be found.

**Comment by fbelavenuto** [comment]
Ok, some trouble with dbgutils addon.

**Comment by ChristianSwift** [comment]
> Ok, some trouble with dbgutils addon.

The actual prompt is "Failed to install the file. The file is probably corrupted.", may be this problem related to #319 , but i tried everything i could try, include change SCSI controller to SATA controller even NVME controller, network driver switched to vmnet3 from e1000e etc. this problem always happened.  
<img width="608" alt="image" src="https://user-images.githubusercontent.com/20925565/211035539-f3860eb9-0660-4634-a0e9-61d31ad66878.png">

**Comment by ChristianSwift** [comment]
in case, my environment is esxi 7.0U3g running on an E5-2680v4 if any helps

**Comment by ChristianSwift** [comment]
> I tested the dbgutils addon in several scenarios and it's working here!! I really don't know what could be going on. Something occurred to me now, as you use VMWare, it is possible to add a serial port and configure it to save in a file, this way it is possible to see the entire log.  
<img width="781" alt="image" src="https://user-images.githubusercontent.com/20925565/211580615-fe845fd6-76fb-4998-a66e-9c17d7cd8acc.png">  
[serial.txt](https://github.com/fbelavenuto/arpl/files/10383629/serial.txt)  
okey, here is my seriel.out log from esxi

**Comment by fbelavenuto** [comment]
This file is incomplete! try shutting down the VM before getting the serial.txt file

**Comment by ChristianSwift** [comment]
> This file is incomplete! try shutting down the VM before getting the serial.txt file

lets see the screen record.   
 
[serial.out.txt](https://github.com/fbelavenuto/arpl/files/10389052/serial.out.txt)  
and the screen record is here  
https://drive.google.com/file/d/1HlEgiaKwSbWLqG5FJNxvJOSrlAqit0Pd/view?usp=share_link

**Comment by fbelavenuto** [comment]
Ok, when configure the ARPL disk, configure as SATA, not IDE.
You can confirue ARPL on SATA1:0 and configure ESXi to boot from SATA1:0. Data disks configure on SATA0:x

**Comment by ChristianSwift** [comment]
> Ok, when configure the ARPL disk, configure as SATA, not IDE. You can configure ARPL on SATA1:0 and configure ESXi to boot from SATA1:0. Data disks configure on SATA0:x

WTF, it really worked, but i tried set boot disk as SATA0:x before while it not work, why set it to SATA1:x could work?

**Comment by fbelavenuto** [comment]
> WTF, it really worked, but i tried set boot disk as SATA0:x before while it not work, why set it to SATA1:x could work?
It's for the numbering of the HDs to be correct, that's all.

**Comment by fbelavenuto** [comment]
Closing, problem solved
