### ISSUE TITLE
Integrate virtIO drivers

### ISSUE THREAD

**Issue by qdrop17** [fbelavenuto/arpl#414]
Hi there.

It would be great if https://github.com/RedPill-TTG/redpill-virtio could be integrated? This would massively benefit all virtualization / proxmox users.

I get max. 60MB/s of transferspeeds (even on a virtual SSD). Using virtIO could massively accelerate this.

Is there a workaround to enable it individually?

Thanks for considering.

**Comment by chchia** [comment]
it is already included....

**Comment by qdrop17** [comment]
Alright, fair enough. Thanks for your answer.
I got virtIO networking up and running. But it still seems impossible to use disks via virtIO. How can this be accomplished?

**Comment by fbelavenuto** [comment]
Hi, what is the DSM model choosed? The Device-tree models only works with native SATA.

**Comment by qdrop17** [comment]
I chose a DS2422+. Where is documented what models are what type?
I found a documentation of a working virtIO setup nowhere. Is this even feasable?

**Comment by fbelavenuto** [comment]
> I chose a DS2422+. Where is documented what models are what type? I found a documentation of a working virtIO setup nowhere. Is this even feasable?

Hello, in the model menu, when one of them is device-tree, a "DT" appears on the right. 

If you want to use a SCSI driver with virtio you will need to choose another non-DT model.

**Comment by qdrop17** [comment]
Alright, I just got it with scsi0 working (on a non-DT model). Using virtio0 seems not to be working (despite having virtio blk drivers integrated).

I think we can close this now.
