### ISSUE TITLE
downloading .pat is very slow

### ISSUE THREAD

**Issue by junner-hu** [fbelavenuto/arpl#416]
Due to network reasons;Can I change the download address or proxy??

**Comment by fbelavenuto** [comment]
Hello, the loader does not allow this! You can change the download URL within the model configuration files, in /opt/arpl/model-configs, but it will not be saved after reboot.
You can place the already downloaded files in the third partition, in /mnt/p3/dl. You can use windows sharing (samba) for this copy.

**Comment by fbelavenuto** [comment]
Closing, question clarified
