### ISSUE TITLE
j5040 and FMA3 and DS918+

### ISSUE THREAD

**Issue by Pooh063** [fbelavenuto/arpl#435]
j5040 belongs to the Gemini Lake family. It turns out it also supports FMA3.
Why then can't I choose DS918+?

**Comment by fbelavenuto** [comment]
Try to choose "Disable flag restriction" inside model menu.

**Comment by Pooh063** [comment]
Yes, I selected "Disable Flag Restriction", and loaded the DS918+ model without error.
So I can safely operate the DS918+ (with the flag disabled)? Or errors related to FMA3 support may occur in the future, during operation?
And what is the fundamental difference between the DS918+ and DS920+ models? Which model is preferable to choose?

**Comment by fbelavenuto** [comment]
> Yes, I selected "Disable Flag Restriction", and loaded the DS918+ model without error. So I can safely operate the DS918+ (with the flag disabled)? Or errors related to FMA3 support may occur in the future, during operation? And what is the fundamental difference between the DS918+ and DS920+ models? Which model is preferable to choose?

You can use without problems. In fact, the community still hasn't discovered what really causes problems with models that use fourth generation CPUs and above. The closest they've come up with is this FMA3 instruction.

The DS920+ model is a device-tree model, it only works with native SATA ports.

**Comment by Pooh063** [comment]
That is, it is preferable to use DS918+? (intel j5040)

**Comment by fbelavenuto** [comment]
> That is, it is preferable to use DS918+? (intel j5040)

Yes!

**Comment by fbelavenuto** [comment]
Closing, problem solved
