### ISSUE TITLE
How to install the old version of DSM.

### ISSUE THREAD

**Issue by luyvlei** [fbelavenuto/arpl#437]
I have tried to install dsm-7.0.1-42218. But when loading the system, it automatically download the latest dsm-7.1.1-42962. 

It seems that my disk has some file created in dsm-7.1.1-42962 so I must upgrade the DSM to the latest version. Is there any solution to deal this problem? The dsm7.1.1 need to register for the "Advanced Media Extensions" to play the video of HEVC format but I don't have a correct SN/MAC pair for registration .

**Comment by luyvlei** [comment]
The new update6 of dsm7.0.1 also need to register for the "Advanced Media Extensions". 

My solution to downgrade version is disconnecting the wan of router then fore-reinstall the dsm via arpl. Then upload the 7.0.1-42218 pat file, the version of dsm will be 7.0.1-42218-update3. It seems that the dsm will auto download and install the small-fix version in the process of installation.

**Comment by exeron21** [comment]
if i am using emby or jellyfin instead of dsvideo, should i stay at 7.0.1-42218 for "Advanced Media Extensions"?

> The new update6 of dsm7.0.1 also need to register for the "Advanced Media Extensions".
> 
> My solution to downgrade version is disconnecting the wan of router then fore-reinstall the dsm via arpl. Then upload the 7.0.1-42218 pat file, the version of dsm will be 7.0.1-42218-update3. It seems that the dsm will auto download and install the small-fix version in the process of installation.

**Comment by luyvlei** [comment]
There's no need because emby/jellyfin has it's own ffmpeg which doesn't
rely on the AME.

git4u ***@***.***>于2023年5月17日 周三15:54写道：
