### ISSUE TITLE
Can't wake on lan through this bootloader

### ISSUE THREAD

**Issue by milkman-wang** [fbelavenuto/arpl#439]
I've checked all settings, they're set properly. Before using this bootloader, it works well on my nas. I think it is because it can get online.

**Comment by chdeast** [comment]
I have the same problem.

**Comment by Elix-g** [comment]
Confirmed, wake-on-lan don't work anymore since I moved to arpl. It was working well before with TinyCore. Baremetal system with ASUS P8H67-I Deluxe using integrated Realtek RTL8111E GigE.

**Comment by MartinKuhl** [comment]
for me it is the other way around. ARPL is working fine for me instead of TinyCore

**Comment by milkman-wang** [comment]
Maybe it is possible to add ethtool to it, since the boot loader is based on Linux.

**Comment by chdeast** [comment]
> 也许可以向其添加ethtool，因为引导加载程序基于Linux。

As shown in the figure, ethtool displays normally. I don't know what the reason is. It may be a driver problem.
![111](https://user-images.githubusercontent.com/87355575/209303070-8b8885c0-15e4-4a8b-acea-5ddfcb1dd335.png)

**Comment by milkman-wang** [comment]
> > 也许可以向其添加ethtool，因为引导加载程序基于Linux。
> 
> As shown in the figure, ethtool displays normally. I don't know what the reason is. It may be a driver problem. ![111](https://user-images.githubusercontent.com/87355575/209303070-8b8885c0-15e4-4a8b-acea-5ddfcb1dd335.png)

I mean check ethtool in the boot loader, which doesn’t include ethtool. I suppose you checked it in DSM right?

**Comment by chdeast** [comment]
> 也许可以向其添加ethtool，因为引导加载程序基于Linux。

My Linux foundation is poor. How can I check it? Thank you very much.

**Comment by milkman-wang** [comment]
> > 也许可以向其添加ethtool，因为引导加载程序基于Linux。
> 
> My Linux foundation is poor. How can I check it? Thank you very much.

我是说你这张图的内容是在群晖查看的ethtool吧，我认为他那个引导里面没有这个东西就开不了网络唤醒

**Comment by fbelavenuto** [comment]
Please update ARPL, reboot, update modules, addons and lkm, rebuild the loader and test it.

**Comment by milkman-wang** [comment]
> Please update ARPL, reboot, update modules, addons and lkm, rebuild the loader and test it.
Thanks for your reply.
I've update these to latest version, the beta 13. And I test the ethtool, it works.
But when I reboot my nas, the wol turns out to be disabled.
I tried to add autostart script to /etc/profile.d, and gave permissions. But after restarting, the script disappears.
However, the wol needs to be enabled every launching, or it is meaningless.
So is it possible to allow us to add or edit startup scripts? Or is it just a bug? Otherwise the wol needs to be enabled manually every time, it is quite inconvenient.
Thanks again for your work.

**Comment by milkman-wang** [comment]
> Please update ARPL, reboot, update modules, addons and lkm, rebuild the loader and test it.

Thanks for your reply.
I've update these to latest version, the beta 13. And I test the ethtool, it works.
But when I reboot my nas, the wol turns out to be disabled.
I tried to add autostart script to /etc/profile.d, and gave permissions. But after restarting, the script disappears.
However, the wol needs to be enabled every launching, or it is meaningless.
So is it possible to allow us to add or edit startup scripts? Or is it just a bug? Otherwise the wol needs to be enabled manually every time, it is quite inconvenient.
Thanks again for your work.

**Comment by fbelavenuto** [comment]
@milkman-wang What is the command to turn on the WoL?

**Comment by milkman-wang** [comment]
> @milkman-wang What is the command to turn on the WoL?

First type “ifconfig” to check out your network card’s name.
Then type “ethtool <your card name>”, and you will see the parameter behind “Wake-on”.
![A3DC867A-84B7-4EEC-A2E2-DA52313E52A3](https://user-images.githubusercontent.com/109866905/214029767-9e4311ea-7818-4508-97a1-6cda2a8f1e23.png)

-g means enabled, or it shows -d
If it shows -d, then type “ ethtool -s <your card name> wol g”.

When you set it up, please reboot and check the parameter again.

**Comment by fbelavenuto** [comment]
Just to confirm, WoL is enabled in BIOS and DSM?

**Comment by milkman-wang** [comment]
> Just to confirm, WoL is enabled in BIOS and DSM?

Confirmed.

**Comment by milkman-wang** [comment]
> > Just to confirm, WoL is enabled in BIOS and DSM?
> 
> Confirmed.

It only works one time when you enable WoL and select boot DSM, and then shut down the nas.
But next time you wake the nas on lan, it can not work. You will find that the parameter of wol in ethtool recovered to -d. I’ve checked BIOS and DSM settings, nothing abnormal.
The problem is the change in ethtool is not permanent. It needs to be edited every time you boot DSM. So I thought add a auto start script to ARPL, but it failed as I described before.

**Comment by fbelavenuto** [comment]
Please test with this image:
https://github.com/fbelavenuto/arpl/actions/runs/3988548866

**Comment by milkman-wang** [comment]
> Please test with this image:
> https://github.com/fbelavenuto/arpl/actions/runs/3988548866

It doesn't work.
I record a video, it might be helpful.
[https://drive.google.com/file/d/1zT2AwmYbe92-VnCtIWtOp69VCv_7YtPn/view?usp=share_link](url)

**Comment by fbelavenuto** [comment]
I've added one new addon, called "wol". It run the command inside DSM.
The ARPL is based on RAM disk, to add a script is necessary to dismount the ramdisk image, add the script and remount. I can do this for permanent execution

**Comment by milkman-wang** [comment]
> I've added one new addon, called "wol". It run the command inside DSM.
> The ARPL is based on RAM disk, to add a script is necessary to dismount the ramdisk image, add the script and remount. I can do this for permanent execution

Looking forward to it. After all, it’s an essential and indispensable feature that can keep nas from working all day long.

**Comment by fbelavenuto** [comment]
Test with this image:
https://github.com/fbelavenuto/arpl/actions/runs/3996435588

**Comment by milkman-wang** [comment]
It worked perfectly. Thanks for your endeavors!

**Comment by milkman-wang** [comment]
> Test with this image:
> https://github.com/fbelavenuto/arpl/actions/runs/3996435588

I viewed your change log just now and I thought maybe you could improve it.
![E143F805-D4C4-4028-B220-53882BD46A0B](https://user-images.githubusercontent.com/109866905/214457374-f86b6cae-edf6-49b0-9956-e62a132de8c6.png)
Not every network card is named “eth0”, if someone’s card called other name, then the wol is unusable.
Therefore, maybe it’s possible to let users customize in menu.sh, that would be more convenient though.

**Comment by fbelavenuto** [comment]
Thanks
