### ISSUE TITLE
atlantic driver support

### ISSUE THREAD

**Issue by Cryental** [fbelavenuto/arpl#44]
Hello. Can you please add atlantic driver to modules? I made a pull request to arpl-modules but not sure if it's correct way.

**Comment by Cryental** [comment]
model is DS3617xs.

**Comment by fbelavenuto** [comment]
Ok, I'll check. Do you have serial access to be able to capture the log?

**Comment by Cryental** [comment]
Actually I don't know what kind of log you need, can you tell me commands so I can run and tell you? Thank you!

**Comment by Cryental** [comment]
Sorry, no serial port exists :(

**Comment by fbelavenuto** [comment]
Please try update modules and rebuild loader

**Comment by fbelavenuto** [comment]
Please try with this image:
https://github.com/fbelavenuto/arpl/suites/7464416747/artifacts/305736183

**Comment by Cryental** [comment]
It says Failed to generate URL to download artifact. Can you send another link?

**Comment by Cryental** [comment]
I tried to boot with latest build and it doesn't even boot.

**Comment by fbelavenuto** [comment]
Please test with 0.3-alpha4, update modules after first boot.

**Comment by Cryental** [comment]
Now I'm going to test, will let you know :)

**Comment by Cryental** [comment]
System is booted successfully with 0.3-alpha4, and I cannot see atlantic one T_T

The device is recognized with arpl, but not in DSM. What should I do?

**Comment by Cryental** [comment]
This is lspci output in DSM 7:

0000:01:00.0 Class 0200: Device 1d6a:07b1 (rev 02)

And that device id is: AQC107 NBase-T/IEEE 802.3bz Ethernet Controller [AQtion]

Hope it can help you to fix.

**Comment by fbelavenuto** [comment]
If your have access to installed DSM, is possible get the log from SSH

**Comment by Cryental** [comment]
What log do you want from SSH?

**Comment by fbelavenuto** [comment]
Please get output from commands:
dmesg
cat /var/log/messages

**Comment by Cryental** [comment]
Ah no problem. It worked with several restarts :) Thank you!
