### ISSUE TITLE
How to generate img

### ISSUE THREAD

**Issue by chdeast** [fbelavenuto/arpl#440]
Please tell me how to generate an img file as a backup after making the boot with your method. Thank you (translated by software, sorry).

**Comment by fbelavenuto** [comment]
Is not possible! You can backup the "user-config.yml" file on the first partition.

**Comment by MartinKuhl** [comment]
You can create a raw backup of your usb stick with the following tool: https://www.alexpage.de/usb-image-tool/download/

**Comment by chdeast** [comment]
> 您可以使用以下工具创建USB记忆棒的原始备份：https://www.alexpage.de/usb-image-tool/download/

Thank you very much.

**Comment by fbelavenuto** [comment]
Closing, question explained
