### ISSUE TITLE
Can you set the default number of hard disks to 36

### ISSUE THREAD

**Issue by laotuoyuan1** [fbelavenuto/arpl#442]
Today, I checked the configuration file and found that the maximum number of disks is empty。It needs to be changed manually. Can it be set to 36 by default so that it does not need to be changed every time.

**Comment by fbelavenuto** [comment]
Hi, maxdisks is configured automatically. For non-DT models the limit is 26, for DT models (only works with native SATA) no limit

**Comment by laotuoyuan1** [comment]
DT models？What do you mean?

**Comment by laotuoyuan1** [comment]
I experimented in esxi, started with stat hard disk, added 26 hard disks, and the last one was unrecognized

**Comment by fbelavenuto** [comment]
DT-models means Device-tree models.
Some new models use a different technique to work with HDs. They use a technology called "Device-tree" to tell you how many SATA disks and what positions these disks are in. This way there is no limit of 26 disks (the old method uses the letters of the alphabet to name the disks, from sdA to sdZ), but it is only compatible with native SATA ports

**Comment by laotuoyuan1** [comment]
Is this the model where the suffix has DT?

**Comment by fbelavenuto** [comment]
> Is this the model where the suffix has DT?

Yes!

**Comment by laotuoyuan1** [comment]
I have virtualized the ds1621+in the esxi and added 22 hard disks, which can be displayed normally. It should be successful

**Comment by laotuoyuan1** [comment]
I will try it on the physics machine tomorrow to see if it can succeed

**Comment by fbelavenuto** [comment]
Ok, if works, please close the issue.
