### ISSUE TITLE
It is hoped that virtual NIC drivers such as vmxnet3 can be added

### ISSUE THREAD

**Issue by skyatcn** [fbelavenuto/arpl#443]
It is hoped that virtual NIC drivers such as vmxnet3 can be added，thanks

**Comment by fbelavenuto** [comment]
Hi, already exists! For example for apollolake platform:
https://github.com/fbelavenuto/arpl-modules/blob/main/apollolake-4.4.180/vmxnet3.ko
Just build the loader, module must be loaded automatically
