### ISSUE TITLE
[Question] Is there an option to show boot log?

### ISSUE THREAD

**Issue by mritd** [fbelavenuto/arpl#448]
I just started using arpl, first of all thanks to all developers for their efforts.

I started XPEnology using arpl in ESXi 8.0 and ESXi 6.7; I found that there is a certain probability that it will not boot when restarting, and the terminal will not prompt any errors.

Is there some option to turn on something like Debug logging? I wonder why XPEnology gets stuck.

![Xnip2022-12-22_20-20-32](https://user-images.githubusercontent.com/13043245/209133749-adcf3588-aff0-4651-8409-a9eef6b48662.png)

**Comment by AuxXxilium** [comment]
Add a serial port to vm and log output to file.

**Comment by mritd** [comment]
@AuxXxilium 👍 Thanks for your reply, I can already see the output log.
