### ISSUE TITLE
The network doesn't work.

### ISSUE THREAD

**Issue by terra35** [fbelavenuto/arpl#45]
After building the Model DS3622xs+ and booting up, Ethernet deadlocks. However, if I build and boot DS920+, it works fine. Does it not work with DS3622xs+?

environment: 
1. HW : intel j4125, realtek Lan  
2. arpl : v0.3-alpha3, Bare Metal installation

**Comment by fbelavenuto** [comment]
Please try update modules and rebuild loader

**Comment by terra35** [comment]
> Please try update modules and rebuild loader
Update Build -> Stop Reboot.
Network still not working after booting DSM kernel

![image](https://user-images.githubusercontent.com/19323500/180438626-45e4ead9-8792-4b02-ae33-6f3975eb6cb4.png)

**Comment by terra35** [comment]
> Please try update modules and rebuild loader

Update modules & rebuild -> Reboot ->
Network hangs after "booting..." message

![image](https://user-images.githubusercontent.com/19323500/180446886-d5817c2a-0de0-475e-8efe-ec73a07d67ee.png)

**Comment by terra35** [comment]
v0.3 alpha5 resolved. Thank you.!

**Comment by terra35** [comment]
v0.3 alpha5 resolved. Thank you.!

**Comment by terra35** [comment]
v0.3 alpha5 resolved. Thank you.!
