### ISSUE TITLE
Error downloading Check internet orcache disk space

### ISSUE THREAD

**Issue by Crazy-FuQing** [fbelavenuto/arpl#451]
你好，在 Build the loader 下载Ds918+-42218.pat 的时候出现报错 硬件环境为 华擎j3455

Hello, when building the loader to download Ds918+-42218.pat, an error was reported. The hardware environment was Chinese Engine j3455

![0b2128d4443547bf47149fca34ad016](https://user-images.githubusercontent.com/46838021/209459581-e9365707-9390-40e3-a807-fdeee39bb830.png)
![1671951610291](https://user-images.githubusercontent.com/46838021/209459583-ea433f5b-afa4-4352-884f-c644c4c5cc97.png)

![f7143f7e239b9595c91fbfcedbb38e8](https://user-images.githubusercontent.com/46838021/209459570-6c34e5c9-d967-4c02-affc-855232231737.png)
![0d685bb10ad10dfd280ce51025d85f8](https://user-images.githubusercontent.com/46838021/209459573-f2844518-2fa0-4d9c-943f-31327234bd9c.png)

**Comment by AuxXxilium** [comment]
Is it showing an IP in line on top of the screen?

**Comment by Crazy-FuQing** [comment]
yes You can visit http://10.168.1.102:7681/ and can be connected to the Internet

>

**Comment by AuxXxilium** [comment]
can you try the command: "ping -c 4 8.8.8.8"

use this command instead of menu.sh and please send the output here

**Comment by Crazy-FuQing** [comment]
I changed a USB disk to install arpl, and no error was reported. The problem has been solved, thanks for your reply

**Comment by AuxXxilium** [comment]
[Close]
