### ISSUE TITLE
为什么引导成功 就是检测不到硬盘呢

### ISSUE THREAD

**Issue by 292818** [fbelavenuto/arpl#452]
我用的是镜像直装编译的

**Comment by lxxii** [comment]
检查硬盘是什么模式

**Comment by 292818** [comment]
> 检查硬盘是什么模型

能详细介绍一下码  或者有教程码

**Comment by MartinKuhl** [comment]
in english please!

**Comment by hulang** [comment]
@292818 黑群晖老问题找不到硬盘，需要bios开启ahci，百度搜索bios修改硬盘模式，ide和ahci两种模式。我开启ahci就找到硬盘了。之前一直找不到。

**Comment by fbelavenuto** [comment]
Closing, do not undestood
