### ISSUE TITLE
N54L 4GB or 8GB ram auto reboot, Cannot load into DSM 7.XX

### ISSUE THREAD

**Issue by Jacksonlcy** [fbelavenuto/arpl#454]
Want to upgrade my N54L with  2*hynix ddr3 4gb 1333 ECC & upgrade to DSM 7.XX

Loader 1.03B  DS3615xs DSM 6.2.3
8GB, 4GB , 2GB RAM
All Works

ARPL v1.0beta9 DSM DS3615xs DSM7.1.1
Only works with the original 2GB RAM come with N54L
Cannot load into DSM with 4GB/8GB ram, infinite boot loop.

Please Help!

**Comment by Jacksonlcy** [comment]
Same issue? How can I download the file?
https://github.com/fbelavenuto/arpl/actions/runs/3244163012

**Comment by fbelavenuto** [comment]
Hi, please test enabling direct boot (into advanced menu). Enable it and boot.

**Comment by Jacksonlcy** [comment]
> Hi, please test enabling direct boot (into advanced menu). Enable it and boot.

Thanks fbelavenuto. Problem solved!
