### ISSUE TITLE
Can`t find lan with Intel i226-v chipset.

### ISSUE THREAD

**Issue by w3a4gh69** [fbelavenuto/arpl#455]
Is there anything i can do?

**Comment by viethvq** [comment]
also problem with Lan Broadcom on my old laptop Acer Aspire 4740

**Comment by stonebreaker2019** [comment]
alright. if that happens to you, it will occur on my hardware. I decide to install it in PVE.

**Comment by hotbullet** [comment]
is this getting 226 getting support? 225 works well. thanks.

**Comment by w3a4gh69** [comment]
> is this getting 226 getting support? 225 works well. thanks.

I have i225 and i226 both.

225 works well but 226 is not working.

**Comment by hotbullet** [comment]
everything works now on i226. Thanks,from b10a

**Comment by fbelavenuto** [comment]
Ok, good to know!! Closing...
