### ISSUE TITLE
 HP Pavilion x360 convertable issue

### ISSUE THREAD

**Issue by sashakozlov86** [fbelavenuto/arpl#46]
Hello!  I'd like to install a baremetal build on an HP Pavilion x360 convertable 14-ba103ur ultrabook with an 8th gen Intel I5 processor, 6 GB RAM, a 128 GB M.2 SSD, and a WD Blue 1 Tb hard drive.  As a LAN card, I use a TP-Link UE300 USB 3.0 adapter based on the Realtek 8156 chip. After generating the serial number and assembling the bootloader for DVA1622 version 42661 and loading it, the Synology DVA1622 image comes out, however, nothing happens.  The web interface is not available.  I tried to look at the LAN IP address of the TP-link UE300 adapter in the router settings, but the router does not see it and does not assign an IP address to it, although the signal reception LED on the adapter blinks and the IP address of the adapter was determined when the bootloader started.  Help me please!  Thank you!

**Comment by fbelavenuto** [comment]
Please test with this image:
https://github.com/fbelavenuto/arpl/suites/7466478056/artifacts/305866341

**Comment by sashakozlov86** [comment]
Dear friend, good afternoon!  Unfortunately this doesn't help.  I also tried to boot from version 0.3a5 (I assembled an assembly for DVA3221 on this laptop), but for some reason, after booting, the connection with the laptop is lost (in the list of router devices) and, accordingly, I can’t find the device in the browser.  At the same time, when loading a usb flash drive before the booting inscription, the IP address of the device is determined as 192.168.0.3, during the assembly of the bootloader it was also determined, downloaded .pat when the build button was pressed.  It is after the inscription booting that the connection disappears and the device is not visible in the router.  As a LAN adapter, I use Tp-link UE300 based on the Realtek RTL8153 chip (as I understand it, the bootloader has no problems with its definition, since the ip-address is determined when assembling and loading the flash drive before booting).  At the same time, even after the device becomes unavailable in the router, the tp-link ue300 led indicator continues to flash, as if there is network activity.  I don’t know, maybe this is a problem, of course, but in this laptop only a 128 GB M.2 SSD is installed as a storage device.  SATA devices are missing.  Thank you very much in advance, dear friend!  Good luck to you and your project, and most importantly, good health!

**Comment by sashakozlov86** [comment]
Dear friend!  I tried to remove the M.2 SSD and install a 320 GB SATA HDD.  The situation has not changed, after the inscription booting in the router, the connection and the tp-link ue300 IP address disappear.  The router also tried to reboot, but it does not help.

**Comment by sashakozlov86** [comment]
Everything worked on bootloader 0.4a1.  But it was necessary to add the physical mac-address of the network card (usb adapter) to the cmdline with the "mac1" parameter, and also add the "netif_num" parameter with the value "1" there.  Thank you!

**Comment by fbelavenuto** [comment]
Fixing mac1 and netif_num variables in the next release
