### ISSUE TITLE
KVM issue, cant format disk

### ISSUE THREAD

**Issue by tiagogbarbosa** [fbelavenuto/arpl#464]
Hi,

Im having a problem with KVM/QEMU so that synology cant format the disk, what im doing wrong?
![image](https://user-images.githubusercontent.com/8936001/210289944-16eabc36-7625-4358-a5cf-1a15800605b9.png)
![image](https://user-images.githubusercontent.com/8936001/210289952-24bd1433-8c34-4267-ad2e-3803e96d346b.png)

Command used to create VM
`virt-install --name=synology1 --vcpus=4 --memory=2048 --disk path=/opt/arpl-flat1.vmdk,bus=usb,target.dev=sdb,boot.order=1 --controller usb3 --disk path=/opt/syno1-hd1.img,format=qcow2,bus=sata,target.dev=sda,address.type=drive,address.controller=0,address.bus=0,address.target=0,address.unit=0,size=8 --os-type generic --network bridge=br0 --graphics vnc,listen=0.0.0.0,port=5903 --noautoconsole --import`

**Comment by fbelavenuto** [comment]
Please try configure USB emulation to USB2

**Comment by tiagogbarbosa** [comment]
v10a:

USB2 wont pass "Welcome to GRUB"
USB1 To slow to boot (+10m) and error too
USB3 Format error
![image](https://user-images.githubusercontent.com/8936001/212183079-b9f05024-ec3d-4592-b7df-6b4b0012a03c.png)


v11:
USB2 - Frozen
![image](https://user-images.githubusercontent.com/8936001/212184001-1a144b18-628f-4ca0-9f2f-ab302dfdec60.png)
USB3 - Format error
![image](https://user-images.githubusercontent.com/8936001/212184502-7dc83281-c04b-4d97-a8a2-4a539b2c14f8.png)
USB1 - Format error
![image](https://user-images.githubusercontent.com/8936001/212185728-d4cd2cb2-9391-4240-833a-c864ab52557f.png)
![image](https://user-images.githubusercontent.com/8936001/212185829-1b345697-5d7c-4f11-9823-f890751306a1.png)

Any log i can provide to you?
Running out of ideas here :(

**Comment by fbelavenuto** [comment]
I see now, increase the size of data disk, must be at least 50GB

**Comment by tiagogbarbosa** [comment]
Ty very much! WORKING

Obrigado mesmo!
