### ISSUE TITLE
About adding the ethtool command to arpl

### ISSUE THREAD

**Issue by chdeast** [fbelavenuto/arpl#469]
Hi, can you add the ethtool command to arpl to check the network card status. thank. (Sorry for the software translation)
![222](https://user-images.githubusercontent.com/87355575/210480170-4cb086d8-b2e3-4866-bd35-260e4e3e64d0.png)

**Comment by fbelavenuto** [comment]
Please update ARPL, reboot, update modules, addons and lkm, rebuild the loader and test it.

**Comment by chdeast** [comment]
After updating ARPL, you can use the ethtool command normally. Thank you very much.

**Comment by chdeast** [comment]
I can use the ethtool command normally after updating ARPL. Thank you very much.
