### ISSUE TITLE
About updating the igc driver version

### ISSUE THREAD

**Issue by LookThePhone** [fbelavenuto/arpl#470]
Hi there. When I checked the version of the igc driver (for apollolake), I found that the driver with arpl was not the latest version (the MD5 check code was different from the latest version) and there was no change after selecting the updated driver. The current igc version within arpl can cause memory leaks. Please update the igc driver.

**Comment by LookThePhone** [comment]
Here is the link: https://github.com/jim3ma/synology-igc/

**Comment by AuxXxilium** [comment]
Driver ist still at version 1.3.1 but recompiled on his own system. so the hash are different.

**Comment by LookThePhone** [comment]
> 驱动程序仍然是1.3.1版本，但在他自己的系统上重新编译。所以哈希是不同的。
> 
> 以下是链接：[Fbelavenuto/ARPL-modules@eace544](https://github.com/fbelavenuto/arpl-modules/commit/eace544fdde6287252918fc5888d44c4003594e0)

Thanks for your reply. But when I manually replace the igc driver in the boot disk with the latest version, I did solve the memory leak problem, while not replacing would cause memory leak, which confused me.

**Comment by AuxXxilium** [comment]
you are right, he added the latest version but this is still different from igc 1.3.1

**Comment by fbelavenuto** [comment]
Hi, I've updated from @jim3ma latest release, please update the modules, rebuild the loader and test it.

**Comment by fbelavenuto** [comment]
Please update ARPL, reboot, update modules, addons and lkm, rebuild the loader and test it.

**Comment by fbelavenuto** [comment]
If issue persist, please reopen
