### ISSUE TITLE
32bit efi cannot boot

### ISSUE THREAD

**Issue by tinysun** [fbelavenuto/arpl#474]
same atom dev are using 64bit cpu but 32bit efi. can you add the booti32.efi in boot file?

**Comment by fbelavenuto** [comment]
Please try with this image:
https://github.com/fbelavenuto/arpl/actions/runs/3848427114

**Comment by tinysun** [comment]
thanks you files.
but the efi is not boot... like
_________________
error: can't find command 'echo'
error: can't find command 'Linux
error: can't find command echo' 
error: can't find command 'initra'
error: can't find command'echo"
Press any key to continue...
_________________

maybe the grub is not include same command like echo linux initra etc.

**Comment by fbelavenuto** [comment]
Ops, sorry, something wrong! Please wait a little more to find this bug.

**Comment by tinysun** [comment]
thanks. waiting....

**Comment by tinysun** [comment]
https://github.com/jfwells/linux-asus-t100ta/blob/master/boot/bootia32.efi
this efi can help samething?

**Comment by fbelavenuto** [comment]
When artifacts are ready, test it:
https://github.com/fbelavenuto/arpl/actions/runs/3887064202

**Comment by tinysun** [comment]
I‘m testing it in this week.
my dev is MS-CH01FV2 stick pc
Atom x5-Z8350
Intel HD Graphics 400
mem 2GB
32GB eMMC
USB 3.0x1、USB 2.0x1、microSDx1
wifi/bt qca61x4

**Comment by tinysun** [comment]
I cannot boot it. it stop at grub>
I my try set "linux /zImage-dsm".
but it not include in img?

**Comment by fbelavenuto** [comment]
Please update ARPL, reboot, update modules, addons and lkm, rebuild the loader and test it.

**Comment by tinysun** [comment]
thanks for your work. it can boot my dev.
I want dd it to emmc.and use usb disk for system,if any idea,please tell me. 
thanks very much.

**Comment by fbelavenuto** [comment]
I found just now a bug in the update system! Re-burning from last image works. Thanks.
