### ISSUE TITLE
I have basically studied and found the following laws

### ISSUE THREAD

**Issue by laotuoyuan1** [fbelavenuto/arpl#487]
I have basically studied and found the following laws
1. If you use the sata interface to connect the hard disk, you can use the dt mode. There is no limit on the number of hard disks
2. If the array card is used to connect the hard disk, the dt mode cannot be recognized, and the hard disk cannot be found. The number of hard disks is limited to 26
3. After the boot compilation is completed and the entry is successfully started, if the network card is added, there is no problem.
4. If the network card is reduced, it will lead to failure to boot. At this time, you need to remove all hard disks, restart, insert the hard disk of volume 1, and reinstall it, but you will lose all data.
Article 4 I don't know whether it is the problem of synology or the problem of guidance. Please pay attention

我已经基本研究清楚，发现以下规律
1，如果使用sata接口连接硬盘，可以使用dt模式。硬盘数量没有限制
2，如果使用阵列卡连接硬盘，dt模式无法识别，会找不到硬盘，硬盘数量限制26个
3，引导编译完成并成功启动进入后，如果增加网卡，没有问题。
4，如果减少网卡，会导致无法引导。此时，需要移除所有硬盘，重启，然后插入卷1的硬盘，重新安装才可以解决，但是会丢失所有数据。

第4条不知道是群晖的问题还是引导的问题，请关注!

**Comment by icekingcy** [comment]
What is dt mode?

**Comment by laotuoyuan1** [comment]
选择型号的时候后缀是DT的就是



---- Replied Message ----
| From | ***@***.***> |
| Date | 02/10/2023 13:59 |
| To | ***@***.***> |
| Cc | ***@***.***>、State ***@***.***> |
| Subject | Re: [fbelavenuto/arpl] I have basically studied and found the following laws (Issue #487) |

What is dt mode?
