### ISSUE TITLE
Bug Text ? on Boot 

### ISSUE THREAD

**Issue by sumonchai** [fbelavenuto/arpl#488]
After Update To v1.0-beta10a
![image](https://user-images.githubusercontent.com/5920739/211757119-f7c0b0ff-4616-4af9-9ad7-31768bf7b3df.png)

**Comment by dtech77pl** [comment]
Booting screen
![arpl](https://user-images.githubusercontent.com/122393484/211759650-6cec605e-b7fb-46d4-9368-14d4811e1c39.jpg)

**Comment by fbelavenuto** [comment]
Please test with this image:
https://github.com/fbelavenuto/arpl/actions/runs/3892978213
(Please wait for artifacts to be generated)

**Comment by dtech77pl** [comment]
It's better with this new 10b image. Now all artifacts are gone, and the menu it's visible without any problems. 
Still during the boot Linux boot progress is visible,

**Comment by fbelavenuto** [comment]
Closing, issue solved
