### ISSUE TITLE
DSM system cannot display the second hard disk port of JMB585 controller

### ISSUE THREAD

**Issue by MIX-Weng** [fbelavenuto/arpl#493]
I directly pass through the JMB585 sata controller under EXSI. The second harddisk port can be seen in the sata port in the aprl boot. However, after entering the DSM system, the hard disk of the second port cannot be identified by plugging. If I pass through the jmb585 to Windows, all hard disks can be identified correctly. Is it because the DSM system does not drive the JMB585 controller correctly

**Comment by fbelavenuto** [comment]
try to add a synoinfo entry "SataPortMap" with value "1"
More information:
https://xpenology.com/forum/topic/52094-how-to-config-sataportmap-sata_remap-and-diskidxmap/

**Comment by fbelavenuto** [comment]
#492 duplicated
