### ISSUE TITLE
Issue with more than 2 cores in VM

### ISSUE THREAD

**Issue by AuxXxilium** [fbelavenuto/arpl#507]
Issue is related to broadwellnk systems, all other configs working fine.

Issue comes if i add more than 2 cpu cores to esxi vm. with only 2 cores, everything is working, with 4 this issue comes and dsm won't boot.

with old beta9 the issue is gone. all later versions look like to have this bug.

[   48.090228] NMI watchdog: BUG: soft lockup - CPU#1 stuck for 41s! [migration/1:12]
[   48.091622] Modules linked in: vmxnet3(OE) vmw_pvscsi(OE) vmw_vmci(E) processor button(E) xhci_pci xhci_hcd uhci_hcd ehci_pci ehci_hcd usbcore usb_common mv14xx(O) redpill(OE)
[   48.094824] CPU: 1 PID: 12 Comm: migration/1 Tainted: G           OE   4.4.180+ #42962
[   48.096242] Hardware name: VMware, Inc. VMware20,1/440BX Desktop Reference Platform, BIOS VMW201.00V.20192059.B64.2207280713 07/28/2022
[   48.098404] task: ffff88022f9ab300 ti: ffff88022f9c0000 task.ti: ffff88022f9c0000
[   48.099745] RIP: 0010:[<ffffffff810d112c>]  [<ffffffff810d112c>] multi_cpu_stop+0x3c/0xc0
[   48.101238] RSP: 0018:ffff88022f9c3da8  EFLAGS: 00000246
[   48.102196] RAX: 0000000000000000 RBX: 0000000000000001 RCX: 0000000000000000
[   48.103474] RDX: 0000000000000001 RSI: 0000000000000018 RDI: ffffffff818d7800
[   48.104751] RBP: ffff88022f9c3dd0 R08: ffff88022f9c0000 R09: 0000000000000000
[   48.106029] R10: 0000000000000400 R11: 00000000000003ee R12: ffff88023b023e18
[   48.107306] R13: 0000000000000286 R14: ffff88023b023e3c R15: ffff88023b023d00
[   48.108584] FS:  0000000000000000(0000) GS:ffff88023dc80000(0000) knlGS:0000000000000000
[   48.110028] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   48.111061] CR2: 00007f366f5f8c90 CR3: 000000023b02f000 CR4: 00000000001606f0
[   48.112363] Stack:
[   48.112743]  ffff88023dc92880 ffff88023b023e18 ffffffff810d10f0 ffff88023dc92890
[   48.114181]  ffff88023b023d98 ffff88022f9c3e90 ffffffff810d137c ffff88023dc92888
[   48.115618]  ffff88022f9ab300 ffff88022f9c3e08 ffffffff81072f83 ffff880239af0000
[   48.117059] Call Trace:
[   48.117519]  [<ffffffff810d10f0>] ? cpu_stop_init_done+0x30/0x30
[   48.118605]  [<ffffffff810d137c>] cpu_stopper_thread+0x7c/0x110
[   48.119675]  [<ffffffff81072f83>] ? update_rq_clock.part.83+0x13/0x30
[   48.120838]  [<ffffffff81562ffd>] ? __schedule+0x2dd/0x7c0
[   48.121829]  [<ffffffff810705a0>] ? sort_range+0x20/0x20
[   48.122789]  [<ffffffff81070668>] smpboot_thread_fn+0xc8/0x170
[   48.123842]  [<ffffffff8106d9e3>] kthread+0xd3/0xf0
[   48.124727]  [<ffffffff8106d910>] ? kthread_worker_fn+0x160/0x160
[   48.125827]  [<ffffffff8156712f>] ret_from_fork+0x3f/0x80
[   48.126804]  [<ffffffff8106d910>] ? kthread_worker_fn+0x160/0x160
[   48.127901] Code: 8b 1d 09 c0 f3 7e 9c 41 5d 48 8b 47 18 48 85 c0 74 76 89 db 48 0f a3 18 19 db 85 db 41 0f 95 c7 4d 8d 74 24 24 31 c0 31 d2 f3 90 <41> 8b 5c 24 20 39 d3 74 f5 83 fb 02 74 4c 83 fb 03 75 13 45 84 
[   48.133314] Sending NMI to other CPUs:
[   48.134063] NMI backtrace for cpu 2
[   48.134733] CPU: 2 PID: 17 Comm: migration/2 Tainted: G           OE   4.4.180+ #42962
[   48.136156] Hardware name: VMware, Inc. VMware20,1/440BX Desktop Reference Platform, BIOS VMW201.00V.20192059.B64.2207280713 07/28/2022
[   48.138333] task: ffff88022f9af2c0 ti: ffff88022f9e8000 task.ti: ffff88022f9e8000
[   48.139689] RIP: 0010:[<ffffffff810d112c>]  [<ffffffff810d112c>] multi_cpu_stop+0x3c/0xc0
[   48.141156] RSP: 0018:ffff88022f9ebda8  EFLAGS: 00000246
[   48.142119] RAX: 0000000000000000 RBX: 0000000000000001 RCX: 0000000000000000
[   48.143402] RDX: 0000000000000001 RSI: 0000000000000018 RDI: ffffffff818d7800
[   48.144685] RBP: ffff88022f9ebdd0 R08: ffff88022f9e8000 R09: 0000000000003c00
[   48.145968] R10: 0000000000000000 R11: 0000000000000000 R12: ffff88023b023e18
[   48.147252] R13: 0000000000000286 R14: ffff88023b023e3c R15: ffff88023b023d00
[   48.148537] FS:  0000000000000000(0000) GS:ffff88023dd00000(0000) knlGS:0000000000000000
[   48.149991] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   48.151028] CR2: 00007ffe30b1ee40 CR3: 000000022c182000 CR4: 00000000001606f0
[   48.152313] Stack:
[   48.152694]  ffff88023dd12880 ffff88023b023e18 ffffffff810d10f0 ffff88023dd12890
[   48.154024]  ffff88023b023d98 ffff88022f9ebe90 ffffffff810d137c ffff88023dd12888
[   48.155356]  ffff88022f9af2c0 ffff88022f9ebe08 ffffffff81072f83 ffff88023b040700
[   48.156689] Call Trace:
[   48.157147]  [<ffffffff810d10f0>] ? cpu_stop_init_done+0x30/0x30
[   48.158234]  [<ffffffff810d137c>] cpu_stopper_thread+0x7c/0x110
[   48.159302]  [<ffffffff81072f83>] ? update_rq_clock.part.83+0x13/0x30
[   48.160466]  [<ffffffff81562ffd>] ? __schedule+0x2dd/0x7c0
[   48.161460]  [<ffffffff810705a0>] ? sort_range+0x20/0x20
[   48.162424]  [<ffffffff81070668>] smpboot_thread_fn+0xc8/0x170
[   48.163480]  [<ffffffff8106d9e3>] kthread+0xd3/0xf0
[   48.164367]  [<ffffffff8106d910>] ? kthread_worker_fn+0x160/0x160
[   48.165468]  [<ffffffff8156712f>] ret_from_fork+0x3f/0x80
[   48.166454]  [<ffffffff8106d910>] ? kthread_worker_fn+0x160/0x160
[   48.167557] Code: 8b 1d 09 c0 f3 7e 9c 41 5d 48 8b 47 18 48 85 c0 74 76 89 db 48 0f a3 18 19 db 85 db 41 0f 95 c7 4d 8d 74 24 24 31 c0 31 d2 f3 90 <41> 8b 5c 24 20 39 d3 74 f5 83 fb 02 74 4c 83 fb 03 75 13 45 84 
[   48.170916] NMI backtrace for cpu 0
[   48.171571] CPU: 0 PID: 4506 Comm: scsi_id Tainted: G           OE   4.4.180+ #42962
[   48.172957] Hardware name: VMware, Inc. VMware20,1/440BX Desktop Reference Platform, BIOS VMW201.00V.20192059.B64.2207280713 07/28/2022
[   48.175121] task: ffff88022fa50cc0 ti: ffff88022c18c000 task.ti: ffff88022c18c000
[   48.176463] RIP: 0010:[<ffffffff8108f1e2>]  [<ffffffff8108f1e2>] queued_spin_lock_slowpath+0xe2/0x150
[   48.178108] RSP: 0018:ffff88022c18fdf0  EFLAGS: 00000202
[   48.179067] RAX: 0000000000100001 RBX: ffff88022f429a40 RCX: 0000000000040000
[   48.180346] RDX: ffff88023dc16e00 RSI: 0000000000000000 RDI: ffffffffa001f6a0
[   48.181624] RBP: ffff88022c18fdf0 R08: 0000000000000001 R09: 0000000000002285
[   48.182903] R10: fffffffffffff124 R11: 0000000000000206 R12: 000000000002005d
[   48.184182] R13: 0000000000002285 R14: 00007ffcd3f92940 R15: 00007ffcd3f92940
[   48.185461] FS:  00007f3ac7ab9c00(0000) GS:ffff88023dc00000(0000) knlGS:0000000000000000
[   48.186909] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   48.187944] CR2: 00007f3ac70dda30 CR3: 000000023bdbe000 CR4: 00000000001606f0
[   48.189224] Stack:
[   48.189604]  ffff88022c18fe00 ffffffff81566a7c ffff88022c18fe30 ffffffffa0002293
[   48.190929]  00000000ffffffe7 00007ffcd3f92940 00007ffcd3f92940 ffff88022f429a40
[   48.192254]  ffff88022c18fe80 ffffffff812c91ca 0000000063c426e8 ffffea0002e20f40
[   48.193586] Call Trace:
[   48.194044]  [<ffffffff81566a7c>] _raw_spin_lock+0x1c/0x20
[   48.195037]  [<ffffffffa0002293>] sd_ioctl_canary+0x23/0x60 [redpill]
[   48.196199]  [<ffffffff812c91ca>] blkdev_ioctl+0x30a/0x9d0
[   48.197191]  [<ffffffff811c3af8>] block_ioctl+0x38/0x40
[   48.198137]  [<ffffffff8119be9a>] do_vfs_ioctl+0x7ea/0xa80
[   48.199130]  [<ffffffff8119c1d1>] SyS_ioctl+0xa1/0xb0
[   48.200047]  [<ffffffff81566d8a>] entry_SYSCALL_64_fastpath+0x1e/0x8e
[   48.201208] Code: 81 48 89 10 8b 42 08 85 c0 75 1e f3 90 8b 42 08 85 c0 74 f7 eb 13 f3 90 8b 37 81 fe 00 01 00 00 74 f4 e9 32 ff ff ff f3 90 8b 07 <66> 85 c0 75 f7 39 c1 75 0f 89 c8 be 01 00 00 00 f0 0f b1 37 39 
[   48.204567] NMI backtrace for cpu 3
[   48.205247] CPU: 3 PID: 4508 Comm: scsi_id Tainted: G           OE   4.4.180+ #42962
[   48.206719] Hardware name: VMware, Inc. VMware20,1/440BX Desktop Reference Platform, BIOS VMW201.00V.20192059.B64.2207280713 07/28/2022
[   48.208963] task: ffff88023b076600 ti: ffff880239aa4000 task.ti: ffff880239aa4000
[   48.210358] RIP: 0010:[<ffffffff8108f1c4>]  [<ffffffff8108f1c4>] queued_spin_lock_slowpath+0xc4/0x150
[   48.212040] RSP: 0018:ffff880239aa7df0  EFLAGS: 00000246
[   48.213030] RAX: 0000000000000000 RBX: ffff88022eeada40 RCX: 0000000000100000
[   48.214378] RDX: ffff88023dd96e00 RSI: 0000000000000000 RDI: ffffffffa001f6a0
[   48.215712] RBP: ffff880239aa7df0 R08: 0000000000000001 R09: 0000000000002285
[   48.217041] R10: fffffffffffff124 R11: 0000000000000206 R12: 000000000002005d
[   48.218385] R13: 0000000000002285 R14: 00007ffd77a36010 R15: 00007ffd77a36010
[   48.219694] FS:  00007f6fd7e62c00(0000) GS:ffff88023dd80000(0000) knlGS:0000000000000000
[   48.221206] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   48.222271] CR2: 00007f6fd747dfd0 CR3: 00000000b902a000 CR4: 00000000001606f0
[   48.223579] Stack:
[   48.223973]  ffff880239aa7e00 ffffffff81566a7c ffff880239aa7e30 ffffffffa0002293
[   48.225335]  00000000ffffffe7 00007ffd77a36010 00007ffd77a36010 ffff88022eeada40
[   48.226695]  ffff880239aa7e80 ffffffff812c91ca 0000000063c426e8 ffffea0002e23540
[   48.228062] Call Trace:
[   48.228546]  [<ffffffff81566a7c>] _raw_spin_lock+0x1c/0x20
[   48.229605]  [<ffffffffa0002293>] sd_ioctl_canary+0x23/0x60 [redpill]
[   48.230802]  [<ffffffff812c91ca>] blkdev_ioctl+0x30a/0x9d0
[   48.231841]  [<ffffffff811c3af8>] block_ioctl+0x38/0x40
[   48.232840]  [<ffffffff8119be9a>] do_vfs_ioctl+0x7ea/0xa80
[   48.233863]  [<ffffffff8119c1d1>] SyS_ioctl+0xa1/0xb0
[   48.234810]  [<ffffffff81566d8a>] entry_SYSCALL_64_fastpath+0x1e/0x8e
[   48.236052] Code: 46 c1 ee 12 83 e0 03 83 ee 01 48 c1 e0 04 48 63 f6 48 05 00 6e 01 00 48 03 04 f5 20 73 8d 81 48 89 10 8b 42 08 85 c0 75 1e f3 90 <8b> 42 08 85 c0 74 f7 eb 13 f3 90 8b 37 81 fe 00 01 00 00 74 f4 
[   96.111293] NMI watchdog: BUG: soft lockup - CPU#2 stuck for 41s! [migration/2:17]
[   96.112697] Modules linked in: vmxnet3(OE) vmw_pvscsi(OE) vmw_vmci(E) processor button(E) xhci_pci xhci_hcd uhci_hcd ehci_pci ehci_hcd usbcore usb_common mv14xx(O) redpill(OE)
[   96.115925] CPU: 2 PID: 17 Comm: migration/2 Tainted: G           OEL  4.4.180+ #42962
[   96.117355] Hardware name: VMware, Inc. VMware20,1/440BX Desktop Reference Platform, BIOS VMW201.00V.20192059.B64.2207280713 07/28/2022
[   96.119535] task: ffff88022f9af2c0 ti: ffff88022f9e8000 task.ti: ffff88022f9e8000
[   96.120884] RIP: 0010:[<ffffffff810d112c>]  [<ffffffff810d112c>] multi_cpu_stop+0x3c/0xc0
[   96.122393] RSP: 0018:ffff88022f9ebda8  EFLAGS: 00000246
[   96.123358] RAX: 0000000000000000 RBX: 0000000000000001 RCX: 0000000000000000
[   96.124644] RDX: 0000000000000001 RSI: 0000000000000018 RDI: ffffffff818d7800
[   96.125927] RBP: ffff88022f9ebdd0 R08: ffff88022f9e8000 R09: 0000000000003c00
[   96.127212] R10: 0000000000000000 R11: 0000000000000000 R12: ffff88023b023e18
[   96.128506] R13: 0000000000000286 R14: ffff88023b023e3c R15: ffff88023b023d00
[   96.129790] FS:  0000000000000000(0000) GS:ffff88023dd00000(0000) knlGS:0000000000000000
[   96.131241] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   96.132285] CR2: 00007ffe30b1ee40 CR3: 000000022c182000 CR4: 00000000001606f0
[   96.133588] Stack:
[   96.133970]  ffff88023dd12880 ffff88023b023e18 ffffffff810d10f0 ffff88023dd12890
[   96.135415]  ffff88023b023d98 ffff88022f9ebe90 ffffffff810d137c ffff88023dd12888
[   96.136857]  ffff88022f9af2c0 ffff88022f9ebe08 ffffffff81072f83 ffff88023b040700
[   96.138302] Call Trace:
[   96.138763]  [<ffffffff810d10f0>] ? cpu_stop_init_done+0x30/0x30
[   96.139852]  [<ffffffff810d137c>] cpu_stopper_thread+0x7c/0x110
[   96.140923]  [<ffffffff81072f83>] ? update_rq_clock.part.83+0x13/0x30
[   96.142109]  [<ffffffff81562ffd>] ? __schedule+0x2dd/0x7c0
[   96.143104]  [<ffffffff810705a0>] ? sort_range+0x20/0x20
[   96.144067]  [<ffffffff81070668>] smpboot_thread_fn+0xc8/0x170
[   96.145123]  [<ffffffff8106d9e3>] kthread+0xd3/0xf0
[   96.146010]  [<ffffffff8106d910>] ? kthread_worker_fn+0x160/0x160
[   96.147115]  [<ffffffff8156712f>] ret_from_fork+0x3f/0x80
[   96.148092]  [<ffffffff8106d910>] ? kthread_worker_fn+0x160/0x160
[   96.149191] Code: 8b 1d 09 c0 f3 7e 9c 41 5d 48 8b 47 18 48 85 c0 74 76 89 db 48 0f a3 18 19 db 85 db 41 0f 95 c7 4d 8d 74 24 24 31 c0 31 d2 f3 90 <41> 8b 5c 24 20 39 d3 74 f5 83 fb 02 74 4c 83 fb 03 75 13 45 84

**Comment by fbelavenuto** [comment]
Please, test with direct boot enabled
