### ISSUE TITLE
How to use SATAMAP?

### ISSUE THREAD

**Issue by TineUser** [fbelavenuto/arpl#508]
I want to use arpl with a LSI 2308 SAS HBA controller on a virtual machine (VMware ESXi 8.0). The HBA controller is in IT mode and is directly attached to the VM (passthrough).

Because of 2 SATA VMDKs I see 60 SATA ports in arpl but not the HBA controller. In TCRP (TinyCore Redpill) I can change this by setting SataPortMap=1 and DiskIdxMap=1000. Then I see the drives attached to the HBA controller. This is OK but the update of DSM and TCRP is very tricky and not really reliable. With a HA cluster of DSM you don't have enough time to do the update of a cluster node before the passive node is deleted from the cluster by the active node and the update is stopped. It took me hours to get the HA cluster up and running again! And it takes hours to synchronize the data between the nodes for the first time.

Updating DSM and arpl is much easier! I have a little test environment with a DSM cluster but without SAS HBA controller. The update works smoothly. So it would be nice to use arpl and the SATAMAP parameters. Is this possible and how does it work? Will this be saved when updating DSM and / or arpl?

**Comment by fbelavenuto** [comment]
Try:
SataPortMap=118
DiskIdxMap=080900

**Comment by fbelavenuto** [comment]
In the CMDLINE:
https://github.com/fbelavenuto/arpl/wiki/Add-an-cmdline-synoinfo-entry

**Comment by TineUser** [comment]
Thank you. I will try this when a new DSM update will be available. I have now a running DSM cluster with TCRP again and don't want to get it broken one more time for now.

**Comment by fbelavenuto** [comment]
Okay, the important thing is that you can use it.

**Comment by TineUser** [comment]
Or do you know a good way to switch a running DSM cluster node from TCRP to arpl without losing the settings and the cluster membership? Then I will try it before an upcoming update of DSM.

**Comment by fbelavenuto** [comment]
> Or do you know a good way to switch a running DSM cluster node from TCRP to arpl without losing the settings and the cluster membership? Then I will try it before an upcoming update of DSM.

I don't know if it's possible and if so, how to do it!

**Comment by aniel300** [comment]
> Try: SataPortMap=118 DiskIdxMap=080900

i tried this but it starts from 2 and not 1, i also read this but i cant find how to do it

https://xpenology.com/forum/topic/58046-cant-find-the-right-diskidxmap-sataportmap-for-pass-throughed-sata-controller/
https://xpenology.com/forum/topic/58464-beta-about-redpill-sataportmap-and-diskidxmap/
https://gugucomputing.wordpress.com/2018/11/11/experiment-on-sata_args-in-grub-cfg/

**Comment by TineUser** [comment]
After one more fail with a DSM update (Update 5) and TinyCore Redpill on a clustered XPEnology I decided to give arpl a try. But with the cmdline parameters

SataPortMap=118
DiskIdxMap=080900

the system won't boot. When not setting these parameters the system boots but doesn't show the disks attached to the LSI 2308 SAS HBA controller on a virtual machine (VMware ESXi 8.0). The HBA controller is in IT mode and is directly attached to the VM (passthrough).

Because of 2 SATA VMDKs I see 60 SATA ports in arpl but not the HBA controller. In TCRP (TinyCore Redpill) I can change this by setting SataPortMap=1 and DiskIdxMap=1000. Then I see the drives attached to the HBA controller. But these parameter do not work in arpl.
