### ISSUE TITLE
Virtual Machine Manager cluster is not initialized

### ISSUE THREAD

**Issue by mewallkit** [fbelavenuto/arpl#51]
used different versions
of synology_bromolow_3615xs U3 42661
synology_broadwell_3617xs U3 42661
when initializing the cluster, the application crashes, with new attempts, the message cannot initiate the cluster
tell me, who has a similar problem?

**Comment by fbelavenuto** [comment]
Please, what is "Virtual Machine Manager cluster", proxmox cluster?

**Comment by vbap** [comment]
VMM is the Synology app that turns your NAS into a hypervisor, so you can run VMs on your synology.
I get the same issue - I believe it's because of the blocking of the syno servers ("example.com") in synoinfo. 
Once you update arpl to allow us to choose whether to block these, then I think VMM will work.

**Comment by fbelavenuto** [comment]
Ok, now I understood!

Please test with this image:

https://github.com/fbelavenuto/arpl/suites/7466951834/artifacts/305894996

After select model and build, go to synoinfo menu and delete all entries, this way the synoinfo.conf will stay intact.

**Comment by mewallkit** [comment]
> Ok, now I understood!
> 
> Please test with this image:
> 
> https://github.com/fbelavenuto/arpl/suites/7466951834/artifacts/305894996
> 
> After select model and build, go to synoinfo menu and delete all entries, this way the synoinfo.conf will stay intact.
synoinfo menu delete selected *
no changes =(

![image](https://user-images.githubusercontent.com/28947729/180514066-3c5afc7c-9d09-4ff1-a994-fc342c4ee9b0.png)
![image](https://user-images.githubusercontent.com/28947729/180514086-5a57ec01-01c4-4765-932c-2c24710bf5d6.png)
![image](https://user-images.githubusercontent.com/28947729/180514097-5f8255df-25b8-45f0-bd1b-d84e15f1aaea.png)

**Comment by vbap** [comment]
I am still testing (network issues to resolve first) but I notice Grub has a menu "Force Re-install DSM". Is this working yet?

**Comment by mewallkit** [comment]
> I am still testing (network issues to resolve first) but I notice Grub has a menu "Force Re-install DSM". Is this working yet?

I tried it, it worked

**Comment by mewallkit** [comment]
> I am still testing (network issues to resolve first) but I notice Grub has a menu "Force Re-install DSM". Is this working yet?

you have completed testing, you have managed to solve the cluster problem of the virtual machine manager ?

**Comment by tonyk520** [comment]
Trying to change the ‘sn'’ and 'mac' to real one can solve this problem

**Comment by sashakozlov86** [comment]
I have the same problem on a DVA1622 build.  Were you able to solve it somehow?

**Comment by sashakozlov86** [comment]
Hello!  Adding the lines to cmd edit helped me: 1) the "mac1" parameter with the value of the MAC address of the network card (without a colon) and 2) the "netif_num" parameter with the value "1"

**Comment by fbelavenuto** [comment]
Thanks for the discover!
