### ISSUE TITLE
MSI B460M + I3 10305T  boot error 

### ISSUE THREAD

**Issue by tx5866** [fbelavenuto/arpl#511]

**Comment by tx5866** [comment]
MSI B460M + I3 10305T boot error
![w5757](https://user-images.githubusercontent.com/84910032/212932957-e118427f-7f48-40cf-9fe9-243a9b6f2393.jpg)

**Comment by JonathanNet** [comment]
I got the same problem, but I found out if Secure Boot is Enabled in bios, then you get this error.
