### ISSUE TITLE
Solved: Acer Easystore H341 - Stuck in Boot at Loading initramfs....

### ISSUE THREAD

**Issue by cherberg** [fbelavenuto/arpl#512]
Solved: seems like the legacy VGA does not display what comes next. I was able to reach the server via SSH and configure the next rest.

Sorry to have bothered you :-)

Dear friends,

I am trying to revive and old server of mine but I cannot get past "Loading initramfs..." which shows for a few seconds, then screen turns off and nothing happens. Any help to overcome this is highly appreciated.

![image](https://user-images.githubusercontent.com/8701752/213005014-1341ff41-111b-42b1-b1be-a1750c3bb01f.png)

**Comment by MartinKuhl** [comment]
I am using an Acer H341 too, and not facing any issues. You need additional help?

**Comment by fbelavenuto** [comment]
I've added an option in grub to boot in text mode, this way the issue do not appears.
