### ISSUE TITLE
More than two hard disks cannot start boot

### ISSUE THREAD

**Issue by yanyisio** [fbelavenuto/arpl#515]
Beta11a has the problem that more than two hard disks cannot boot. I am using beta3 now, but this version has 1225-v memory problems, so I always restart. Can you help me? thank you!

**Comment by fbelavenuto** [comment]
Hi, please use the beta11a and update modules

**Comment by yanyisio** [comment]
Hi ,i try update modules, but the problem is still on.
The network can be pinged on for about three seconds before it is disconnected, have four hard disks.
![1111111](https://user-images.githubusercontent.com/122669087/213348480-050fe1f7-7148-459a-bc73-2f7d76fe68bc.jpg)
![2222222](https://user-images.githubusercontent.com/122669087/213348701-b8b28a9c-97a4-432d-8f10-c17ac781e58d.jpg)

**Comment by fbelavenuto** [comment]
About bug of 2 disks, change lkm from dev to prod (advanced menu)

**Comment by fbelavenuto** [comment]
#449
