### ISSUE TITLE
[beta12 issue] symbol 'grub_disk_native_sectors' not found error

### ISSUE THREAD

**Issue by azchoi** [fbelavenuto/arpl#521]
After update beta 11a to beta12 via update menu,
I meet 'GRUB Loading Error' like below picture.
How can I fix this issue?

![123](https://user-images.githubusercontent.com/111041447/213592689-0401611f-6391-4fc7-a8f1-c39f0e33d4d5.jpg)

**Comment by fbelavenuto** [comment]
Try to reburn your USB drive.

If you already have a DSM installed, use the "try to recover an installed DSM" option within the "advanced" menu

**Comment by MartinKuhl** [comment]
I have this issue in my VM too. Is the rebuilt of the loader the only way?

**Comment by fbelavenuto** [comment]
unfortunately!  If you already have DSM installed, you can use the "recover DSM..." option in the "advanced" menu.  This recovery will not bring the settings like serial, mac, addons, etc.  You can write it down to get it right later.

**Comment by MartinKuhl** [comment]
Is that issue fixed in Beta13 so that we can update without reburn the loader?

**Comment by fbelavenuto** [comment]
has not been fixed!

**Comment by azchoi** [comment]
> I have this issue in my VM too. Is the rebuilt of the loader the only way?
> <img alt="image" width="735" src="https://user-images.githubusercontent.com/55736453/213860529-5187c9da-b7ea-48be-98fd-fa44e6cd6e41.png">

Are you still using lagacy bios??? fbelavenuto said me it needs UEFI bios. And I tested it again, UEFI was OK.

**Comment by MartinKuhl** [comment]
So I will wait with updating my real non-UEFI systems until this issue has been fixed.

**Comment by MartinKuhl** [comment]
with beta11 DSM was able to read my SCSI data disk. Now with beta12 and 13 this is not the case anymore. 
When I switch the controller to SATA I get every 10 seconds the error message, that the data disk has been re-identified

<img width="664" alt="image" src="https://user-images.githubusercontent.com/55736453/213927856-7747b726-0847-45dc-b1bb-fdbc96d7356b.png">

**Comment by fbelavenuto** [comment]
> with beta11 DSM was able to read my SCSI data disk. Now with beta12 and 13 this is not the case anymore.
> When I switch the controller to SATA I get every 10 seconds the error message, that the data disk has been re-identified.

What is your SCSI model?

**Comment by MartinKuhl** [comment]
It should be this one:
```
00:0f.0 SCSI storage controller [0100]: Broadcom / LSI 53c1030 PCI-X Fusion-MPT Dual Ultra320 SCSI [1000:0030]
        Subsystem: Parallels, Inc. 53c1030 PCI-X Fusion-MPT Dual Ultra320 SCSI [1ab8:0400]
        Kernel driver in use: mptspi
        Kernel modules: mptspi
```

**lspci -nnk:**
```
00:00.0 Host bridge [0600]: Intel Corporation 82P965/G965 Memory Controller Hub [8086:29a0] (rev 02)
        Subsystem: Parallels, Inc. 82P965/G965 Memory Controller Hub [1ab8:0400]
00:01.0 PCI bridge [0604]: Intel Corporation 82G35 Express PCI Express Root Port [8086:2981] (rev 02)
        Kernel driver in use: pcieport
00:03.0 Unassigned class [ff00]: Parallels, Inc. Virtual Machine Communication Interface [1ab8:4000]
        Subsystem: Parallels, Inc. Virtual Machine Communication Interface [1ab8:0400]
00:05.0 Ethernet controller [0200]: Intel Corporation 82545EM Gigabit Ethernet Controller (Copper) [8086:100f]
        Subsystem: Parallels, Inc. 82545EM Gigabit Ethernet Controller (Copper) [1ab8:0400]
        Kernel driver in use: e1000
        Kernel modules: e1000
00:0a.0 PCI bridge [0604]: Digital Equipment Corporation DECchip 21150 [1011:0022]
00:0e.0 RAM memory [0500]: Red Hat, Inc. Virtio memory balloon [1af4:1002]
        Subsystem: Parallels, Inc. Virtio memory balloon [1ab8:0005]
        Kernel modules: virtio_pci
00:0f.0 SCSI storage controller [0100]: Broadcom / LSI 53c1030 PCI-X Fusion-MPT Dual Ultra320 SCSI [1000:0030]
        Subsystem: Parallels, Inc. 53c1030 PCI-X Fusion-MPT Dual Ultra320 SCSI [1ab8:0400]
        Kernel driver in use: mptspi
        Kernel modules: mptspi
00:1d.0 USB controller [0c03]: Intel Corporation 82801FB/FBM/FR/FW/FRW (ICH6 Family) USB UHCI #1 [8086:2658] (rev 02)
        Subsystem: Parallels, Inc. 82801FB/FBM/FR/FW/FRW (ICH6 Family) USB UHCI [1ab8:0400]
        Kernel driver in use: uhci_hcd
00:1d.6 USB controller [0c03]: NEC Corporation uPD720200 USB 3.0 Host Controller [1033:0194] (rev 04)
        Subsystem: Parallels, Inc. uPD720200 USB 3.0 Host Controller [1ab8:0400]
        Kernel driver in use: xhci_hcd
00:1d.7 USB controller [0c03]: Intel Corporation 82801FB/FBM/FR/FW/FRW (ICH6 Family) USB2 EHCI Controller [8086:265c] (rev 02)
        Subsystem: Parallels, Inc. 82801FB/FBM/FR/FW/FRW (ICH6 Family) USB2 EHCI Controller [1ab8:0400]
        Kernel driver in use: ehci-pci
00:1e.0 PCI bridge [0604]: Intel Corporation 82801 PCI Bridge [8086:244e] (rev f2)
00:1f.0 ISA bridge [0601]: Intel Corporation 82801HB/HR (ICH8/R) LPC Interface Controller [8086:2810] (rev 02)
        Subsystem: Parallels, Inc. 82801HB/HR (ICH8/R) LPC Interface Controller [1ab8:0400]
00:1f.1 IDE interface [0101]: Intel Corporation 82801BA IDE U100 Controller [8086:244b] (rev 05)
        Subsystem: Parallels, Inc. 82801BA IDE U100 Controller [1ab8:0400]
        Kernel driver in use: ata_piix
00:1f.2 SATA controller [0106]: Intel Corporation 82801HR/HO/HH (ICH8R/DO/DH) 6 port SATA Controller [AHCI mode] [8086:2821] (rev 02)
        Subsystem: Parallels, Inc. 82801HR/HO/HH (ICH8R/DO/DH) 6 port SATA Controller [AHCI mode] [1ab8:0400]
        Kernel driver in use: ahci
00:1f.3 SMBus [0c05]: Intel Corporation 82801H (ICH8 Family) SMBus Controller [8086:283e] (rev 02)
        Subsystem: Parallels, Inc. 82801H (ICH8 Family) SMBus Controller [1ab8:0400]
        Kernel driver in use: i801_smbus
01:00.0 VGA compatible controller [0300]: Red Hat, Inc. Virtio GPU [1af4:1050] (rev 01)
        Subsystem: Parallels, Inc. Virtio GPU [1ab8:0010]
        Kernel driver in use: virtio-pci
        Kernel modules: virtio_pci
```

**Comment by fbelavenuto** [comment]
Plesa, go to loader, update modules, rebuild and test it

**Comment by MartinKuhl** [comment]
@fbelavenuto thanks a lot, now my data disc is recognized when it's connected via SCSI.

**Comment by fbelavenuto** [comment]
Closing

**Comment by MartinKuhl** [comment]
@fbelavenuto 
the main issue of this ticket: grub_disk_native_sectors error message after updating a non-UEFI system is still there.
Or were you able to fix this issue?

**Comment by fbelavenuto** [comment]
> @fbelavenuto the main issue of this ticket: grub_disk_native_sectors error message after updating a non-UEFI system is still there. Or were you able to fix this issue?

To fix is necessary to reburn media (Usb stick or SATADoM).

**Comment by MartinKuhl** [comment]
If a am on a system without this issue (e.g. beta 10) and upgrade to the latest one (beta13) will I facing this issue?

**Comment by MartinKuhl** [comment]
> > @fbelavenuto the main issue of this ticket: grub_disk_native_sectors error message after updating a non-UEFI system is still there. Or were you able to fix this issue?
> 
> To fix is necessary to reburn media (Usb stick or SATADoM).

If a am on a system without this issue (e.g. beta 10) and upgrade to the latest one (beta13) will I facing this issue?

**Comment by fbelavenuto** [comment]
> If a am on a system without this issue (e.g. beta 10) and upgrade to the latest one (beta13) will I facing this issue?

Yes!! If your machine is configured to boot via UEFI, this issue do not happens.

**Comment by MartinKuhl** [comment]
> > If a am on a system without this issue (e.g. beta 10) and upgrade to the latest one (beta13) will I facing this issue?
> 
> Yes!! If your machine is configured to boot via UEFI, this issue do not happens.

Thanks for clarification. My prod system is pre-UEFI so I need to reburn my boot stick.
