### ISSUE TITLE
BIOSTAR A10N-8800E stuck in booting

### ISSUE THREAD

**Issue by sslhk** [fbelavenuto/arpl#522]
I have tried all beta version, still the same problem.
<img width="1348" alt="螢幕截圖 2023-01-20 下午8 46 57" src="https://user-images.githubusercontent.com/29858604/213707674-614da732-f434-494a-85df-4a379939584c.png">

**Comment by fbelavenuto** [comment]
Hello, have you tested the "console" addon?

**Comment by sslhk** [comment]
It is working now, I just chnged the setting "direct loader" to true from flase

**Comment by fbelavenuto** [comment]
Ok, closing
