### ISSUE TITLE
I219-V

### ISSUE THREAD

**Issue by Paulos25** [fbelavenuto/arpl#527]
hello?
I219-V is using the built-in Lan, and there is no problem until the build, but I can't get the IP at the DSM boot stage. I checked and the I219-V built-in Lan does not turn on with the LED off. Why? I saw an article on Xepnology.com with a similar symptom to mine, and the article said that there was an issue that I219-V Lan could not be caught if the RAM was 2GB or more.

**Comment by yanyisio** [comment]
you can see this https://github.com/fbelavenuto/arpl/issues/526

**Comment by yanyisio** [comment]
you can see this maybe https://github.com/fbelavenuto/arpl/issues/526

**Comment by Paulos25** [comment]
> you can see this maybe #526

Thank you. I tested it with what you just told me and it's the same problem. I thought it was an I219-V chipset problem. Thank you.

**Comment by fbelavenuto** [comment]
Please add addon console and rebuild.

**Comment by Paulos25** [comment]
> Please add addon console and rebuild.

Adding a console addon has the same symptoms. So I solved it by only upgrading to beta13 after building with beta3. Thank you for answer.

**Comment by fbelavenuto** [comment]
Change LKM from DEV to PROD (advanced menu), rebuild and test
