### ISSUE TITLE
DSM920+ shows 4GB memory only

### ISSUE THREAD

**Issue by sslhk** [fbelavenuto/arpl#531]
<img width="1110" alt="synology 4GB" src="https://user-images.githubusercontent.com/29858604/214252940-bbf6a83f-f9d6-4c69-9859-9a4343b45f45.png">
Hi, I installed v1.0-beta12 and 2 x 8GB physical memory, but the NAS system only shows 4GB memory, anyone can assist to fix this issue?

**Comment by sslhk** [comment]
Hi, I installed v1.0-beta12 and install 2 x 8GB phisical memory, but the Nas only shows 4GB memory, anyone can assist to fix this issue?

**Comment by fbelavenuto** [comment]
In the ARPL shell, type: "free -h"
Check in the BIOS if is recognized 8GB

**Comment by fbelavenuto** [comment]
Very Strange! Try to clean memory contacts, swap modules, etc. The ARPL kernel and DSM kernel not have memory limits, both are 64-bit.

**Comment by sslhk** [comment]
Hi fbelavenuto,  a solution for memory issue from google search, url "https://xpenology.com/forum/topic/7527-hp-n54l-dsm-61-onwards/page/3/#comment-73074", they said add "set common_args_3617='disable_mtrr_trim syno_hdd_powerup_seq=0 HddHotplug=0 syno_hw_version=DS3617xs vender_format_version=2 console=ttyS0,115200n8 withefi elevator=elevator quiet syno_port_thaw=1'" can fix the memory problem, but no luck for me even I added this to the grub.cfg.

**Comment by sslhk** [comment]
Problem is fixed after change to DS1621+ version.
