### ISSUE TITLE
error "Failed to install the file. The file is probably corrupted"

### ISSUE THREAD

**Issue by yossiyemin** [fbelavenuto/arpl#534]
I use an intel nuc to which two drives are connected via a splitter that sits on the m.2 like this:
https://a.aliexpress.com/_EzkBz9F

Every installation I try I get an error "Failed to install the file. The file is probably corrupted" Does anyone know a solution?

**Comment by fbelavenuto** [comment]
What is the name of the PAT file you downloaded? At what percentage of the installation does the error occur?

Try letting DSM automatically download the PAT file.

**Comment by yossiyemin** [comment]
> מה השם של קובץ ה-PAT שהורדת? באיזה אחוז מההתקנה מתרחשת השגיאה?
> 
> נסה לאפשר ל-DSM להוריד אוטומטית את קובץ ה-PAT.

**Comment by yossiyemin** [comment]
> What is the name of the PAT file you downloaded? At what percentage of the installation does the error occur?
> 
> Try letting DSM automatically download the PAT file.

I tried with the latest version and also with the automatic download of the firmware - I was stuck by 55%

**Comment by fbelavenuto** [comment]
If the error occurs at 55%, there is a problem with boot disk detection. If the loader is in a SATADoM it may be configured as an IDE. If it's on an SD/MMC port, there's no driver (there are no SD/MMC modules yet).

**Comment by yossiyemin** [comment]
> If the error occurs at 55%, there is a problem with boot disk detection. If the loader is in a SATADoM it may be configured as an IDE. If it's on an SD/MMC port, there's no driver (there are no SD/MMC modules yet).

Thank you very much for the quick reply, is there a solution? In addition, is it possible to install the system on usb and connect additional drives through the connection?

**Comment by fbelavenuto** [comment]
Just for comfirmation, you are using ARPL onto USB flash drive?

**Comment by yossiyemin** [comment]
> Just for comfirmation, you are using ARPL onto USB flash drive?

Yes, and I want to install the system on an external hard drive connected with usb

**Comment by fbelavenuto** [comment]
I believe install on a usb mass storage is unsupported by DSM. You need sata ports
