### ISSUE TITLE
Use fixed IP in menu.sh mode

### ISSUE THREAD

**Issue by explorerhk** [fbelavenuto/arpl#535]
Is there any way to use fixed IP instead of getting IP from DHCP?

**Comment by ardenee** [comment]
You could set the ip reservation to the mac address in your router in the dhcp section, most routers have this option. This is what I do.

**Comment by fbelavenuto** [comment]
I'm sorry, I have no plans to support a static IP. You can reserve the MAC for an IP on your router (@ardenee answer) or leave it fixed within DSM only.
