### ISSUE TITLE
cpu 8 core not boot about.

### ISSUE THREAD

**Issue by gokselu** [fbelavenuto/arpl#537]
not boot any model 8cpu core. only 4 core boot ok. and everyting works.

Other information for the curious;

my config;

esxi hardware
asus h97 plus motherboard
i7 4790
32gb ram

esxi config for syno vm;

sata chipset passthrough
usb passthrough <- arpl bootloader installed.
usb not supported boot on esxi -> look the plopboot.iso -> plopboot iso for default selector usb -> plopboot create iso -> cdrom attach IDE. not sata, not scsi.
cpu 4 core
4gb ram

**Comment by fbelavenuto** [comment]
Please try to add the variable "disable_mtrr_trim" with no value in cmdline menu:

https://github.com/fbelavenuto/arpl/wiki/Add-an-cmdline-synoinfo-entry

Boot and test
