### ISSUE TITLE
R8152 USB 2.5G network card cannot be driven successfully

### ISSUE THREAD

**Issue by Mozi71** [fbelavenuto/arpl#539]
RTL8152/RTL8153/RTL8156 (2.5Gbps or 1.0Gbps) USB 2.5G network card cannot be driven successfully (https://github.com/bb-qq/r8152), I added R8152 driver support in the arpl compilation stage, and it failed. Seeking solutions (translated from Chinese to English by Google Translate)
Reference address: [1] https://www.mi-d.cn/2396
                     [2] http://www.mi-d.cn/2331
                     [3] https://github.com/bb-qq/r8152

**Comment by Mozi71** [comment]
RTL8152/RTL8153/RTL8156(2.5Gbps or 1.0Gbps) USB 2.5G网卡无法驱动成功(https://github.com/bb-qq/r8152)，我在arpl编译阶段添加了R8152的驱动支持，失败了，寻求解决方案（由谷歌翻译中翻译英）
参考地址：[1]https://www.mi-d.cn/2396
                    [2]http://www.mi-d.cn/2331
                    [3]https://github.com/bb-qq/r8152

**Comment by Mozi71** [comment]
> Please test with this image: https://github.com/fbelavenuto/arpl/releases/tag/test2-r8152

Thanks, I will try it right away

**Comment by Mozi71** [comment]
> Please test with this image: https://github.com/fbelavenuto/arpl/releases/tag/test2-r8152

[Translated from Chinese to English by Google]
Thanks for your guidance, I initially solved the problem of driving R8152 in Synology DS1621+, but a new problem appeared,
As follows: 
            1. The test file provided just now cannot automatically identify the nvme cache disk, but it can be found in [arpl v1.0-beta13]
            2. I need to manually install the R8152 driver in the package center, and I need to repair it after each restart of Synology to use the R8152 2.5G USB driver normally, so I can only use the motherboard network card when starting the system. I am not sure if this is a problem with the R8152 driver --- "r8152-v1000-2.16.3-3.spk"---[ https://github.com/bb-qq/r8152/releases ], or arpl problem

**Comment by Mozi71** [comment]
感谢您的指导，我初步解决了在群晖DS1621+中驱动R8152 ，但是出现了新问题，
如下：1、刚才提供的测试文件无法自动识别nvme缓存盘，但是可以在【arpl v1.0-beta13】
           2、我需要手动在套件中心安装R8152驱动，并且需要在每次重启群晖后修复才能正常使用R8152 2.5G USB驱动，所以启动系统时只能使用主板网卡，我不确定这是否是R8152驱动问题----  "r8152-v1000-2.16.3-3.spk” [ https://github.com/bb-qq/r8152/releases ] ，还是arpl问题

**Comment by fbelavenuto** [comment]
Answers:

1 - Ok, It'll fixed.
2 - Without install this custom package, the r8152 is not recognized? The correct is detect and work without adicional package

**Comment by Mozi71** [comment]
> Answers:
> 
> 1 - Ok, It'll fixed. 2 - Without install this custom package, the r8152 is not recognized? The correct is detect and work without adicional package

without adicional package

After using arpl to compile the system, arpl can use R8152 to obtain the ip address, but after booting into the Synology system, the network card does not work normally and cannot be connected to the Internet. It is still necessary to use the network card on the motherboard for system access

**Comment by IT-Woker** [comment]
'test for r8152'
DS920+ 7.1.1-42962
no ‘cdc’ models , it can work !!!

**Comment by Mozi71** [comment]
> 'test for r8152' DS920+ 7.1.1-42962 no ‘cdc’ models , it can work !!!

Thanks for you test info,I will try it tomorrow morning.
