### ISSUE TITLE
Xpenology system will suddenly completely freeze, after transfer large data.

### ISSUE THREAD

**Issue by nuri4in** [fbelavenuto/arpl#54]
My Xpenology system is Asrock J3455 itx + 4G ram
(bulit in NIC chip is Realtek RTL8111GR.)

I liked the easy xpenology installation of the arpl loader, so I reinstalled with arpl loader.

I wanted to choose the ds918+ model. Because the 918+ model's cpu chipset is the same.
But I can't select the ds918+,  because 918+ models are not displayed
(J3455 CPU's lack of support for FMA instructions???)

Arpl loader's another advantage is that it takes less time to recognize the NAS after starting it.
(arpl loader : 10 -12 min, picopoco/tinycore redpill loader : 15 - 20min)

But, If the network transfer large data (like, 2GB), the the arpl loader system will suddenly completely freeze:
I had to force shutdown by pressing the power button long time.
I didn't have this symptom when I used picopoco/tinycore loader before.

I noticed something different during the installation process.
picopoco/tinycore redpill loader installed nic driver r8169, differently arpl loader's module nic driver r8168.

Please refer to this situation.

**Comment by sashakozlov86** [comment]
Greetings!  Try using an SSD as one of the drives.  I had problems with strong brakes on ASRock J4205-itx 8 gb ram and ASRock J4125-itx 8 gb ram.  The system took a long time to load, slowed down (the web interface worked very slowly) and after some time fell off.  When I installed an SSD as a second disk, everything began to work quickly and stably.  I did this already on 2 PCs connected to each other via CMS.

**Comment by fbelavenuto** [comment]
@nuri4in please execute into loader: 
lscpu
And post the result.

I've added r8169 driver, please update modules and rebuild the loader.

**Comment by nuri4in** [comment]
I rebuild the loarder. Now the arpl loader system doesn't freeze even the network transfer large data (like, 2GB).
But  it takes more time to recognize the NAS after starting it. (12-15min)
Thanks.

**Comment by fbelavenuto** [comment]
Thanks for the test
