### ISSUE TITLE
change video to text mode 

### ISSUE THREAD

**Issue by nemesis122** [fbelavenuto/arpl#549]
Hi Fabio

I have tested the newest ARPL 1.0beta 13 in VMM and it is only working when i set :

change video to text mode <-- 

steps :

1) Build the Loader 

2) choose : change video to text mode 

3) booting DSM 

 

what means change video to text mode ( means this UEFI and MBR Bios Mode )?

further how can i set always using this option change video to text mode ?

thank you

**Comment by fbelavenuto** [comment]
Hi, in text mode the kernel stay in text mode, do not initialize VESA graphics modes. The option is saved, you need do only one time.

When the menu show "change text to vesa mode" the mode is text, you do not need change anything.
