### ISSUE TITLE
The Network Cart for VMXNET3 on ESXi doesn't work.

### ISSUE THREAD

**Issue by thansury** [fbelavenuto/arpl#55]
I tried to install arpl boot on my computer. My network card is vmxnet3 , But the arpl 0.3 boot does not automatically pull the driver of this network card. Actually it works fine in version 0.2 , I hope you can fix it in the next version , Thank you a lot

**Comment by fbelavenuto** [comment]
Please test latest image

**Comment by thansury** [comment]
> Please test latest image

Yes, I've updated the latest version and it now works well with the vmxnet3 network card. thank U

**Comment by fbelavenuto** [comment]
Thanks, closing issue
