### ISSUE TITLE
*.pat file download twice

### ISSUE THREAD

**Issue by edwinhuish** [fbelavenuto/arpl#552]
When build the loader, I saw it need to download the  *.pat file. 

But after boot the loader, the system ask to upload another *.pat file or download again from the offical web.

Somethng I'm doing wrong?

**Comment by linkq** [comment]
this is normal process

**Comment by fbelavenuto** [comment]
Is normal. The ARPL loader based on Redpill loader needs to download PAT file to extract some files and patch it. After boot, the official DSM needs download the PAT to install the system. Is not possible automatize this part.
