### ISSUE TITLE
How do I upgrade ARPL?

### ISSUE THREAD

**Issue by lingyinsam** [fbelavenuto/arpl#559]
I am using an old version of ARPL and want to upgrade to the latest version (v1.0-beta13). What should I do?

**Comment by error105** [comment]
Click update in configuration?

**Comment by lingyinsam** [comment]
The reason I want to upgrade is that I replaced a new motherboard. The new motherboard NIC model is Killer™ E2500. This network card is not recognized, so I wonder if an update can solve this problem.











手握日月摘星辰，世上无我这般人

---Original---
From: ***@***.***&gt;
Date: Thu, Feb 2, 2023 16:40 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [fbelavenuto/arpl] How do I upgrade ARPL? (Issue #559)




 
Click update in configuration?
