### ISSUE TITLE
Error downloading Check internet or cache disk space

### ISSUE THREAD

**Issue by silence9527** [fbelavenuto/arpl#560]
Hello, this is my machine translation, I'm sorry if you don't understand something, I have a little problem when using ARPL, my cpu is N5000, use esxi，and I use a SATA HDD The hard disk and an NVME hard disk, when installing, it prompts Error downloading Check internet or cache disk space, and I searched many forums, and also used the PING command, the following is the picture of the error，please help me，thank you

![1](https://user-images.githubusercontent.com/79163325/216085235-2aeaa268-c658-4890-bfa3-5a46e1574b5d.png)
![2](https://user-images.githubusercontent.com/79163325/216085252-48576bf9-8ee2-47dd-b6a0-de94114dab35.png)
![3](https://user-images.githubusercontent.com/79163325/216086115-1083c476-f883-4d66-8611-9847cfc04e0f.png)
![4](https://user-images.githubusercontent.com/79163325/216086144-7a24515a-8a6d-4a71-b77e-4a289bd44aa3.png)
![5](https://user-images.githubusercontent.com/79163325/216086156-455700ca-791b-4e22-abb6-95baef6ffbbc.png)

It seems that when using the PING command, such as ping github.com ping google.com, there is no response, but I can access Google and github on my computer

**_### The problem has been solved, replace DNS_**

**Comment by Angelwized** [comment]
please tell me dns number ,i have same trouble.

**Comment by silence9527** [comment]
> 

I am very glad to help you. The DNS I set is 140.82.121.3. If you are in bypass or virtual machine mode, it is recommended to change the DNS of the main route and the bypass route and restart it.

**Comment by fbelavenuto** [comment]
Closing
