### ISSUE TITLE
new 42218 pat hash

### ISSUE THREAD

**Issue by wjz304** [fbelavenuto/arpl#565]
new 42218 pat hash:

DSM_DS1019+_42218.pat sha256pat: e782ad4ce5e0505e7981a5a3fa7ca986a4575240f645ec2c64f92def1774556f
DSM_DS1019+_42218.pat sha256zImage: 7311b04f7462847f529cf966c7b332097354692485c8157643d89441e2a81cd0
DSM_DS1019+_42218.pat sha256ramdisk: a8bcb6c36e8657a8723882b19ec3e76149dc67df3650f6db0af1958637e7f565
DSM_DS1019+_42218.pat md5pat: a7c5ac7a5963aac8bf9a599a8a6f6b86
DSM_DS1520+_42218.pat sha256pat: b8864e2becd8ce5a6083db993564c8c0b982df8300a006b56695a0495a670aa3
DSM_DS1520+_42218.pat sha256zImage: 70e93678f3932c35c5e884f950e50b36f8dc6366f96dd9a454c8d47ecbaee5de
DSM_DS1520+_42218.pat sha256ramdisk: 7679ab11e895302425533c64e0dded211b38b8af71f2dd268c47a68bc9f6818a
DSM_DS1520+_42218.pat md5pat: d1ebc3c9a2b9e04980a85c4784904f91
DSM_DS1621+_42218.pat sha256pat: 396144fdcd94d441b4ad665099395cf24a14606742bee9438745ea30bf12b9ef
DSM_DS1621+_42218.pat sha256zImage: 0ab3bf0ff027fb94863ef8822df787194f2d21079ecc66c0b0d4e46d24598855
DSM_DS1621+_42218.pat sha256ramdisk: 127a12bab3835cdf5af4e7ad2a23e78f889408302c55e5052080671cff6da5b7
DSM_DS1621+_42218.pat md5pat: 1fd1d6e733bb096f418f68e06f81022e
DSM_DS1621xs+_42218.pat sha256pat: 12bcfd44b4aaa6c3439b1404b7f07760373d816724ef672884d5187f27ccd70f
DSM_DS1621xs+_42218.pat sha256zImage: 3697732b2f29a4b7020f4994ff06c2d06309894ab568e264716bf7d5d02ae685
DSM_DS1621xs+_42218.pat sha256ramdisk: 5727d99522a8d7e8e31cdc353e295ce4280b956391396d080d02fcde1e07c029
DSM_DS1621xs+_42218.pat md5pat: 302fdefb00c8d4f8bf95ac25dca1e864
DSM_DS2422+_42218.pat sha256pat: 5a6cfbc690facdfaef9fbcc55215eac38c73ca6a85965a910af11cede5e2cd5d
DSM_DS2422+_42218.pat sha256zImage: e083a8aec10537582ed0dd6d79bc358d9aff828b3e256996ef1e4f4bf418dd5d
DSM_DS2422+_42218.pat sha256ramdisk: 57bcadf9699252aa68dac40b5c48f362169b51fda9f77a7f1b51e3336a551f8f
DSM_DS2422+_42218.pat md5pat: 7fe3c9ae80396a2ea9ed9909b8746c4b
DSM_DS3615xs_42218.pat sha256pat: ae1aca3b178a00689b93e97cca680b56af3f453174b852e0047496120dee2ee3
DSM_DS3615xs_42218.pat sha256zImage: 354f0bb13c898a7b24f2942d8015f591f7acce1739e2060580c0f38c41addaf7
DSM_DS3615xs_42218.pat sha256ramdisk: 3a8c2fe60142d3eb3a7ed2381819faa1db2cda30ff163288dd0a6c85a25815c1
DSM_DS3615xs_42218.pat md5pat: 9f959ec4d16d5d7729374961fc2b9bed
DSM_DS3617xs_42218.pat sha256pat: f7e846e2a22b62613ac5e9d6e154df0213ba4ae64a6556297af627cd1e643e5c
DSM_DS3617xs_42218.pat sha256zImage: 8e0ab965c85b348dfc9dc17392b9cf0a117756f1d1bc4c0f0d19bb610350659d
DSM_DS3617xs_42218.pat sha256ramdisk: eaddd97c40a35bbcf4092417364ca4376925fb3eb322cad0cf602d4c7973d147
DSM_DS3617xs_42218.pat md5pat: b7d85926561ff125928b68e7fffa646b
DSM_DS3622xs+_42218.pat sha256pat: a222d37f369d71042057ccb592f40c7c81e9b988a95d69fa166c7c2a611da99c
DSM_DS3622xs+_42218.pat sha256zImage: d6059bcd7160ed1f775a9323599ac8860b60ada32f0a4f3e5ca166c15a17784e
DSM_DS3622xs+_42218.pat sha256ramdisk: 11ebadba5d831ad6f31258ab317ed1f7cbfe18243413f9f81291b894b5f7a591
DSM_DS3622xs+_42218.pat md5pat: b9b452577b38adc82aca42e031be267b
DSM_DS918+_42218.pat sha256pat: a662d11999c266dfa86c54f7ba01045c6644c191124195a22d056d618790dffe
DSM_DS918+_42218.pat sha256zImage: 7311b04f7462847f529cf966c7b332097354692485c8157643d89441e2a81cd0
DSM_DS918+_42218.pat sha256ramdisk: d27320b536da0ac82d7959e0492180b3a25ef78a3997f65cc4ccddc426b921bd
DSM_DS918+_42218.pat md5pat: 0c8a0d2dc6f1d7e37ee63d74760808b8
DSM_DS920+_42218.pat sha256pat: b9b77846e0983f50496276bec6bcdfcfadd4c1f9f0db8ed2ca5766f131ddf97f
DSM_DS920+_42218.pat sha256zImage: 70e93678f3932c35c5e884f950e50b36f8dc6366f96dd9a454c8d47ecbaee5de
DSM_DS920+_42218.pat sha256ramdisk: 8607c34fff3a13c75dbc1a9c730de2b2cf649697d6244fd37047090d2e2ba897
DSM_DS920+_42218.pat md5pat: 55a7e4ccbf6fcba9238a11976a4a7381
DSM_DVA3219_42218.pat sha256pat: b3498a20aeb7c7c36deca0f4393172d4db7b51aa4fb87eaace83fe224d935e3b
DSM_DVA3219_42218.pat sha256zImage: 8b58e602317286bdd25481c4927a791507589ce0b7c29f1ad394d08b634d41a3
DSM_DVA3219_42218.pat sha256ramdisk: 5b301519fe08200e4cb368b7d23e4ce460d5412428126b9496084ceae3f6d67e
DSM_DVA3219_42218.pat md5pat: 4345e7cff9ba4fe97793c254c87b3ed5
DSM_DVA3221_42218.pat sha256pat: 6722c73c51070dde2f542659d7728c497fc846256da2c9cf017177476de0bb09
DSM_DVA3221_42218.pat sha256zImage: 8b58e602317286bdd25481c4927a791507589ce0b7c29f1ad394d08b634d41a3
DSM_DVA3221_42218.pat sha256ramdisk: 86a7450cdc461049c4cefe3fe3a1f9d241ea3c484f72f5667d7cd27f2842c8d6
DSM_DVA3221_42218.pat md5pat: e3455afd4644cb882cb2c9bede08c7bf
DSM_FS2500_42218.pat sha256pat: 3fbd5defbc0fef0d152494033f3e817c330525b70e356a9e9acd2b72d9806b59
DSM_FS2500_42218.pat sha256zImage: e083a8aec10537582ed0dd6d79bc358d9aff828b3e256996ef1e4f4bf418dd5d
DSM_FS2500_42218.pat sha256ramdisk: 8d66ddfa947b38c0e407d4c5efd7558b1a9392e04fd83fe9f162e1aa546f8da8
DSM_FS2500_42218.pat md5pat: 9562d49a07f5481208b672ff777f3cbf
DSM_FS6400_42218.pat sha256pat: 3437cc14ba919f13e37691d31d960f3f48cd3d734c015001ad2a7679636a5e9d
DSM_FS6400_42218.pat sha256zImage: 67a5c04ba47cbef148195816412f88248b86a58e021e1c8196e31fbd375d0b50
DSM_FS6400_42218.pat sha256ramdisk: ec1e1ea2022ac4af7dfbf2f72b64219b0c8ef747278a0b5c37d50ac7b07195ed
DSM_FS6400_42218.pat md5pat: e7887381980432a7be5ddf4dec0772ad
DSM_RS3413xs+_42218.pat sha256pat: b5f5505a4ee0d623c562db43a0be6aba64a5bc57c6d6dcb796d80a60ea5fc7cd
DSM_RS3413xs+_42218.pat sha256zImage: 354f0bb13c898a7b24f2942d8015f591f7acce1739e2060580c0f38c41addaf7
DSM_RS3413xs+_42218.pat sha256ramdisk: ad2b7c6ffabf348a14df0558ab89bc2ac62226b33dfe5b19114f7beed11ae41f
DSM_RS3413xs+_42218.pat md5pat: 2f2e7312db70ca36b3c09236f117f23f
DSM_RS3618xs_42218.pat sha256pat: 941886bee9a0929c6bd078c5f2c465d9599721fc885a1e3835d6b60631f419af
DSM_RS3618xs_42218.pat sha256zImage: 41993de949af53def17ca6190bfff503044b9ebc0beccf7a3d54ab050998e9db
DSM_RS3618xs_42218.pat sha256ramdisk: cd7c7ed0fba15b2d3eae70b9d6f680a8dfbe1138164e6312d98482177746f544
DSM_RS3618xs_42218.pat md5pat: e91236e37fdbbb3a4f368dffa5a63013
DSM_RS4021xs+_42218.pat sha256pat: 2a32266b7bcf0b2582b5afd9e39dc444e7cb40eaf4ccfdbfedf4743af821f11c
DSM_RS4021xs+_42218.pat sha256zImage: d6059bcd7160ed1f775a9323599ac8860b60ada32f0a4f3e5ca166c15a17784e
DSM_RS4021xs+_42218.pat sha256ramdisk: f2b99b4c05559376d34d30d6446c30a8b3f44f516e5a041299d03be9c7fd0095
DSM_RS4021xs+_42218.pat md5pat: cbcb77548de26b6843ab31d7a7258b62

**Comment by cfplcfpl** [comment]
What's the use of this? When you download 100% for the first time, you will be prompted when you download pat,Hash of pat not match, try again!

**Comment by cfplcfpl** [comment]
When alpl is compiled, after downloading 100% of the first time, when returning to pat, it will prompt Hash of pat not match, try again!, Is it the 42218 pat hash problem? If so, how to solve it

**Comment by shmilyin** [comment]
I have the same problem in 42218, 42661 and 42962 have no problem.

**Comment by Dixonapps** [comment]
Here i made a fix for it: 
https://github.com/Dixonapps/arpl_checksumfix

-Build on the newest branch from fbelavenuto (1.1-beta1)
-Fixed the hash/checksum error for 7.0.1-42218
-Removed restrictions flags from DS918+

**Comment by fbelavenuto** [comment]
Use this image:
https://github.com/fbelavenuto/arpl/actions/runs/4129912020
