### ISSUE TITLE
Arpl - compilation error, prompt Hash of pat not match, try again!

### ISSUE THREAD

**Issue by cfplcfpl** [fbelavenuto/arpl#568]
Arpl - compilation error, prompt Hash of pat not match, try again!, Download to 100% error report, and test 918+42218 920+42218 error report
![WX20230203-202222@2x](https://user-images.githubusercontent.com/124364663/216606523-97210a3c-963a-42bb-8032-8ab8eb7e1c47.png)

**Comment by FNS005** [comment]
Hello, is your problem solved

**Comment by cfplcfpl** [comment]
Not resolved

**Comment by nonskim** [comment]
THE SAME QUESTIONS

**Comment by fbelavenuto** [comment]
Duplicate: #565

**Comment by cfplcfpl** [comment]
The boot cannot be started with the latest v1.1-beta1 boot. It has been stuck here and restarted
![WechatIMG330](https://user-images.githubusercontent.com/124364663/217779033-4f48f30e-12cf-4f7b-87cf-c8b510e2690a.jpeg)
![WechatIMG329](https://user-images.githubusercontent.com/124364663/217779048-9a290482-a38c-4f67-9132-0a07746fd9b5.jpeg)
