### ISSUE TITLE
May I ask how to modify grub.cfg for Synology boot when i use ./boot.sh to start 

### ISSUE THREAD

**Issue by wnark** [fbelavenuto/arpl#575]
Hello, I also have this problem when I use a virtual machine to install ds918 (I didn't use dva1622 because my qemu version does not support this model and cannot be connected to the Internet). How to modifying grub to manually add synoboot_satadom=2 dom_szmax=510?It seems that vim directly editing the grub file of the startup disk
https://github.com/fbelavenuto/arpl/issues/351
Modifying /mnt/p1/grub/grub.cfg will not take effect, and will not be useful for boot Synology from here
![image](https://user-images.githubusercontent.com/24355466/217022938-961af807-8c99-4c8e-a6fb-3beade64673e.png)

**Comment by wnark** [comment]
I modified boot.sh, it seems that I can use this parameter to start Synology for the time being, but it seems that Synology started in this way does not hide the boot disk
![image](https://user-images.githubusercontent.com/24355466/217025613-ad1311c3-9117-4e7d-9936-7fe43c9eed62.png)

**Comment by fbelavenuto** [comment]
This parameters is automatic calculated. Please do not edit manually, let the loader do job.

What is the cmdline generated automatically without manual edit?

**Comment by wnark** [comment]
Thank you, I can install it normally by manually modifying the configuration file and setting it as sata
