### ISSUE TITLE
How to modify boot.sh to support the use of virtio-scsi hard disk as boot disk

### ISSUE THREAD

**Issue by wnark** [fbelavenuto/arpl#577]
Hello, I'm trying to install dsm918 on openstack platform server of some cloud vendor. Currently I have successfully installed dsm by manually modifying the virsh xml file and booting the system with a sata mode hard drive
![image](https://user-images.githubusercontent.com/24355466/217144904-d0128e62-7f23-4ccb-84a9-d801c284bd4b.png)
However, since the platform is not deployed by me, the default cloud hard disk of the platform only has two options, scsi and virtio, and the platform will automatically change sata back to scsi every time I start dsm.
I found this option that might be helpful for using scsi drives as boot disks, but I don't know how to modify it:.
https://github.com/fbelavenuto/arpl/blob/230cbc986b42ae47ecbb0e9539c079d68dddfd80/files/board/arpl/overlayfs/opt/arpl/boot.sh
![image](https://user-images.githubusercontent.com/24355466/217150481-f27b0a2f-aa11-42b1-878f-bdda16675983.png)
How do I change this to use a scsi cloud drive as the dsm boot disk?

**Comment by wjz304** [comment]
dom 只是区分 usb 和 sata，具体支持的类型是在 rp.ko 侧实现的，改了这个参数也没有用的

**Comment by fbelavenuto** [comment]
Sorry, is not possible to use virtio-scsi as boot disk, only SATA and USB stick.
