### ISSUE TITLE
华擎J3455有成功的没？

### ISSUE THREAD

**Issue by hyy34** [fbelavenuto/arpl#581]
前3项选一次后，直接Build the loader，重启机器，貌似进不去，918 920都试了，需要什么特殊操作吗？

**Comment by gbaoye** [comment]
相同的问题

**Comment by kingandwood** [comment]
有，我j3455+最新版DSM+DS918成功了。

UEFI启动且硬盘数量大于2个的话，v1.0某个beta之后开始就出现问题。我忘记哪个issue里有人提过了。你用v1.0 beta2试一下，这个版本是ok的，我亲测了。

但我这边还有一个问题：Advanced Media Extension激活不了。网上说是除了全洗白外，netif_num设置要正确。我的机器是一个网口，DS918应该是2个网口，我不确定我的grub里应该设置为1还是2。但我两个都试了，都不行。（不影响启动，只影响AME激活）你们可以试下

**Comment by Brian099** [comment]
3455 bios默认不支持Linux启动，安装群晖后启动过程很漫长，启动时间很久，要耐心的等待，10分钟以上 
可以通过给BIOS打补丁解决启动慢的问题

**Comment by hyy34** [comment]
> 

1.0 beta2安装的DSM版本和新的是一样的吗？

**Comment by hyy34** [comment]
> 3455 bios默认不支持Linux启动，安装群晖后启动过程很漫长，启动时间很久，要耐心的等待，10分钟以上 可以通过给BIOS打补丁解决启动慢的问题

打补丁了，进hdmi里看了，貌似跟引导成功的显示不一样。。

**Comment by hyy34** [comment]
> 相同的问题

打了补丁，然后用了别人分享的成品，成功了。起机也很快。

**Comment by kingandwood** [comment]
> 
是的，可以装最新的7.1.1-42962 update3

**Comment by fbelavenuto** [comment]
English please
