### ISSUE TITLE
Error loading modules

### ISSUE THREAD

**Issue by spammoogle** [fbelavenuto/arpl#585]
I have been updating ARPL and its modules.
There are several that give loading error.
I send images.

![WhatsApp Image 2023-02-09 at 13 42 58 (1)](https://user-images.githubusercontent.com/7886433/217816145-0e9f3997-4ffc-404a-b7da-475907cec008.jpeg)
![WhatsApp Image 2023-02-09 at 13 42 58](https://user-images.githubusercontent.com/7886433/217816166-ed38bdd2-e011-48b5-bd66-89c406e5d861.jpeg)

**Comment by fbelavenuto** [comment]
Hi, please check your internet and try again. Here is working, maybe a temporary internet failure.

**Comment by spammoogle** [comment]
Hi, 
I have tried it several times...
Everything is updated except those two modules.

Installation with v1.1-beta1 has been successful, but once installed when you put in a new disk, at the next reboot, ARPL no longer assigns IP to the NAS and you can't boot it.

If you unplug the drive and reboot then the IP is assigned and you can enter the NAS. Of course, then I get an error that a disk is missing.

And this situation is repeated constantly.

Installation DSM_DS3622xs+_42962 with USB stick :
ASUS motherboard
I7 2270 processor
20GB RAM
main disc 120GB Kingston SSD

**Comment by fbelavenuto** [comment]
Please check if LKM is selected as PROD, in advanced menu

**Comment by spammoogle** [comment]
Yes, LKM is selected as PROD.

It still doesn't work.
Process:
1.- I start DSM with a single disk. Assign IP and I can access.
2.- I connect disk dynamically. It recognizes it and assigns it.
3.- DSM restart with both disks. It does not assign IP.
4.- PC restart. I remove the second disk.
5.- I start DSM with a single disk. Assign IP and I can access again.
6.- return to point 1 :-D...

It still doesn't work.
Process:
1.- I start DSM with a single disk. Assign IP and I can access.
2.- I connect disk dynamically. It recognizes it and assigns it.
3.- DSM restart with both disks. It does not assign IP.
4.- PC restart. I remove the second disk.
5.- I start DSM with a single disk. Assign IP and I can access again.
6.- return to point 1 :-D...

I honestly don't know what is happening.

**Comment by spammoogle** [comment]
Hi @fbelavenuto , 

I think something is going on with version DSM_DS3622xs+_42962,

In the end I have modified the boot with DS923+
It has installed correctly the first time and is stable with all disks.

Many thanks for everything.

**Comment by fbelavenuto** [comment]
> Hi @fbelavenuto ,
> 
> I think something is going on with version DSM_DS3622xs+_42962,
> 
> In the end I have modified the boot with DS923+ It has installed correctly the first time and is stable with all disks.
> 
> Many thanks for everything.

Ok, I'll check 3622, thks
