### ISSUE TITLE
Error Update ARPL

### ISSUE THREAD

**Issue by SayonaRRRa** [fbelavenuto/arpl#586]
Thank you so much for all your effort put into this tool.
I have managed to install this on many a platforms.
I have an ARPL 0.4-alpha8 DS920+ 42962. I woud like to update to the latest beta.
I boot into configure loader and in the update menu I get "Error downloading bzimage."
If I put a fresh image on my USB stick, would I have to reinstall completely ?

**Comment by fbelavenuto** [comment]
i've tested here, no problems!
You can take note of your serial number and addons choosed, burn the latest ARPL image to your USB flashdrive, uses the option "Try to recover a installed DSM" founded in advanced menu, and reconfigure only SN and Addons. In the latest ARPL version the SN is recovered too.

**Comment by SayonaRRRa** [comment]
Ok, THank you for your prompt reply.I will come back tomorrow with an update.
