### ISSUE TITLE
 VMware Workstation e1000 network fails for v1.1-beta1_DS920+

### ISSUE THREAD

**Issue by FZ500** [fbelavenuto/arpl#590]
VMware Workstation e1000 network failure, Boot can still ping to ip when IP appears, but loading DSM kernel... > Booting... cannot be pinged after the network is interrupted

The same setup works fine in v1.0-beta13

**Comment by fbelavenuto** [comment]
Please update modules, rebuild and test again

**Comment by FZ500** [comment]
update 1.1-beta2 works fine, thanks
