### ISSUE TITLE
Update to v1.1-beta1  failed can't boot 

### ISSUE THREAD

**Issue by sumonchai** [fbelavenuto/arpl#591]
v1.1-beta1 on  vmware 6.7
Can configs all. But Can't Access to to web config. check ping not found.
![image](https://user-images.githubusercontent.com/5920739/218027390-08ac7f85-6bec-4c62-8ba5-9c2152f7b2df.png)

**Comment by hahacandy** [comment]
I can't boot either.
I used esxi 6.7.

**Comment by revola38** [comment]
Same issue here. New install with v1.1-beta1 on ESXi 6.7. Trying to boot for installation, loader gets the IP address, it pings for 1 or 2 seconds, then connection drops and console does not seem reponsive anymore.
I tried with default add-ons and modules, then with some changes but no luck

![Screen Shot 02-10-23 at 02 54 PM](https://user-images.githubusercontent.com/72125904/218111537-d66219d4-a07b-4548-b188-14901d0615f0.PNG)

**Comment by fbelavenuto** [comment]
Please update modules, rebuild and test it

**Comment by sumonchai** [comment]
Success Work.
update modules, rebuild 

![image](https://user-images.githubusercontent.com/5920739/218144233-6d9f2cff-814d-4cf9-b7e1-6036f11741a5.png)

**Comment by revola38** [comment]
> Please update modules, rebuild and test it

I confirm it works now ! Thanks. And thanks for the great work on this project !

**Comment by hahacandy** [comment]
@fbelavenuto thank you!

**Comment by crazyshitass** [comment]
Same issue here. Update modules, rebuild, NOT working.

**Comment by subhrapratimde** [comment]
Same issue here. I am using Gigabyte GA-E2500N (rev. 1.0)(https://www.gigabyte.com/Motherboard/GA-E2500N-rev-10) board. Could that be a problem?

**Comment by crazyshitass** [comment]
> Same issue here. I am using Gigabyte GA-E2500N (rev. 1.0)(https://www.gigabyte.com/Motherboard/GA-E2500N-rev-10) board. Could that be a problem?

mine is Gigabyte h270n-wifi

**Comment by baozi510** [comment]
Same issue.
using V1.1-beta2.
J4105m
