### ISSUE TITLE
rescue mode with v1.1 beta 2 at boot

### ISSUE THREAD

**Issue by mpuff** [fbelavenuto/arpl#594]
I can't boot from the usb anymore, I get an error that grub_disk_native_sectors not found.
<img width="798" alt="Bildschirm­foto 2023-02-11 um 16 09 17" src="https://user-images.githubusercontent.com/13885599/218265994-b7d0020a-0ce2-49a5-ab7f-e0253e1697ce.png">

I use it at a hp microgen 8 baremetal installation

**Comment by krzysieki** [comment]
I encountered the same issue. My installation is on: Proxmox VE 7.3.6, SeaBIOS.

1. I was on some previous version (1.0alpha probably). 
2. Went to the ARPL web menu and selected "update menu" option.
3. After reboot, grub rescue with "grub_disk_native_sectors not found".

**Comment by mpuff** [comment]
also after a reinstall of the kernel, I doesn't get an ip after booting the kernel.
i have a hp micro gen 8.

**Comment by MartinKuhl** [comment]
here you have to recreate the loader. This error happens after update vom alpha to beta version of this loader.

**Comment by krzysieki** [comment]
@mpuff I resolved the issue reinstalling the version v1.0beta3. (in my case after reinstalling the loader all the "old" apps and data were untouched)

Please check the issue https://github.com/fbelavenuto/arpl/issues/526, there is more information. As for now it seems that v1.0beta3 is the last stable for most people.

**Comment by mpuff** [comment]
Thank you for this information

**Comment by fbelavenuto** [comment]
Hi, is necessary to reburn the USB stick or configure your BIOS to boot via UEFI.
