### ISSUE TITLE
Building loader issus

### ISSUE THREAD

**Issue by asaboss** [fbelavenuto/arpl#6]
Running arpl on ESXI 6.7u2.

I'm trying to do the same step as redpill, but get stuck at build the loader. 

![)X8CLYHWAW}@LBQF)2F(XCU](https://user-images.githubusercontent.com/19362747/177358759-2e200f8e-7e5a-4c6b-8301-3741c079c2bd.png)

This is excellent project , thank you :)

**Comment by fbelavenuto** [comment]
Please remove this addon. Go to "Addons/drivers" option, choose "Delete addon(s)", select "ata_piix" and press Enter.

**Comment by asaboss** [comment]
Building error has been fixed at alpha3. But this loader has some  problems.  

ESXI:6.7U2
1. LOADING DSM :OK
2. instanll DSM :OK
3. Booting DSM: Failed( automatically shutdown)
then try to downloading  addon popout : file format not recognized!

vmxnet3 , mpt2sas

**Comment by fbelavenuto** [comment]
Please try this alpha release:
https://github.com/fbelavenuto/arpl/releases/download/v0.1-alpha7/arpl-0.1-alpha7.vmdk.zip

**Comment by asaboss** [comment]
Storage Pool on DiskStation has degraded :(

ESXI 6.7U2 
MODEL: DS3622XS+
3008HBA card direct connect to dsm.

everything is good and fast during creating loader, i even forget to poll out hard drives from sever...2 disks has missed. 

HAHAHAHAH  I'M Repairing data NOW....

**Comment by fbelavenuto** [comment]
Closing
