### ISSUE TITLE
I have a question about adding a module.

### ISSUE THREAD

**Issue by dalso0418** [fbelavenuto/arpl#60]
Hello.

I am a user who has been using it well since the early version v0.1 whenever a new version comes out.

Previously, in v0.1, the current module (driver) could be added from webui, but is this function missing?

It is good that addon and module are separated, but I would like to add modules as a selection method as before.
Personally, it's good to add modules automatically, but I'd like to be able to choose them manually.

Thank you for the good project.
*Please understand if there is a misunderstanding as it was translated through a translator.

**Comment by fbelavenuto** [comment]
Hi, I changed it to load modules automatically! Some modules like "9p" are not automatically loaded, so this type of module will be addons for the user to add manually.
With the new way I'm following, it won't be possible to configure two ways to choose modules, what can be done is to create the empty module files (/mnt/p3/modules/<platform-kver>/tgz) and add the old addons manually to the image.

**Comment by fbelavenuto** [comment]
If exists another trouble, please open a new issue
