### ISSUE TITLE
USB drives are not recognized/ are popping up as internal drives with v1.1-beta2 on ESXi

### ISSUE THREAD

**Issue by BloodXPride** [fbelavenuto/arpl#600]
Hello,
with the new bootloader v1.1-beta2 and Xpenology in an VM on ESXi-7.0U3g-20328353, my USB drives are not recognized / are popping up as internal drives.
With v1.0-beta13 everything worked out perfectly.
How can i fix this?

**Comment by BloodXPride** [comment]
Nevermind, fixed it by changing SataPortMap and DiskIdxMap values.

**Comment by go2boss** [comment]
Would U tell me how to fix it on SataPortMap and DiskIdxMap values?
Thanks
