### ISSUE TITLE
Sorry for opening this issue, I need help.

### ISSUE THREAD

**Issue by spammoogle** [fbelavenuto/arpl#608]
I am aware that it has nothing to do with ARPL.

Does anyone else have the problem that they cannot register on the page of "https://xpenology.com/" forum ?
because I get a google catpcha message: "This site key is not enabled for the invisible captcha."

Does somebody know anything about this ?

I apologize again but I can't register and it doesn't let me write to the forum contact either.

![image](https://user-images.githubusercontent.com/7886433/219091071-c6c82980-4d71-4162-8914-067184b1f8cf.png)

**Comment by pcking99** [comment]
You ain't alone. I have tried multiple times but never got confirmation mail after creating an account.

**Comment by fbelavenuto** [comment]
Hi, I can't help, please use the Contact form from xpenology site to contact forum administrators.

**Comment by spammoogle** [comment]
The problem is that the same error also appears on the contact page.

thx
