### ISSUE TITLE
LSI-3008 with 24 hard disks

### ISSUE THREAD

**Issue by SGZLJSG** [fbelavenuto/arpl#609]
addon for LSI installed, but can not find any disk.

**Comment by SGZLJSG** [comment]
installed in a physical machine

**Comment by laotuoyuan1** [comment]
test ds3622xs

**Comment by SGZLJSG** [comment]
![17f30de1bd65e30821bed18067b186a](https://user-images.githubusercontent.com/125531975/219932101-8389a32c-491d-47ed-97f1-e83b7e29a0cb.jpg)
Thanks @laotuoyuan1 
Can find 24 hard disks, but can not format the disks.

**Comment by laotuoyuan1** [comment]
你是用什么盘引导的？应该可以用U盘引导，其他的都不行！

**Comment by SGZLJSG** [comment]
用U盘的。

**Comment by SGZLJSG** [comment]
能够检测到7-30号硬盘，就是格式化失败。帮忙看下怎么弄。

**Comment by laotuoyuan1** [comment]
关掉所有的sata控制器就好了  机器只插U盘和阵列卡



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月19日 16:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [fbelavenuto/arpl] LSI-3008 with 24 hard disks (Issue #609) |

能够检测到7-30号硬盘，就是格式化失败。帮忙看下怎么弄。

**Comment by SGZLJSG** [comment]
![1](https://user-images.githubusercontent.com/125531975/220002790-68c3023a-d3b9-4b1c-be6b-20b3c9a21013.jpg)
![2](https://user-images.githubusercontent.com/125531975/220002802-207fd2d2-dd32-4c83-90eb-a230c39d01a1.jpg)
![3](https://user-images.githubusercontent.com/125531975/220002812-a4d8d6a8-7bb3-4a5e-a1d3-5d7c760647d0.jpg)
![4](https://user-images.githubusercontent.com/125531975/220002820-1c76bf39-8765-4ce1-af2b-e845927a52d2.jpg)
Still not able to format the disks, installation failed

**Comment by laotuoyuan1** [comment]
只插一块硬盘试试



---- Replied Message ----
| From | ***@***.***> |
| Date | 02/20/2023 11:28 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [fbelavenuto/arpl] LSI-3008 with 24 hard disks (Issue #609) |





Still not able to format the disks, installation failed

**Comment by SGZLJSG** [comment]
![1](https://user-images.githubusercontent.com/125531975/220006363-6c06a2e0-0081-40f8-ab21-eddc027ee989.jpg)
![2](https://user-images.githubusercontent.com/125531975/220006366-75eb3d4f-90a4-4e59-ab8f-a38bc0c9400c.jpg)
**Still not able to format, even use 1 disk only.**

**Comment by SGZLJSG** [comment]
![Screenshot 2023-02-20 130434](https://user-images.githubusercontent.com/125531975/220014391-457ff2ca-fd2a-4421-b4d6-9af2d22bd02b.jpg)
![Screenshot 2023-02-20 130852](https://user-images.githubusercontent.com/125531975/220014393-9620c0b2-b518-4ce8-99c7-043edcc4f3c5.jpg)
4021 installed successfully. will test the stability and feedback here. Thanks A LOT!!

**Comment by fbelavenuto** [comment]
I do not understood chinese, but if working, then I'll close the issue
