### ISSUE TITLE
Loader disk neither USB or DoM (I know the root cause, but need help!)

### ISSUE THREAD

**Issue by b2ctransfer** [fbelavenuto/arpl#614]
I used one internal NVME M.2 disk as loader disk. Successfully write the loader files on it. However, when I boot the machine, it shows "Loader disk neither USB or Dom" and loader just quit moving forward. 
But if I choose "boot the loader" either through web interface or command-line, it boots successfully.
I am wondering whether there is a way to configure the loader location (lift restrictions to USB/DoM).

Here are some information you may need from lspci, lsblk and blkid commands:
<img width="884" alt="Screenshot 2023-02-17 at 11 55 16 AM" src="https://user-images.githubusercontent.com/6739186/219738233-e65d8bf2-086d-4967-a191-092f377c19d5.png">

<img width="1907" alt="Screenshot 2023-02-17 at 11 52 11 AM" src="https://user-images.githubusercontent.com/6739186/219737563-5421aea5-db0b-4fb5-aef7-fca20e5c21c5.png">

**Comment by b2ctransfer** [comment]
Alternatively, if there is a way to deploy DSM 7 onto PCIE NVMe drive then I can use the SATA SSD as loader disk. Any help is  appreciated. Thanks.

**Comment by asqw77918** [comment]
同样的问题，我也是装在nvme硬盘里。等一个解决办法

**Comment by fbelavenuto** [comment]
Please use only supported disk models for loader: SATA or USB flash stick
