### ISSUE TITLE
Loader disk not found!

### ISSUE THREAD

**Issue by lingyinsam** [fbelavenuto/arpl#618]
My motherboard has 3 SATA ports, and I have an m.2 to sata adapter card installed on the m.2/nvme port based on the asm1166 chip. All six of my hard drives are plugged into this adapter. But when I installed the hard disk in the sata interface of the motherboard and started, the message "Loader disk not found!When I removed the sata hard disk on the motherboard, I was able to enter the boot screen and boot the system normally.

**Comment by fbelavenuto** [comment]
boot disk is a SATA disk, is necessary plug boot disk on the native SATA of your board, is incompatible to use adapters. Please check this.

**Comment by lingyinsam** [comment]
I've figured out why, one of my other sata drives is already an aprl boot drive. Having two boot disks at the same time caused the problem.











手握日月摘星辰，世上无我这般人

---Original---
From: "Fabio ***@***.***&gt;
Date: Thu, Feb 23, 2023 21:36 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [fbelavenuto/arpl] Loader disk not found! (Issue #618)




 
boot disk is a SATA disk, is necessary plug boot disk on the native SATA of your board, is incompatible to use adapters. Please check this.

**Comment by fbelavenuto** [comment]
Cool! Thanks.
