### ISSUE TITLE
Ability to connect more than 2 sata drives to dva1622

### ISSUE THREAD

**Issue by sashakozlov86** [fbelavenuto/arpl#62]
Good afternoon!  In one of the threads of the Xpenology forum, I saw that more than 2 sata hdds can be connected on dva1622 assemblies.  Is it possible to do this with the arpl loader?  If possible, what needs to be done?  Rebuild the build again?

**Comment by fbelavenuto** [comment]
Yes, it's possible! Just use the last release, disks will be detected automatically. This detection is made on-the-fly during DSM boot

**Comment by fbelavenuto** [comment]
PS: DT models (DVA1622+ included) only works with SATA drives, is impossible to use another disk type (SCSI, SAS, IDE, etc)

**Comment by sashakozlov86** [comment]
Thank you friend!  Do I need to install additional addons when building?  Up to how many drives can be connected to the system?  And the last question, should all these drives be defined as SATA HDD and visible in the storage manager?  Thank you!

**Comment by fbelavenuto** [comment]
You don't have to do anything, it's all automatic. In theory, infinite disks can be added. All disks will visible in the storage manager

**Comment by sashakozlov86** [comment]
Thank you very much dear friend!  I'll definitely try it tonight!

**Comment by sashakozlov86** [comment]
It work! Thank you very much my friend!
