### ISSUE TITLE
adaptec hba support?

### ISSUE THREAD

**Issue by psp271** [fbelavenuto/arpl#63]
hello,can you add  the module "accraid.ko"? thank you.

tc@box:~$  lspci -tnnvq

       
            |            \-01.0  VMware USB2 EHCI Controller [15ad:0770]
           +-15.0-[03]----00.0  Adaptec Series 8 12G SAS/PCIe 3 [9005:028d]
           +-15.1-[04]--
           +-15.2-[05]--
           +-15.3-[06]--
           +-15.4-[07]--
           +-15.5-[08]--
           +-15.6-[09]--
           +-15.7-[0a]--
           +-16.0-[0b]----00.0  Intel Corporation 82574L Gigabit Network Connection [8086:10d3]

**Comment by fbelavenuto** [comment]
Hello, the correct would be "aacraid.ko" right?
If yes, they already exists, ex:
https://github.com/fbelavenuto/arpl-modules/blob/main/apollolake-4.4.180/aacraid.ko

**Comment by psp271** [comment]
> Hello, the correct would be "aacraid.ko" right? If yes, they already exists, ex: https://github.com/fbelavenuto/arpl-modules/blob/main/apollolake-4.4.180/aacraid.ko

Thank you ! and it's "aacraid.ko".

**Comment by fbelavenuto** [comment]
Closing
