### ISSUE TITLE
Second mac address was not applying

### ISSUE THREAD

**Issue by T-REX-XP** [fbelavenuto/arpl#69]
**DSM:** DS3622xs
**ARPL**: 0.3a7
Seems like something is wrong with applying the mac addresses to the network adapters.
command line contains :`netif_num=2 mac1=00.... mac2=00....` , but when DSM was loaded, the only first mac is applied, second mac unchanged.

<img width="508" alt="image" src="https://user-images.githubusercontent.com/4560084/182469686-f0710d21-b95f-414d-989e-6052eccff0e3.png">

**Result:**
<img width="394" alt="image" src="https://user-images.githubusercontent.com/4560084/182469931-e447ffae-423d-4a05-8fdb-c44ae6961c9d.png">

**Comment by fbelavenuto** [comment]
Please go to loader, menu synoinfo and add the entrie "support_oob_ctl" with value "no"
Rebuild the loader and boot

**Comment by T-REX-XP** [comment]
Thanks. It’s works!

**Comment by Donghyun-Son** [comment]
> Please go to loader, menu synoinfo and add the entrie "support_oob_ctl" with value "no" Rebuild the loader and boot

Currently, v0.4 alpha7 is used, and even if the mentioned option is not applied, two MACs can be applied.
But is there any way I can get MAC1 written in front in this situation?
Even if MAC1 is entered first, MAC2 is written first.
I want to fix it because eth0 is using MAC2's address and eth1 is using MAC1.

**Comment by fbelavenuto** [comment]
Try to invert into config file the "mac1" with "mac2"

**Comment by Donghyun-Son** [comment]
I'm far away from the server right now, so I can't try it out sooner. After applying the solution, I will share the results.
