### ISSUE TITLE
Compile and guide the installation of DSM DS920+, and found problems with the MAC of the network card, the number of hard disks, and the order of adjustment.

### ISSUE THREAD

**Issue by N04LE7** [fbelavenuto/arpl#698]
Compile and guide to install DS920+ (42962) on the physical machine J1900, the network cable has been plugged into the network card 1, set netif_num=2, add the MAC address of the network card 2; arpl uses the MAC address of the network card 2 to obtain the IP, the IP is 192.168.1.43 , and this IP cannot enter DSM, you must use the MAC address IP 192.168.1.42 of network card 1 to enter DSM. After entering the system, the order of the network cards is also reversed. After trying to exchange the MAC addresses of the two network cards through aprl, the order is correct, but aprl still uses the adjusted MAC2 address to obtain the IP.
In addition, setting DiskIdxMap=0400, SataPortMap=24, SasIdxMap=0, and adjusting the order and number of hard disks have no effect.
The test installed DS918+, DS3617+, DS3622+, but there are no such problems, and the identification display is normal.
Is there a good solution to these problems of compiling and booting DS920+?

**Comment by AuxXxilium** [comment]
The DS920+ is a DT Model (Device Tree) so DiskIdxMap and SataPortMap have no effect. 

The Loader uses the ethernet port that is loaded first to optain an ip. so this is normal that you have to check your router. you have to deactivate the unused ethernet controller in bios or plug a second cable in eth2.

**Comment by N04LE7** [comment]
Thanks, I'll try again
