### ISSUE TITLE
你们使用arpl引导的dsm7.1.1可以检查到在线升级吗?

### ISSUE THREAD

**Issue by mty0313** [fbelavenuto/arpl#709]
我当前是update4, 检查升级一直是网络失败, 但是套件安装正常, 检查/etc/hosts下也没有额外内容, 不知道问题出在哪里?

**Comment by Yanajnp** [comment]
wz304 化了很大精力，方便大家自由编译群晖各个型号和版本，最后还是闭关了。

**Comment by 412498569** [comment]
不行

**Comment by mty0313** [comment]
我手动下载安装包, 已经成功更新update5

**Comment by ancelee** [comment]
可以在线更新，已成功升级到update5

**Comment by tjpicole** [comment]
可以检测到，之前是update4，运行了50多天，之前我经常去手刷群晖官网看看有没有新版本的。最近也忘了去官网看了，倒是提示有新版本，然后官网一看，有update5了，很不错！

**Comment by mty0313** [comment]
> 可以检测到，之前是update4，运行了50多天，之前我经常去手刷群晖官网看看有没有新版本的。最近也忘了去官网看了，倒是提示有新版本，然后官网一看，有update5了，很不错！

挺奇怪的, 我用的是1.1beta2引导, 就是搜不到, 不过手动更新一下也行, 搜不到就算了

**Comment by Zywz955** [comment]
可以啊 直接在线升级到了update5
