### ISSUE TITLE
Again: Using cmdline parameters "SataPortMap" and "DiskIdxMap"

### ISSUE THREAD

**Issue by TineUser** [fbelavenuto/arpl#721]
I want to use arpl with a LSI 2308 SAS HBA controller on a virtual machine (VMware ESXi 8.0 U1). The HBA controller is in IT mode and is directly attached to the VM (passthrough).

Because of 2 SATA VMDKs I see 60 SATA ports in arpl but not the HBA controller. In TCRP (TinyCore Redpill) I can change this by setting SataPortMap=1 and DiskIdxMap=1000. Then I see the drives attached to the HBA controller. This is OK but the update of DSM and TCRP is very tricky and not really reliable. With a HA cluster of DSM you don't have enough time to do the update of a cluster node before the passive node is deleted from the cluster by the active node and the update is stopped. It took me hours to get the HA cluster up and running again! And it takes hours to synchronize the data between the nodes for the first time.

Updating DSM and arpl is much easier! I have a little test environment with a DSM cluster but without SAS HBA controller. The update works smoothly.

My last issue was set to closed (https://github.com/fbelavenuto/arpl/issues/508) and I'm not able to reopen it. So I open a new issue after one more fail with a DSM update (Update 5) and TinyCore Redpill on a clustered XPEnology. So I decided to give arpl a try. But with the suggested cmdline parameters

SataPortMap=118
DiskIdxMap=080900

the system won't boot. When not setting these parameters the system boots but doesn't show the disks attached to the LSI 2308 SAS HBA controller on a virtual machine (VMware ESXi 8.0). The HBA controller is in IT mode and is directly attached to the VM (passthrough).

Because of 2 SATA VMDKs I see 60 SATA ports in arpl but not the HBA controller. In TCRP (TinyCore Redpill) I can change this by setting SataPortMap=1 and DiskIdxMap=1000. Then I see the drives attached to the HBA controller. But these parameter do not work in arpl.

Does someone know what to do for getting the data disks running with arpl?

**Comment by TineUser** [comment]
With

SataPortMap=118
DiskIdxMap=010203

the system boots and shows the physical disks but I don't see the first virtual disk the was used for TCRP, Docker and applications like HyperBackup etc.

**Comment by TineUser** [comment]
I followed this guide: https://gugucomputing.wordpress.com/2018/11/11/experiment-on-sata_args-in-grub-cfg/

DiskIdxMap=XXYYZZ (HEXadecimal number: XX is the location of first disk of 1st controller, YY  is the location of first disk of 2nd controller, ZZ is the location of first disk of 3rd controller)
SataPortMap=ABC (Decimal number: A is max disks of 1st controller, B is max disks of 2nd controller, C is max disks of 3rd controller)

**Comment by TineUser** [comment]
I tried some other settings but I only get the 21 GB VM disk or the 4 physical disks mounted.

I also found a configuration issue in the VM. I had to reconfigure the VM disks and forgot to check the settings of the SATA controllers. Now I corrected this to SATA 0:0 for the arpl boot disk and SATA 1:0 for the 21 GB VM disk (before it was 0:0 and 0:1).

Now, with

SataPortMap=118
DiskIdxMap=010002

I only see the 21 GB VM disk on slot 1 in DSM. The 4 physical disks should start with slot 3. This would be the same configuration as with TCRP and would correspond to my cluster settings.

**Comment by TineUser** [comment]
Here's the lspci -kkq data of the running DSM node:

0000:02:00.0 SATA controller: VMware SATA AHCI controller
        DeviceName: sata0
        Subsystem: VMware SATA AHCI controller
        Kernel driver in use: ahci
0000:02:01.0 SATA controller: VMware SATA AHCI controller
        DeviceName: sata1
        Subsystem: VMware SATA AHCI controller
        Kernel driver in use: ahci
0000:02:02.0 USB controller: VMware USB1.1 UHCI Controller
        DeviceName: usb
        Subsystem: VMware Device 1976
        Kernel driver in use: uhci_hcd
0000:02:03.0 USB controller: VMware USB2 EHCI Controller
        DeviceName: ehci
        Subsystem: VMware USB2 EHCI Controller
        Kernel driver in use: ehci-pci
0000:03:00.0 Ethernet controller: VMware VMXNET3 Ethernet Controller (rev 01)
        DeviceName: Ethernet0
        Subsystem: VMware VMXNET3 Ethernet Controller
        Kernel driver in use: vmxnet3
0000:0b:00.0 Ethernet controller: VMware VMXNET3 Ethernet Controller (rev 01)
        DeviceName: Ethernet1
        Subsystem: VMware VMXNET3 Ethernet Controller
        Kernel driver in use: vmxnet3
0000:13:00.0 Serial Attached SCSI controller: Broadcom / LSI SAS2308 PCI-Express Fusion-MPT SAS-2 (rev 05)
        DeviceName: pciPassthru0
        Subsystem: Broadcom / LSI SAS9207-4i4e
0001:09:00.0 SATA controller: Marvell Technology Group Ltd. 88SE9235 PCIe 2.0 x2 4-port SATA 6 Gb/s Controller (rev 11)
0001:0c:00.0 SATA controller: Marvell Technology Group Ltd. 88SE9235 PCIe 2.0 x2 4-port SATA 6 Gb/s Controller (rev 11)

**Comment by TineUser** [comment]
Even following https://github.com/fbelavenuto/arpl-modules/issues/38#issuecomment-1337184296 doesn't help.

I installed the module "lsiutil". When running DSM and connecting with SSH lsiutil shows the following:

```
sudo lsiutil

LSI Logic MPT Configuration Utility, Version 1.71, Sep 18, 2013
modprobe: FATAL: Module mptctl not found.
/bin/mknod: /dev/mptctl: File exists

0 MPT Ports found
```

It looks like the drivers for the LSI 2308 SAS HBA controller aren't available or aren't loaded.

**Comment by aniel300** [comment]
i never got it to start from 1 or 0 but i will giving your finding a try and report back

**Comment by wjz304** [comment]
> Here's the lspci -kkq data of the running DSM node:
> 
> 0000:02:00.0 SATA controller: VMware SATA AHCI controller DeviceName: sata0 Subsystem: VMware SATA AHCI controller Kernel driver in use: ahci 0000:02:01.0 SATA controller: VMware SATA AHCI controller DeviceName: sata1 Subsystem: VMware SATA AHCI controller Kernel driver in use: ahci 0000:02:02.0 USB controller: VMware USB1.1 UHCI Controller DeviceName: usb Subsystem: VMware Device 1976 Kernel driver in use: uhci_hcd 0000:02:03.0 USB controller: VMware USB2 EHCI Controller DeviceName: ehci Subsystem: VMware USB2 EHCI Controller Kernel driver in use: ehci-pci 0000:03:00.0 Ethernet controller: VMware VMXNET3 Ethernet Controller (rev 01) DeviceName: Ethernet0 Subsystem: VMware VMXNET3 Ethernet Controller Kernel driver in use: vmxnet3 0000:0b:00.0 Ethernet controller: VMware VMXNET3 Ethernet Controller (rev 01) DeviceName: Ethernet1 Subsystem: VMware VMXNET3 Ethernet Controller Kernel driver in use: vmxnet3 0000:13:00.0 Serial Attached SCSI controller: Broadcom / LSI SAS2308 PCI-Express Fusion-MPT SAS-2 (rev 05) DeviceName: pciPassthru0 Subsystem: Broadcom / LSI SAS9207-4i4e 0001:09:00.0 SATA controller: Marvell Technology Group Ltd. 88SE9235 PCIe 2.0 x2 4-port SATA 6 Gb/s Controller (rev 11) 0001:0c:00.0 SATA controller: Marvell Technology Group Ltd. 88SE9235 PCIe 2.0 x2 4-port SATA 6 Gb/s Controller (rev 11)

`Ls/sys/block/sd * ` What does it return?

**Comment by TineUser** [comment]
> > Here's the lspci -kkq data of the running DSM node:
> > 0000:02:00.0 SATA controller: VMware SATA AHCI controller DeviceName: sata0 Subsystem: VMware SATA AHCI controller Kernel driver in use: ahci 0000:02:01.0 SATA controller: VMware SATA AHCI controller DeviceName: sata1 Subsystem: VMware SATA AHCI controller Kernel driver in use: ahci 0000:02:02.0 USB controller: VMware USB1.1 UHCI Controller DeviceName: usb Subsystem: VMware Device 1976 Kernel driver in use: uhci_hcd 0000:02:03.0 USB controller: VMware USB2 EHCI Controller DeviceName: ehci Subsystem: VMware USB2 EHCI Controller Kernel driver in use: ehci-pci 0000:03:00.0 Ethernet controller: VMware VMXNET3 Ethernet Controller (rev 01) DeviceName: Ethernet0 Subsystem: VMware VMXNET3 Ethernet Controller Kernel driver in use: vmxnet3 0000:0b:00.0 Ethernet controller: VMware VMXNET3 Ethernet Controller (rev 01) DeviceName: Ethernet1 Subsystem: VMware VMXNET3 Ethernet Controller Kernel driver in use: vmxnet3 0000:13:00.0 Serial Attached SCSI controller: Broadcom / LSI SAS2308 PCI-Express Fusion-MPT SAS-2 (rev 05) DeviceName: pciPassthru0 Subsystem: Broadcom / LSI SAS9207-4i4e 0001:09:00.0 SATA controller: Marvell Technology Group Ltd. 88SE9235 PCIe 2.0 x2 4-port SATA 6 Gb/s Controller (rev 11) 0001:0c:00.0 SATA controller: Marvell Technology Group Ltd. 88SE9235 PCIe 2.0 x2 4-port SATA 6 Gb/s Controller (rev 11)
> 
> `ls /sys/block/sd*` What does it return?

You mean  `ls -lh /sys/block/sd*`, right?

`lrwxrwxrwx 1 root root 0 May  4 14:21 /sys/block/sda -> ../devices/pci0000:00/0000:00:11.0/0000:02:01.0/ata2/host1/target1:0:0/1:0:0:0/block/sda`

**Comment by wjz304** [comment]
> @wjz304
> 
> Change in disks addon:
> 
> ```
> # sysfs is populated here
> SATA_PORTS=`ls /sys/class/ata_port | wc -w`
> [ -d '/sys/class/sas_phy' ] && SAS_PORTS=`ls /sys/class/sas_phy | wc -w`
> [ -d '/sys/class/scsi_disk' ] && SCSI_PORTS=`ls /sys/class/scsi_disk | wc -w`
> NUMPORTS=$((${SATA_PORTS}+${SAS_PORTS}+${SCSI_PORTS}))
> ```
Thank you, because I don't have much related hardware to test. So I never knew what 'sas_phy' meant. Your reply makes me understand.

**Comment by wjz304** [comment]
@TineUser 

 You can also use ARC or modify it yourself for quick testing,

**Comment by TineUser** [comment]
> @TineUser
> 
> You can use ARC or modify it yourself for quick testing,

How can I do this? What is ARC?

**Comment by AuxXxilium** [comment]
Arc in my Github repo or you use @wjz304 arpl version (he updated the addons and fixed it some hours ago)

**Comment by TineUser** [comment]
No luck :-(. It's still the same behavior. I think the problem is that the driver for the LSI controller isn't loaded. But I don't know why I see the physical disks when using

```
SataPortMap=118
DiskIdxMap=010203
```

**Comment by AuxXxilium** [comment]
You updated addons in update menu of arpl?

**Comment by AuxXxilium** [comment]
by the way: for lsi and esxi it's better to attach the disks as physical drive to vm and not the controller. so only passthrough the disks and not the controller. have the same issue with passthrough controller in esxi 8. but it is working in 7.0U3g.

**Comment by TineUser** [comment]
TCRP doesn't habe issues with passthroughed controller - neither with ESXi 7.0 U3 nor with ESXi 8.0 U1.

**Comment by TineUser** [comment]
> You updated addons in update menu of arpl?

I updatet ARPL-i18n by the update function of the loader. But when rebooting the bootloader wasn't found. I had to use the new VMDK flat file and reconfigure ARPL-i18n from scratch.

**Comment by wjz304** [comment]
> > 您在 arpl 的更新菜单中更新了插件？
> 
> 我通过加载器的更新功能更新了 ARPL-i18n。但是重新启动时找不到引导加载程序。我不得不使用新的 VMDK 平面文件并从头开始重新配置 ARPL-i18n。

Because a small number of people use Legacy BIOS and cannot access the boot interface,
So I updated Grub and it is not compatible with the original Grub.

**Comment by TineUser** [comment]
> > > You updated addons in update menu of arpl?
> > 
> > 
> > I updatet ARPL-i18n by the update function of the loader. But when rebooting the bootloader wasn't found. I had to use the new VMDK flat file and reconfigure ARPL-i18n from scratch.
> 
> Because a small number of people use Legacy BIOS and cannot access the boot interface, So I updated Grub and it is not compatible with the original Grub.

Then you should deactiviate the ARPL-i18n update function so that only addons, modules etc. can be updated by the menu.

**Comment by AuxXxilium** [comment]
no you have to update all things in update menu. Am 05.05.2023 um 09:37 schrieb TineUser ***@***.***>:﻿



You updated addons in update menu of arpl?

I updatet ARPL-i18n by the update function of the loader. But when rebooting the bootloader wasn't found. I had to use the new VMDK flat file and reconfigure ARPL-i18n from scratch.

Because a small number of people use Legacy BIOS and cannot access the boot interface, So I updated Grub and it is not compatible with the original Grub.

Then you should deactiviate the ARPL-i18n update function so that only addons, modules etc. can be updated by the menu.

**Comment by wjz304** [comment]
> > > > 您在 arpl 的更新菜单中更新了插件？
> > > 
> > > 
> > > 我通过加载器的更新功能更新了 ARPL-i18n。但是重新启动时找不到引导加载程序。我不得不使用新的 VMDK 平面文件并从头开始重新配置 ARPL-i18n。
> > 
> > 
> > 因为少数人使用旧版 BIOS 并且无法访问启动界面，所以我更新了 Grub，它与原始 Grub 不兼容。
> 
> 然后，您应该停用ARPL-i18n更新功能，以便仅使用插件，模块等。可以通过菜单更新。

Yes,  this is my problem. the current update function judgment is not rigorous, but the check modification of the version number is quite complex

**Comment by TineUser** [comment]
> Arc in my Github repo or you use @wjz304 arpl version (he updated the addons and fixed it some hours ago)

Tried no ARC - I never heard of it before. But here's the same issue. ARC has more options for checking system. So here I see that the LSI controller is passthroughed:

![image](https://user-images.githubusercontent.com/77736099/236405179-b57274b6-024b-489b-8931-156b5a4733dd.png)

But it doesn't find the disks attached to the LSI controller. I don't understand why.

**Comment by AuxXxilium** [comment]
do you use latest firmware for your controller, do you have enable "option rom" in bios/uefi for pcie port of the controller.

**Comment by TineUser** [comment]
> by the way: for lsi and esxi it's better to attach the disks as physical drive to vm and not the controller. so only passthrough the disks and not the controller. have the same issue with passthrough controller in esxi 8. but it is working in 7.0U3g.

And what about S.M.A.R.T with passthroughed disks? This doesn't work then, right? I had so much issues with disks. So I want to know if a disk is going to be dead before losing data. Yes I have backup but the restore tooks more time than switching the disk before the dead of a disk.

**Comment by TineUser** [comment]
> No luck :-(. It's still the same behavior. I think the problem is that the driver for the LSI controller isn't loaded. But I don't know why I see the physical disks when using
> 
> ```
> SataPortMap=118
> DiskIdxMap=010203
> ```

With ARC the above settings won't work. I only see the 21 GB virtual disk on slot 3 in DSM. So this is what is to be expected at this point.

**Comment by TineUser** [comment]
> do you use latest firmware for your controller, do you have enable "option rom" in bios/uefi for pcie port of the controller.

I will do a reboot of the ESXi host today at later time to be sure that the physical disks are seen by the controller. I will also check for "option rom" to be safe that it's enabled. The controller is in IT mode so it's not useable as hardware RAID controller.

**Comment by AuxXxilium** [comment]
If you use sas or scsi controller. diskidxmap and sataportmap have no effect. thats normal and in description of redpill. you can use the automated settings while model selection if you you see the drives in sysinfo menu.

**Comment by kaneske** [comment]
If he has 2 Controller of the ESXi besides the HBA and they're the first 2 in the Row, SataPortMap 118 is right for him (why are there 2 Controllers in his VM???)

The the DiskIdxMap 090A08 (if the last Controller is the HBA should work.

Or am I wrong?

**Comment by AuxXxilium** [comment]
090A00 is that what you mean. if you use 08 at last, you can only attach 1 disk. but for scsi and sas controller these mapping wont work and all disks if them will be shown after all sata disks. if you map your sata disks to port 9 and 10 the sas/scsi disks starts from port 11 in dsm. Am 05.05.2023 um 12:51 schrieb TineUser ***@***.***>:﻿

do you use latest firmware for your controller, do you have enable "option rom" in bios/uefi for pcie port of the controller.

I will do a reboot of the ESXi host today at later time to be sure that the physical disks are seen by the controller. I will also check for "option rom" to be safe that it's enabled. The controller is in IT mode so it's not useable as hardware RAID controller.

**Comment by AuxXxilium** [comment]
according to the screenshot above, he has to use sataportmap 11 and diskidxmap 0001. nothing else.

**Comment by kaneske** [comment]
Strange since my Rig with Two HBA of 2008 LSI with 12 attached Disks and 1 VM SATA Controller works flawlessly with 0C0008 and 188...

**Comment by AuxXxilium** [comment]
a link to study for everone:

https://gugucomputing.wordpress.com/2018/11/11/experiment-on-sata_args-in-grub-cfg/

**Comment by TineUser** [comment]
```
SataPortMap=11
DiskIdxMap=0100
SasIdxMap=0
```
No luck :-(.

There are 2 virtual SATA controller in VM because of the bootloader disk an a 21 GB disk which is needed for the TCRP install and a small data partition for DSM apps like docker, anti virus etc.

**Comment by wjz304** [comment]
DiskIdxMap=ff0102
I'm not an expert in this field, but you can try it out
