### ISSUE TITLE
Freezing At First Boot

### ISSUE THREAD

**Issue by huseyinergen** [fbelavenuto/arpl#786]
Hello everyone.
I have installed it completely. It gets ip address but always freezes in 5 seconds. The keyboard does not work at this time and i can't reach nas ip address.

Can anybody help me?
I have an intel i5 CPU and 16gb ddr3 ram.

**Comment by wunihehuan** [comment]
中国人吧

**Comment by huseyinergen** [comment]
i don't understand

**Comment by guishuangxi** [comment]
May be the network interface does not support,you should not use virtIO type.

**Comment by huseyinergen** [comment]
i changed the Hardware and work. Thank you
