### ISSUE TITLE
Question about whether the hard disk is in the compatibility list of Synology

### ISSUE THREAD

**Issue by look-dc** [fbelavenuto/arpl#79]
With the same configuration, I installed the system with a hard disk that is in the Synology compatibility list, and it can be used normally. After installing it with a disk that is not in the compatibility list, it will prompt that DSM is not installed. Is this a setting problem in arpl?

**Comment by fbelavenuto** [comment]
Yes! Please test with latest build (0.3a8).

**Comment by look-dc** [comment]
> Yes! Please test with latest build (0.3a8).

Tried 0.3a8 today
I used a disk that will not be reinstalled after restarting to test and then put the sata ssd in it and found that the system partition of the sata ssd was damaged after the restart.

**Comment by fbelavenuto** [comment]
Please, test the v0.4-alpha8 release

**Comment by fbelavenuto** [comment]
Closing, if the issue persists, please reopen
