### ISSUE TITLE
How to add external ，eg： mpt2sas  vmnet3

### ISSUE THREAD

**Issue by maye459453500** [fbelavenuto/arpl#80]
I tryed to add external mpt2sas  vmnet3 from [pico](https://github.com/pocopico/rp-ext)  ，Prompts an format error，how to use drivers eg:mpt2sas  vmnet3

Thanks!

**Comment by fbelavenuto** [comment]
The ARPL addon system does not support redpill extensions.
These modules already exist and are automatically loaded. Use the latest image version.

**Comment by fbelavenuto** [comment]
If exists another trouble, please open a new issue
