### ISSUE TITLE
How downgrade 7.1.1 42921 to 7.1 42661

### ISSUE THREAD

**Issue by sashakozlov86** [fbelavenuto/arpl#82]
Good afternoon!  I have arpl bootloader version 0.3a7, everything worked well.  I inadvertently upgraded DSM on DVA1622 from version 7.1 42661 to version 7.1.1 42921. Now the DSM won't boot (configuration and bootloader assembly is loading, where I can build the bootloader for DSM version 7.1 42661).  I tried to rebuild the bootloader, but it does not help.  How can I downgrade?  Thank you!

UPD: I tried to create the bootloader again and reboot.  The DSM web interface became available and prompted me to reinstall the system.  When I tried to reinstall the system, I selected the DVA1622 42661.pat file, but during the process of forming the DSM system partition, I wrote that I could not format the disk

**Comment by fbelavenuto** [comment]
Hi, cannot downgrade, DSM limitation!
But wait to add the new buildnumber to loader, then will be possible to resolve your issue

**Comment by sashakozlov86** [comment]
Thank you!  I'm looking forward to it!  Please let me know how you do it.

**Comment by fbelavenuto** [comment]
You can update loader now

**Comment by sashakozlov86** [comment]
Thank you friend!  It really helped!
