### ISSUE TITLE
Warning, running kexec with --noefi param, strange things will happen!!

### ISSUE THREAD

**Issue by MIKEMC606** [fbelavenuto/arpl#83]
Hi there!
There was was a fully working system : 7.1 42661 (3615xs) with 0.3-alpha4 loader.  Config : GIGABYTE H410M S2 V3 + Celeron G5905, 8Gb DDR4 Patriot Signature Line., 4 HDD
After reassembling the system in another case - now i have this yellow-colored error  :   Warning, running kexec with --noefi param, strange things will happen!!
Making new loader 0.3-alpha8 not solving this error.
Has anyone encountered a similar problem?

**Comment by fbelavenuto** [comment]
It's not a loader bug! The DS3615xs kernel has a bug with uefi, for this model configure your motherboard to boot via CSM (if possible) or consider switching to 3617 or 3622

**Comment by MIKEMC606** [comment]
But somehow -earlier this configuration worked! All I did was move hardware to another case...

**Comment by fbelavenuto** [comment]
If exists another trouble, please open a new issue
