### ISSUE TITLE
7.1.0-42661 to 7.1.1-42951 update error

### ISSUE THREAD

**Issue by dalso0418** [fbelavenuto/arpl#84]
Hello, how are you doing?

Thank you for continuously updating the arpl.
Today, the RC version of 7.1.1 came out, so I manually updated it, but the following error is printed.
![image](https://user-images.githubusercontent.com/107911055/183898105-08f49998-3429-4684-a094-6b22660a3e4b.png)

Please check it when you have time.
Thank you always for the good project.

Note: https://www.synology.com/en-global/releaseNote/DSM?model=DS3622xs%2B#7_1
https://svrforum.com/nas/393446

**Comment by fbelavenuto** [comment]
This is because there is no information in the loader of this new release. We are testing to add to loader.
Before upgrading to a new release or a new smallupdate, wait for testing information on the forum, as a new release can have a lot of changes and break your installation.
This is the reason for not leaving automatic update by default.

**Comment by dalso0418** [comment]
I'm running a small community, so I updated it first in the system under test.

I always use the arpl with a grateful heart.
If it is updated, I will test it again. Please feel free to let me know if there is a platform that needs to be tested.
Have a nice day today!

**Comment by fbelavenuto** [comment]
Sorry if it sounded rude of me, I have language difficulties too.
I'm testing each model to make sure there is no error, so you can update the loader to test.

**Comment by dalso0418** [comment]
Oh, it wasn't rude at all.
I am also not used to English as a Korean, so I rely on a translator
😊lol

**Comment by fbelavenuto** [comment]
You can update loader now

**Comment by green1052** [comment]
https://svrforum.com/nas/393677

![image](https://user-images.githubusercontent.com/34261355/183926866-205610dc-cc49-40b1-915b-83a0da2899b9.png)

sadly not working

**Comment by fbelavenuto** [comment]
Sorry, some trouble with old versions! Please burn the new .img file, recreate loader with same model and test

**Comment by dalso0418** [comment]
Proxmox에서 테스트 결과 드립니다.

42218이나 42951로 빌드시 에러가 나오고있습니다.
![image](https://user-images.githubusercontent.com/107911055/184049338-6c3dd6f4-6d84-40c2-a619-0a99087a7477.png)

![image](https://user-images.githubusercontent.com/107911055/184049289-2929f842-69d3-4376-a7e1-dbc0f42735a2.png)
![image](https://user-images.githubusercontent.com/107911055/184049327-5d451295-9229-4c3a-be22-14fbade4cfb6.png)
![image](https://user-images.githubusercontent.com/107911055/184049343-e6ea3872-c445-4d95-abc1-24569130d1c2.png)

**Comment by fbelavenuto** [comment]
I'll investigate this bug.
