### ISSUE TITLE
waitting ip... Error

### ISSUE THREAD

**Issue by green1052** [fbelavenuto/arpl#9]
but i can access web console

**Comment by green1052** [comment]
b660m-b Realtek® RTL8125BG 2.5Gbps LAN controller

**Comment by fbelavenuto** [comment]
Try alpha6:
https://github.com/fbelavenuto/arpl/releases/download/v0.1-alpha6/arpl-0.1-alpha6.img.zip

**Comment by green1052** [comment]
thx i will try soon!

but how can save data?
like seral, mac, etc..

**Comment by green1052** [comment]
i tested 0.2-alpha1 but not wokring

**Comment by green1052** [comment]
umm web console showing ip

but real console showing error

**Comment by fbelavenuto** [comment]
I will increase the timeout

**Comment by fbelavenuto** [comment]
Timeout increased, please test with 0.3-alpha1

**Comment by green1052** [comment]
its working thx
