### ISSUE TITLE
grub not using predictable ifnames for network interfaces

### ISSUE THREAD

**Issue by r0bb10** [fbelavenuto/arpl#93]
Loader sais that eth0 is not found, probably because the network interface has a different name.. could be fixed using net.ifnames and biosdevnames in grub.

![image](https://user-images.githubusercontent.com/16479888/184365206-711bba5c-f864-47f9-a54f-d8dabf216e82.png)

**Comment by fbelavenuto** [comment]
Please test with this images:
https://github.com/fbelavenuto/arpl/actions/runs/2847319270

**Comment by r0bb10** [comment]
works :) no more error and interface has common eth0 name :)

![image](https://user-images.githubusercontent.com/16479888/184418651-952d563f-1a4f-4884-a3ad-57dd33b0c30c.png)

**Comment by fbelavenuto** [comment]
Cool!! Closing issue
