### ISSUE TITLE
ARPL 0.4a2 DVA3219 Ramdisk is not patched

### ISSUE THREAD

**Issue by sashakozlov86** [fbelavenuto/arpl#95]
Hello dear friend!  When trying to install (build) the DVA3219 bootloader on arpl 0.4a2, a message appears that ramdisk is not patched and the assembly is not built.  Have a look, please.  Thank you!
![IMG20220813174057](https://user-images.githubusercontent.com/93244850/184499188-2bd93e32-b79f-497a-b90d-072a449f6a64.jpg)

**Comment by fbelavenuto** [comment]
Please test with this release:
https://github.com/fbelavenuto/arpl/releases/tag/v0.4-alpha4

**Comment by fbelavenuto** [comment]
Old issue without answer, closing it. If the trouble is not fixed, please re-open this issue.
