### ISSUE TITLE
HP Microserver Gen8 compatibility

### ISSUE THREAD

**Issue by mmkt1** [fbelavenuto/arpl#96]
with ARPL 04.a2 I can't install DSM due to HDD formating error. 
I attached a complete dev log of the building prozess and the first reboot after loader creation untill the DSM HDD format error is prompted in the web panel.
After a lot of tests I found that if I use the same Crucial HDD with a allready installed working DSM on it (TinyCoryLoader), I can install DSM with arpl and do not end up in a install loop and the loader works fine....
The formating error depends not on the used NIC! Thats the reason why I added the log with the intel NIC.

Additional I added the log tcrp.log of the same building and boot process of tinycore loader. Maybe you see a relevant difference

[arpl_intelnic.log](https://github.com/fbelavenuto/arpl/files/9331733/arpl_intelnic.log)
[tcrp.log](https://github.com/fbelavenuto/arpl/files/9331742/tcrp.log)
.

**Comment by fbelavenuto** [comment]
I found the error, I will fix it in the next release. Thanks

**Comment by fbelavenuto** [comment]
Please test with this image:
https://github.com/fbelavenuto/arpl/actions/runs/2877632349

**Comment by fbelavenuto** [comment]
Please, test the v0.4-alpha8 release

**Comment by mmkt1** [comment]
it's working since 0.4a8.
Thanks!!
