### ISSUE TITLE
failed to install DSM. file is probably corrupted

### ISSUE THREAD

**Issue by gcat000** [fbelavenuto/arpl#97]
if I try to install the DSM 7.1 on a new one disk - an error occurs "failed to install DSM. file is probably corrupted"
this error can be avoided by turning off internet access during installation
when I try to migrate from 6.2.3 - this error occurs constantly and DSM cannot be installed

PS broadwellnk-7.1.0-42661

**Comment by Cryental** [comment]
Try to upgrade from 6.2.3 to 7.0.1-42218, then 42661. It can help I think.

**Comment by fbelavenuto** [comment]
Please try to do what @Cryental commented, and make sure you are using the correct file "DSM_xxxx_42xxx.pat".

**Comment by fbelavenuto** [comment]
Some sucess?

**Comment by gcat000** [comment]
yes, thank you, now all done! ds3622xs+, DSM7.1-42661 and arpl 0.4-alpha1
