### ISSUE TITLE
Can"t activate functions (codecs etc)

### ISSUE THREAD

**Issue by oleging** [fbelavenuto/arpl#98]
Can"t activate functions (codecs etc) with real sn, mac & sino account - connection error.

**Comment by fbelavenuto** [comment]
This is not a bug, when creating the loader remove the lines with "example.com" in the synoinfo menu

**Comment by oleging** [comment]
Thanks, I will try.

**Comment by fbelavenuto** [comment]
If exists another trouble, please open a new issue
